### ISSUE TITLE
busboy emits `end` possibly at the wrong moment

### ISSUE THREAD

**Issue by asnowfix** [mscdex/busboy#1]
busboy emits `end` at the end of the parsing of parts, but nothing at the end of the processing of parts. Therefore it is not possible to trigger a cleanup/collection after the end of the processing.

As a result, the code provided by https://github.com/senchalabs/connect/issues/898#issuecomment-24558457 cannot be chained with a post-processing step that deals with every parts at a time.

**Comment by rla** [comment]
@talha-asad got it right. You need your own complex machinery to detect when processing of file data is finished. Having a callback on the `file` event would have made that way easier.
