### ISSUE TITLE
accepting files through busboy on another page

### ISSUE THREAD

**Issue by jayknowstheway** [mscdex/busboy#107]
I am trying to accept mp3s through my site using Node.js and busboy. I've been able to do this just fine on the homepage, using this code:

```javascript
// accept POST request on the homepage
app.post(__dirname + '/', function(req, res) {
    var busboy = new Busboy({
        headers: req.headers
    });
    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
        var saveTo = path.join('./uploads', filename);
        console.log('Uploading: ' + saveTo);
        file.pipe(fs.createWriteStream(saveTo));
    });
    busboy.on('finish', function() {
        console.log('Upload complete');
        res.writeHead(200, {
            'Connection': 'close'
        });
        res.end("UPLOAD COMPLETE!");
    });
    return req.pipe(busboy);
});
```

I am trying to accept files in the same way on another page on my website: /pages/secondpage.html but I get a Cannot POST /pages/secondpage.html

Here's my client side code on both pages:

```html
<form method="POST" enctype="multipart/form-data" id="uploadform">
  <input type="file" name="filefield">
  <input type="submit" id="submit" value="SUBMIT">
</form>
```

Does anyone have any ideas on how to get file uploads working on the second page?

**Comment by mscdex** [comment]
This seems unrelated to busboy as it looks like it's just not finding your Express route. Have you tried inserting a `console.log()` inside the route handler to ensure that it's being called for your other page?

**Comment by kuba12kozak** [comment]
You don't have any action in your form.
