### ISSUE TITLE
event 'finish' emit before 'file', and then cannot check fields

### ISSUE THREAD

**Issue by acrazing** [mscdex/busboy#113]
the busboy code as follow:

```js
const busboy = new Busboy({headers: req.headers});
let to = '';
let done = 0;
let data = '';
let write = () => {
  if (done < 2) {
    return;
  }
  console.log('start write');
  fs.writeFile(to, data, null, (err) => {
    if (err) {
      res.writeHeader(500);
      return res.end('write file error' + err.toString());
    }
    console.log('file write done');
    res.end('1');
  })
};
busboy.on('file', (field, file) => {
  if (field !== 'file') {
    return;
  }
  done += 1;
  file.on('data', chunk => data += chunk);
  file.on('end', () => write() || console.log(field, data))
});
busboy.on('field', (field, val) => {
  if (field !== 'to') {
    return;
  }
  if (val.startsWith(root + base) === false) {
    res.writeHeader(406);
    return res.end('forbidden path');
  }
  mkdirp(path.dirname(val), (err) => {
    if (err) {
      res.writeHeader(500);
      return res.end('make dir error' + err.toString());
    }
    console.log(field, val);
    done += 1;
    to = val;
    write();
  })
});
busboy.on('finish', () => done < 2 && (res.writeHeader(400) || console.log('finish', done) || res.end('body parse error')));
```

when I use curl send a request as follow:

```bash
curl -v --form "file=@package.json" --form "to=/home/work/abc/abc/abc" "http://localhost:8019/?base=/abc/abc&token=xxx"
```

the output of console as follow:

```bash
[package.json content]

finish 1
to /home/work/bjpt/abc/abc
start write
file write done
```

the event `finish` emit before event `file`!

**Comment by mscdex** [comment]
Can you provide an example `package.json` that duplicates the behavior?

**Comment by acrazing** [comment]
@mscdex just a normal package.json of mine project:

```json
{
  "name": "fis-listener",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "***"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "busboy": "*",
    "mkdirp": "*"
  },
  "devDependencies": {
    "fis3": "*"
  }
}
```

**Comment by mscdex** [comment]
I'm not able to reproduce the problem. However what is likely happening is that the entire stream is being read into memory, `finish` is emitted (because all streams were completely read from), and then your `writeFile()` callback is called.

So as far as I can tell, this is working as intended.

**Comment by acrazing** [comment]
If so, how I know all parts are parsed?

for example: how to handle a form submitted by user? If the `finish` is emitted before `file` or `field`, I cannot know the form parse is finished and then get all fields and files.

**Comment by acrazing** [comment]
I see, thanks

**Comment by mscdex** [comment]
`finish` is only emitted once all `field` events have been emitted and all `file` streams have been completely read from. busboy has no way of knowing what you are doing with the data once you read it from a file stream (such as if you're streaming to disk and the fs.WritableStream happens to take a little while to close after it has read the last chunk from busboy's file stream).

**Comment by acrazing** [comment]
Add `done` in cb of `mkdirp`, it's my fault.

**Comment by mscdex** [comment]
One additional suggestion is that you might want to change this:

```javascript
  if (field !== 'file') {
    return;
  }
```

to this:

```javascript
  if (field !== 'file') {
    return file.resume();
  }
```

That will allow the unexpected file stream to be skipped.
