### ISSUE TITLE
Busboy hangs

### ISSUE THREAD

**Issue by devlo** [mscdex/busboy#116]
I thought it was because of multer, but i dig a littile bit and found that it's problem with busboy. File event is not called for 6th file every ~20 requests, interesting part is that if i repeat same request couple seconds later everything is ok.. Here is more info:

https://github.com/expressjs/multer/issues/328

And here is additional info:

this is log from request:
```
09:33:01.512 INFO  {"debugId":45,"uri":"https://some.url/route","method":"POST","headers":{"Cookie":"cc=5;key=c588f348;"
,"host":"some.url","content-type":"multipart/form-data; boundary=--------------------------599289528758391892425834","content-length":2927495}}
09:33:01.512 INFO  {"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"some.url","port":443,"hostname":"some.url","hash":null,"search":null,"query
":null,"pathname":"/route","path":"/route","href":"https://some.url/route"},"method":"POST","headers":{"Cookie":"cc=5
;key=c588f348;","host":"some.url","content-type":"multipart/form-data; boundary=--------------------------599289528758391892425834","cont
ent-length":2927495}}
09:33:01.512 INFO   mediainfo end
09:33:01.512 INFO   mediainfo close
09:33:01.558 INFO   photo1 end
09:33:01.558 INFO   photo1 close
09:33:01.563 INFO   photo2 end
09:33:01.563 INFO   photo2 close
09:33:01.565 INFO   photo3 end
09:33:01.565 INFO   photo3 close
```

As you can see all files are properly closed in request.
I've setup loging on busboy events. This is how it looks like on server side:

```
09:33:01.543 INFO  in multerMiddleware
09:33:01.546 INFO   field busboy cc 5
09:33:01.547 INFO   field busboy key c588f348
09:33:01.547 INFO   field busboy name somename
09:33:01.547 INFO   field busboy something yes
09:33:01.548 INFO   field busboy category 11
09:33:01.548 INFO   file busboy somefile somefile.name 7bit application/octet-stream
09:33:01.549 INFO   file busboy nfo some.nfo 7bit text/x-nfo
09:33:01.549 INFO   file busboy media media.info 7bit application/octet-stream
09:33:01.549 INFO   file busboy photo1 screen_1.png 7bit image/png
09:33:01.568 INFO   file busboy photo2 screen_2.png 7bit image/png
```
As you can see file event is called for photo1 and photo2, but not for photo3, it just hangs. Any thoughts?

**Comment by mscdex** [comment]
Can you provide a standalone test (with exact file sizes used) that uses just busboy that I can use to reproduce the problem?

**Comment by devlo** [comment]
Yes, but i need to wait for it to happen, i can't reproduce this myself either. The interesting part is that you mentioned the file sizes, i forgot that if i repeat the request, all photos are recreated. I will test it next time it happens with exactly same files (without recreating) and see if it will occur again, i will report here then.

**Comment by mscdex** [comment]
@devlo Were you ever able to create a standalone test to reproduce the problem?

**Comment by devlo** [comment]
@mscdex 
No. It happens less often now, i am just retrying if it happens, don't really have time to debug this deeper.
