### ISSUE TITLE
Example file saving snippet saves a corrupt file

### ISSUE THREAD

**Issue by Arlen22** [mscdex/busboy#119]
I have run into this before with other file streams, so I'm note sure if I'm not understanding something or what, but when I try to upload a file using the example code on the project page, the file that gets saved has data but cannot be read. The file size is almost double the original file.

```
busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
	var filestream = fs.createWriteStream(filepath);
	file.pipe(filestream);
	file.on('end',function(){
		response.write("[ext[uploads/" + filename + ']]');
	});
});
request.pipe(busboy);
```

**Comment by mscdex** [comment]
What does `console.dir(encoding); console.dir(mimetype)` show? Can you show how are you submitting the multipart request?

**Comment by Arlen22** [comment]
Well, turns out it was a middleware issue which I thought I had fixed, but once I saw that the file size was _bigger_ I started suspecting an encoding problem. The pipe is actually working fine now with express. I'm not quite sure why it was changing the encoding, but once I went directly through Express it worked. My apologies for the false alarm.
