### ISSUE TITLE
Having trouble getting videos of moderate size from server

### ISSUE THREAD

**Issue by kkotwal94** [mscdex/busboy#120]
Im trying to get a video from gridfs after successfully uploading it, checking mongoclient i can see that all the proper subfields lie in there. However I can't figure out why when i try to play certain videos it fails to fetch it (network tab shows 0 bytes received) however for some of them, for example a youtube video downloaded as a mp4, and then uploaded to my web application plays and is fetched fine.

If i go to my api that gets this video 'file/:someid' then the video downloads locally to my computer just fine, but trying to play it on the video player seems to fail. I don't know if im fetching or forgetting properties to set when loading it through busboy or if its a videoplayer problem or something.

I posted this issue with more discrete details on stackoverflow : 

http://stackoverflow.com/questions/36760404/express-multer-uploading-moderate-large-files-not-playing-on-player

The code i have in express is this

```
app.post('/file/video', function(req, res) {
  //console.log(req.body);
  var busboy = new Busboy({ headers : req.headers });
  var fileId = new mongoose.mongo.ObjectId();
  //console.log(req.body);

  busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
    //console.log('got file', filename, mimetype, encoding);
    var writeStream = gfs.createWriteStream({
      _id: fileId,
      filename: filename,
      mode: 'w',
      content_type: mimetype,
    });
    file.pipe(writeStream);
  }).on('finish', function() {
    // show a link to the uploaded file
    req.user.videos.push(fileId);
    req.user.save();
    //console.log(req.user);

    res.end();


    /*var proc = new ffmpeg('/Documents/20000pitches/parkour.mp4')
  .takeScreenshots({
      count: 1,
      timemarks: [ '600' ] // number of seconds
    }, '/', function(err) {
    console.log('screenshots were saved')
  });
*/
  });

  req.pipe(busboy);
});

app.get('/file/:id', function(req, res) {
  gfs.findOne({ _id: req.params.id }, function (err, file) {
    if (err) return res.status(400).send(err);
    if (!file) return res.status(404).send('');

    res.set('Content-Type', file.contentType);
    res.set('Content-Disposition', 'attachment; filename="' + file.filename + '"');

    var readstream = gfs.createReadStream({
      _id: file._id
    });

    readstream.on("error", function(err) {
      console.log("Got error while processing stream " + err.message);
      res.end();
    });

    readstream.pipe(res);
  });
});
```

And video is played like this:

```
<Video style ={{height:'100%', width: '100%'}}poster={singleposts.thumbnail} controls ref="video" onProgress={this.onProgress}>
            <source style = {{width: '100%', height: '100%'}} src={"/file/" + singleposts.videoURL} type="video/mp4" />
        </Video>
```

It decides to hang on the get request for getting the src for my video, like the id and everything is correct i console log it, i check in the browser, etc.

An example is here 
http://20000passions.kkotwal.me/gallery/57185f3e1b237af47940f370
Where it fails vs when it works is here
http://20000passions.kkotwal.me/gallery/56fe76dae94f67c974394d42

I noticed that when it didnt work it was of mp4 format from my phone and the quality and resolution were both high

**Comment by mscdex** [comment]
Closing this as it doesn't seem like a busboy issue, especially since you've identified that downloading the file locally to your system using the same API endpoint works just fine.

My guess is that there is either something wrong with the video player or its configuration, or the server is not sending some information that the video player is expecting (or is sending information that the player is *not* expecting, such as the `Content-Disposition` header).
