### ISSUE TITLE
Link to developer files when dependency is bundled

### ISSUE THREAD

**Issue by abalhier** [mscdex/busboy#121]
Hello !

Thank you for the time and effort you put in this project :)
We used your project recently and we encountered an issue when starting our node server :
```
~/dev/my_project/release • node server.js
fs.js:856
  return binding.readdir(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/abalhier/dev/my_project/node_modules/busboy/lib/types'
    at Error (native)
    at Object.fs.readdirSync (fs.js:856:18)
    at Object.<anonymous> (/Users/abalhier/dev/my_project/release/server.js:10960:4)
    at Object.__dirname.13.module.exports.extractFormDataInputHierachy.28../utils (/Users/abalhier/dev/my_project/release/server.js:10972:4)
    at s (/Users/abalhier/dev/my_project/release/server.js:1:316)
    at /Users/abalhier/dev/my_project/release/server.js:1:367
    at Object.__dirname.13.module.exports.objectFromHierarchyArray.busboy (/Users/abalhier/dev/my_project/release/server.js:1614:16)
    at s (/Users/abalhier/dev/my_project/release/server.js:1:316)
    at /Users/abalhier/dev/my_project/release/server.js:1:367
    at Object.__dirname.13.module.exports.extractFormDataInputHierachy.252.exports.254.257.passport.263.623.../authentication/authentication (/Users/abalhier/dev/my_project/release/server.js:118103:20)
```

We are bundling dependencies and our code with node-browserify which may not be the traditional way to deploy and run node servers, but we feel this issue could be resolved easily by removing the use of __dirname.
Can you take a look at the pull request I am submitting ?

**Comment by mscdex** [comment]
I'd think you'd run into other issues despite this, such as you're trying to run an http server in the browser? If not, I'm curious why else you'd be parsing multipart and/or urlencoded forms in the browser?

**Comment by abalhier** [comment]
No I am not running this in a browser. It's a REST API which accepts file uploads.
We bundle our dependencies because we don't want to clone our project on the server and npm start it.

**Comment by abalhier** [comment]
Are you willing to support the use of your project through a bundle ?
If I was not clear I can try to explain better, and provide an example project for this issue.

**Comment by psulek** [comment]
Hi @abalhier i run to same error when using webpack bundler. In my final "output" folder there is only 1 final bundled JS files "bundle.js" and no folder "types" with required types from busboy, so it fails on such error. I will try @abalhier fix if it helps, but i think this should be fixed.

**Comment by mscdex** [comment]
@psulek Did @abalhier's fix in #122 work for you?

**Comment by psulek** [comment]
@mscdex yes it helps.

**Comment by punkeel** [comment]
Looks like this "bug" was reintroduced by v1.0.0 (https://github.com/mscdex/busboy/blob/54a86838c15bba1fc78eebdfa3c6a986a5e57dd9/lib/index.js#L40-L47). Was it done on purpose, or would you accept PRs similar to #122?
