### ISSUE TITLE
Can I add setHeaders method? 

### ISSUE THREAD

**Issue by Jerret321** [mscdex/busboy#123]
I need control the headers when the formData is parsing. But I cannot find the method in busboy resource code. 

The code like this and overwirte the headers if some context is needed
```javascript
Busboy.prototype.setHeaders = function (extraHeaders){
  if(typeof extraHeaders !== 'object'){
    throw new Error('invalid type');
  }
  for(var i in extraHeaders){
    if(this.opts.headers[i] && extraHeaders[i]){
      this.opts.headers[i] = extraHeaders[i];
    }
  }
  this.parseHeaders(this.opts.headers)
};
```

**Comment by mscdex** [comment]
I don't understand the need for this. Why do you need to mutate it *during* parsing?

**Comment by Jerret321** [comment]
I had solved the problem. It doesn't matter with busboy.  Thanks all the same.
