### ISSUE TITLE
Unsupported content type: application/json 

### ISSUE THREAD

**Issue by kalitas** [mscdex/busboy#125]
after i set this (due to cross domain problem):
app.all('*', function(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'PUT, GET, POST, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type');
  next();
});

i get this Error: Unsupported content type: application/json
    at Busboy.parseHeaders (/Users/dang/Documents/applicaster/tapawayAws/node_modules/busboy/lib/main.js:68:9)
    at new Busboy (/Users/dang/Documents/applicaster/tapawayAws/node_modules/busboy/lib/main.js:21:10)

here are the req with the headers:
_consuming:false
_dumped:false
_events:Object
_eventsCount:0
_maxListeners:undefined
_parsedUrl:Url
_readableState:ReadableState
baseUrl:""
client:Socket
complete:false
connection:Socket
domain:null
headers:Object
accept:"application/json, text/plain, */*"
accept-encoding:"gzip, deflate"
accept-language:"en-US,en;q=0.8,he;q=0.6"
cache-control:"no-cache"
connection:"keep-alive"
content-length:"70"
content-type:"application/json;charset=UTF-8"
host:"localhost:9000"
origin:"http://0.0.0.0:9000"
pragma:"no-cache"
referer:"http://0.0.0.0:9000/"
user-agent:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
__proto__:Object
httpVersion:"1.1"
httpVersionMajor:1
httpVersionMinor:1
method:"POST"
next:function next(err) { … }
 
here is how i use this:
app.post('/makepayment', function(req, res) {
    var busboy = new Busboy({ headers: req.headers });
    var savedData = {};
    busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated) {
      console.log('Field [' + fieldname + ']: value: ' + inspect(val));
      savedData[fieldname] = val;
    });
  
    busboy.on('finish', function() {
      if (savedData.orderId !== undefined && savedData.applicationName !== undefined){
        Transactions.initParseWithKeys(savedData.applicationName); 
        Transactions.makePaymentRequestGotten(savedData.orderId, savedData.finalPrice, function(result) {
           res.status(200);
           if (result !== undefined){
            if (result.response === 'success'){
              res.json(result);
            }
            else{
              res.json({'response' : 'error', 'body' : result.body});
            }
           }
           else{
              res.json({'response' : 'error', 'body' : result.body});
           }
        });
      }
      else{
          res.status(404);
          res.json({'response': "error", 'body' : 'params is missing'});
      }
    });
    return req.pipe(busboy);
});

**Comment by mscdex** [comment]
`busboy` doesn't support `application/json` requests, only `multipart/form-data` and `application/x-www-form-urlencoded`.
