### ISSUE TITLE
Request closed and no one error event is emmited

### ISSUE THREAD

**Issue by Aeonrush** [mscdex/busboy#130]
I have a this sample
```javascript
'use strict';

const express = require('express'),
  Busboy = require('busboy'),
  bodyParser = require('body-parser'),
  app = new express()
  ;

app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.post('/upload', function (req, res, next) {

  const busboy = new Busboy({ headers: req.headers });

  busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {

    file.on('data', function(data) {
      console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
    });

    file.on('close', function() {
      console.log('File [' + fieldname + '] Closed');
    });

    file.on('error', function() {
      console.log('File [' + fieldname + '] Errored');
    });

    file.on('end', function() {
      console.log('File [' + fieldname + '] Finished');
    });

    const fStream = require('fs').createWriteStream(require('path').join(__dirname, 'tmp'));

    fStream.on('finish', function () {
      console.log('File stream for [' + fieldname + '] Finished');
    });

    fStream.on('end', function () {
      console.log('File stream for [' + fieldname + '] End');
    });

    fStream.on('close', function () {
      console.log('File stream for [' + fieldname + '] Closed');
    });

    fStream.on('error', function () {
      console.log('File stream for [' + fieldname + '] Errored');
    });

    file.pipe(fStream);

  });

  req.on('close', function() {
    console.log('Request closed');
    res.send('Closed');
  });

  busboy.on('error', function() {
    console.log('Busboy error');
    res.send('Finished');
  });

  busboy.on('close', function() {
    console.log('Busboy close');
    res.send('Finished');
  });

  busboy.on('finish', function() {
    console.log('Request finished');
    res.send('Finished');
  });

  req.pipe(busboy);

});

app.listen(3000);
```
Whn I tried do this `curl -F "image=@/tmp/test/big_file.jpg" --limit-rate 128k http://192.168.0.105:3000/upload` and after a few seconds press `Ctrl+C` I had in console something like this
```bash
File [image] got 16384 bytes
File [image] got 16384 bytes
File [image] got 16384 bytes
File [image] got 16384 bytes
File [image] got 16384 bytes
File [image] got 16384 bytes
Request closed
```
And that's all. No one error messages. 
How do I need to catch event where request is terminated from a client?

**Comment by ValYouW** [comment]
Hi, I ran into the same issue as well, did you find anything interesting?
My bigger concern is what errors should I expect and handle...

**Comment by Muqito** [comment]
Correct me if I am wrong, but the file is just a stream; and a stream stops piping when it receives null.

Anyway, I don't see the problem. If you received a file and the request is being closed (properly handled) you can just remove the output path of the WriteStream.

But if you want to track how much progress you have done and at what % you stopped the request; you can store expectedData from request headers like this:

`let expectedData = req.headers['content-length'];`

and in your file on data-event; you can track your fetched data by adding data.length to a fetchedData variable like this:

`fetchedData += data.length;`


If you want to know more about streams; I would suggest this handbook:

[Substack's stream handbook on github](https://github.com/substack/stream-handbook)

**Comment by ValYouW** [comment]
The point here as I see it is whether all resources are being released properly when the request is aborted.
ReadableStream has a "cleanup" method which is not being called in case the request is aborted, not sure I can fully track down the implications.
Listening to the `aborted` event on request, and then calling to its unpipe will trigger the cleanup method on Readable.
```js
req.on('aborted', function() {
    req.unpipe(busboy);
});
```
So if it's the user's responsibility to do that I think it is worth mentioning in the docs...

**Comment by mscdex** [comment]
@ValYouW I'm not sure it matters. The stream objects (both `req` and `busboy`) will just get GC'ed at some point anyway, so calling `req.unpipe(busboy)` on `'aborted'` doesn't really gain you much.

**Comment by Aeonrush** [comment]
Hi
Thanks everyone for help and clarify this situation. I think I found solution (this is example):
```javascript

// All like in a first time

app.post('/upload', (req, res, next) => {

  const busboy = new Busboy({ headers: req.headers })

  req.files = []
  busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
    const fStream = require('fs').createWriteStream(require('path').join(__dirname, 'tmp'))
    req.files = [...req.files, { fieldname, filename, file, fStream }]
    file.pipe(fStream)
  })

  req.on('aborted', () => {
    // Is it necessary?
    req.unpipe(busboy)
    console.log(req.files.filter(f => !f.fStream.closed).map(f => `[${f.fieldname}]: ${f.fStream.path}/${f.filename}`))
    res.send(req.files.filter(f => !f.fStream.closed).map(f => `[${f.fieldname}]: ${f.fStream.path}/${f.filename}`))
  })

  busboy.on('finish', () => next())

  req.pipe(busboy)

})

app.use((req, res, next) => {
  console.log('OK')
  console.log(req.files)
  res.send(req.files.map(f => f.fieldname))
})

app.use((err, req, res, next) => {
  console.error(err)
  res.status(500).send(err)
})

app.listen(3000, () => console.log('Started'))
```
When `req.on('aborted'` emitted, I know that request is not completed... In `req.files` I'm store files that started processing and that enables, for example, delete them
I'm agree with @Muqito `busboy` and `fileStream` shouldn't to emit error event
If I'm wrong please fix me, I'll be very appreciate for that.
