### ISSUE TITLE
receiving files from a Formdata upload not working

### ISSUE THREAD

**Issue by gocoffeecup** [mscdex/busboy#133]
I would like to upload a file using the html5 file API but the file event doesn't trigger, only the field event.

this is my clientside code:

```
upload.prototype.sendFile = function(fileData){
    var formData = new FormData()
    formData.append('file',fileData)
    var xhr = new XMLHttpRequest();
    xhr.open("post", "/file/upload", true);
    xhr.send(formData)
}

```

on the serverside I'm using the busboy example with express 4.0

any ideas?

**Comment by mscdex** [comment]
What is `fileData`? Where does it come from?

Are you saying the appended part named 'file' is arriving at the server via a 'field' event instead of a 'file' event?

**Comment by mscdex** [comment]
Also, did you verify what is being sent in your form by checking your browser's development tools?

**Comment by gocoffeecup** [comment]
mscdex, thank you for your fast response. 

yes it's arriving as 'field' event instead of a 'file' event

fileData is created by a fileReader 

```
input.addEventListener('change',function(e){
    var file = e.target.files[0]
    if (!file) return
    if (/^image\//i.test(file.type)){
      var reader = new FileReader()
      reader.onloadend = function(){
        self.sendFile(reader.result)
      }
      reader.onerror = function(){
        console.log('error')
      }
      reader.readAsDataURL(file)
    } else {
      alert('Not a valid image!');
    }
})
```

**Comment by gocoffeecup** [comment]
under equest headers I can see the following:

`content-type:multipart/form-data; boundary=----WebKitFormBoundaryBZbY1BAWMdBq9QBa`

and request payload starts with:

```
------WebKitFormBoundaryBZbY1BAWMdBq9QBa
Content-Disposition: form-data; name="file"

data:image/jpeg;base64,/9j/4AAQSkZ
```

**Comment by mscdex** [comment]
Ok, the issue is that you're using `reader.readAsDataURL()`. As [noted on MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL), `reader.result` will still be a data URL, but what you need is a `File` or `Blob` object instead.

I think you should be able to just pass `file` directly to `self.sendFile()` (and skip using a `FileReader` at all).

**Comment by gocoffeecup** [comment]
yep you're right, passing the file object directly works!
thank you!
