### ISSUE TITLE
Handling multipart/related requests

### ISSUE THREAD

**Issue by jeffreznik** [mscdex/busboy#137]
Does busboy handle multipart/related requests?  I'm trying to send an image from the client, through my node app server, to my image service (node app I wrote):

Client (Browser) --> App --> Image service

I don't want to wait to receive the entire file on the App before beginning to send it to the Image service, so I won't know the `Content-Length` at the time of the request, hence the need to send a multipart/related (chunked) request.  The request being sent from the App seems to have the correct headers, but busboy appears to be failing:

`Error: Unsupported content type: multipart/related; boundary=b7e55277-62b0-4d36-b989-866d326af1a9`

Here are the `console.log()`'d headers:

```
{ host: 'localhost:4000',
  'transfer-encoding': 'chunked',
  'content-type': 'multipart/related; boundary=b7e55277-62b0-4d36-b989-866d326af1a9',
  connection: 'close' }
```

Here is the request being sent from the client (using `request` library):

```javascript
request({
        method: 'PUT',
        preambleCRLF: true,
        postambleCRLF: true,
        url: 'http://localhost:4000',
        multipart: {
          chunked: true,
          data: [
            {
              'content-type': mimetype,
              body: fileStream
            }
          ]
        },
      }, (error, res, body) => {
        if (error) {
          return reject(error)
        }
        if (res.statusCode !== HttpStatus.OK) {
          return reject(res.statusMessage)
        }
        const urlArray = JSON.parse(chunks.join(''))
        resolve(urlArray[0])
      })
```

The `fileStream` being sent in the PUT request is a busboy stream received from its `file` event.

**Comment by mscdex** [comment]
`request` supports multipart/form-data also, why not use that instead? `busboy` only explicitly supports application/x-www-form-urlencoded and multipart/form-data.

**Comment by jeffreznik** [comment]
Reason is I want to stream the file through the app server to the image service without downloading it all first on the app server. As far as I know, this isn't possible with multipart/form-data as you need to know the content length prior to the request initiation. They only way to know the content length of the file is to download it all first though. 
-------- Original message --------From: Brian White <notifications@github.com> Date: 2017-01-07  9:48 PM  (GMT-06:00) To: mscdex/busboy <busboy@noreply.github.com> Cc: Jeff Reznik <reznik.jeff@gmail.com>, Author <author@noreply.github.com> Subject: Re: [mscdex/busboy] Handling multipart/related requests (#137) 
request supports multipart/form-data also, why not use that instead? busboy only explicitly supports application/x-www-form-urlencoded and multipart/form-data.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mscdex/busboy","title":"mscdex/busboy","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mscdex/busboy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mscdex in #137: `request` supports multipart/form-data also, why not use that instead? `busboy` only explicitly supports application/x-www-form-urlencoded and multipart/form-data."}],"action":{"name":"View Issue","url":"https://github.com/mscdex/busboy/issues/137#issuecomment-271127770"}}}

**Comment by mscdex** [comment]
You shouldn't need to know the content length beforehand for multipart/form-data. You should be able to just set `formData: { myFile: fs.createReadStream(...) }` or whatever stream you have. If that doesn't work, then there's a bug in either the `request` or `form-data` modules.

**Comment by jeffreznik** [comment]
Here is my attempt at sending it with multipart/form-data (App server code):

```javascript
class ImageServiceAdapter {
  // returns Promise which resolves to the url of the uploaded image
  static put(fileStream, filename, mimetype, options) {
    if (!filename) {
      throw 'No filename given in options to ImageServiceAdapter.put()'
    }
    options = Object.assign(defaultOptions, options)
    return new Promise((resolve, reject) => {

      const formData = {
        filename: filename,
        maxWidthHeightPixels: options.maxWidthHeightPixels,
        file: {
          value: fileStream, // this is a busboy file ReadableStream from the 'file' event, sent from the browser
          options: {
            filename: filename,
            contentType: mimetype,
          }
        }
      }

      request.post({url: 'http://localhost:4000', formData: formData}, (error, res, body) => {
        if (error) {
          return reject(error)
        }
        if (res.statusCode !== HttpStatus.OK) {
          return reject(res.statusMessage)
        }
        const urlArray = JSON.parse(chunks.join(''))
        resolve(urlArray[0])
      })
    })
  }
}
```

And on the Image service, here are the headers received:

```
{ host: 'localhost:4000',
  'content-type': 'multipart/form-data; boundary=--------------------------114791971148033485630697',
  'content-length': '458',
  connection: 'close' }
```

And busboy gives this error:

```
Error: Unexpected end of multipart data
    at /Users/jreznik/Sites/image-service/node_modules/dicer/lib/Dicer.js:62:28
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I noticed that `content-length` is in the header list.  As you can see I did not specify this in the `request` options, so it is inferring it from the busboy file stream given to it somehow.  Is this perhaps my issue?  Can I not put a busboy file stream directly into `request` options like you can with `fs.createReadStream(...)`?

**Comment by jeffreznik** [comment]
In my tests, I replaced the `busboy` file stream with a `fs.createReadStream(...)` file stream in the `request` options and the latter worked.  The Image service receives the `content-length` header with a correct value for the image I send.  I'm thinking that `request` or `form-data` is having trouble using the `busboy` file stream and I don't know why.  What is so different between these two streams?  Sure one is coming from the network and the other the file system but why should that matter?

**Comment by jeffreznik** [comment]
I found this related issue: #132 where I see you said:

> `request()` uses `form-data` which only allows certain kinds of streams, specifically those that it can determine the total length of up front since it always adds a Content-Length header in the request (although node supports sending chunked requests).
> 
> You would probably need to submit a issue/PR to `form-data` to allow any streams, and to use chunked encoding if any of the streams' lengths cannot be pre-determined.

So instead of using `form-data` (or `request`'s `multipart/form-data` functionality which uses `form-data` under the hood), I am trying to use `request`'s `multipart/related` functionality to send a chunked request.  This is where `busboy` has an issue though as it does not seem to support `multipart/related`/chunked requests.

**Comment by mscdex** [comment]
Your best bet is probably to submit an issue on the [`form-data` issue tracker](https://github.com/form-data/form-data/issues). It appears that they have thought about arbitrary stream support at least a [couple](https://github.com/form-data/form-data/pull/103) of [times](https://github.com/form-data/form-data/pull/70).

**Comment by mscdex** [comment]
`busboy` has no issue with chunked requests, however as I previously mentioned it only supports application/x-www-form-urlencoded and multipart/form-data, which are the two main types of form submissions.

**Comment by jeffreznik** [comment]
Thanks, is it possible to send a multipart/form-data chunked request?  I have been working under the understanding that chunked necessitated the use of multipart/related, but that could be wrong.

The web server I am sending to is a node server (I'm developing it too), and I am using busboy on that side as well to receive the request.

**Comment by mscdex** [comment]
The `Transfer-Encoding`/`Content-Length` and `Content-Type` HTTP headers are not related in any way. You could send a `Content-Type: multipart/form-data; ...` request with a `Content-Length` header set *or* with `Transfer-Encoding: chunked` set. Similarly, you could send a `Content-Type: text/plain` request with a `Content-Length` header set or with `Transfer-Encoding: chunked` set.

**Comment by jeffreznik** [comment]
Thank you, that has really helped me determine the best approach to getting this to work.  This is definitely NOT a `busboy` issue, and I was just able to get the transfer to work using the [PR you linked above](https://github.com/form-data/form-data/pull/103).  Unfortunately `Transfer-Encoding: chunked` isn't into `form-data`'s main codebase yet, but I can work around that for the time being.  Thanks again for your help and replies, and for this excellent module.

**Comment by liutian1937** [comment]
mark

**Comment by thanh-nt-niteco** [comment]
I got the same problem and this solution worked
