### ISSUE TITLE
Forms that violate limitations returns a 404 instead of throwing an error

### ISSUE THREAD

**Issue by kmccmk9** [mscdex/busboy#138]
Hello,

First I want to thank you for a very well performing package!

I did come into one problem that I believe stems from within busboy itself. If I set limitations on the form through the Busboy options, and a form doesn't meet this criteria, the express route stops execution and returns a 404 Not Found to the client. This is definitely not ideal since, first it should probably be a 400 not 404. But, also it would be great if this through an error exception that could be captured in some way so the developer could handle them in their own way.

Please let me know if you need more information about how to reproduce. 

Thank you,
Kyle C.

**Comment by mscdex** [comment]
This module has nothing to do with Express. It doesn't even have access to any request or response objects because it's just streams. It sounds like you're describing some other the behavior of some third party module that uses busboy instead, so you might want to submit an issue on that module's issue tracker instead.

**Comment by kmccmk9** [comment]
Hi @mscdex, thank you for the quick reply. I have confirmed that my package.json does refer to busboy and not a third party tool. If it doesn't touch express (which makes sense), what is the best way to catch when a form does not pass the validation options? I see from the documentation that there are the three emits...but it doesn't say much about what those contain if anything about the information as to why validation may have failed?


```
partsLimit() - Emitted when specified parts limit has been reached. No more 'file' or 'field' events will be emitted.

filesLimit() - Emitted when specified files limit has been reached. No more 'file' events will be emitted.

fieldsLimit() - Emitted when specified fields limit has been reached. No more 'field' events will be emitted.
```

**Comment by mscdex** [comment]
busboy does not validate field content or anything. The only explicit "validations" are the various limits you can impose. The events you're referring to are emitted when the various `limits` you pass to the busboy constructor are reached. In addition, file streams emitted by busboy will emit a `'limit'` event and have a `.truncated` set to `true` for a file size limit.

**Comment by kmccmk9** [comment]
Right, that is what I meant by validations, apologies. Thank you for the additional information about the stream emitters. Ok finally clarification, if I'm relying mostly on the limits and the three emits associated, is there a good way to get context? From the documentation, it doesn't look like there is any variables passed to the emitter as to provide a context.

**Comment by mscdex** [comment]
Well, like any `EventEmitter`, `this` will refer to the busboy instance. If you need any more context than that, you will need to use proper scoping with your event handlers.

**Comment by kmccmk9** [comment]
I understand. Thank you very much for your help.
