### ISSUE TITLE
Boundary containing forward slash character returns empty body

### ISSUE THREAD

**Issue by markusekblad** [mscdex/busboy#139]
I'm using multer so not sure if this belongs here or there but when submitting an XMLHttpRequest from ReactNative iOS the multipart boundary sometimes contains a forward slash '/' character and those requests all produce an empty body even tho the '/' character is allowed according to RFC 2046. https://www.ietf.org/rfc/rfc2046.txt

'content-type': 'multipart/form-data; boundary=-XrQHxml_qhW/dc2hip09LUML-QC3Wo.9OiqWz8G1NGvI3L1RP1GrN_ljEwkwWRpIzrv8M'

Issue reported at multer as well: https://github.com/expressjs/multer/issues/462

**Comment by charmander** [comment]
Can you record a failed request and reproduce an issue with this?

```javascript
'use strict';

const Busboy = require('busboy');

const readToEnd = (stream, callback) => {
	const parts = [];

	stream.on('data', part => {
		parts.push(part);
	});

	stream.on('end', () => {
		callback(Buffer.concat(parts));
	});
};

const boundary = '-XrQHxml_qhW/dc2hip09LUML-QC3Wo.9OiqWz8G1NGvI3L1RP1GrN_ljEwkwWRpIzrv8M';

const busboy = new Busboy({
	headers: {
		'content-type': 'multipart/form-data; boundary=' + boundary,
	},
});

busboy.on('field', (name, value) => {
	console.log('field %j %j', name, value);
});

busboy.on('file', (name, file) => {
	readToEnd(file, data => {
		console.log('file %j %j', name, data.toString('utf8'));
	});
});

busboy.on('finish', () => {
	console.log('finish');
});

busboy.end(
	'--' + boundary + '\r\n' +
	'Content-Disposition: form-data; name="test"\r\n' +
	'\r\nA field\r\n' +
	'--' + boundary + '\r\n' +
	'Content-Disposition: form-data; name="test-file"; filename="test-file"\r\n' +
	'Content-Type: text/plain\r\n' +
	'\r\nA file\r\n' +
	'--' + boundary + '--\r\n'
);
```

**Comment by markusekblad** [comment]
Thank you, based on that I logged the following request and I can conclude that busboy does not seem to be the problem here.

{ 
  'content-type': 'multipart/form-data; boundary=XhUHflPj.HUwxcHTEUuBjBcx.i-CQDg2iREEuOs1d/j9WqXSbwFM3UNrb-U_QSeE3R5DR1',
  ...
 }
field "external_url" "Ufyivigo"
field "school_class" "589091e3edf6f20140c"
finish


And your code unmodifed produces
field "test" "A field"
file "test-file" "A file"
finish

**Comment by charmander** [comment]
Yep, this can be closed: https://github.com/expressjs/multer/issues/462#issuecomment-281423146
