### ISSUE TITLE
Suggestion: Never throw constructor errors, only emit error event.

### ISSUE THREAD

**Issue by simontabor** [mscdex/busboy#140]
I know there is now updated documentation on error handling, but it still feels much more natural for all errors to be emitted rather than thrown. It's significantly easier to handle too.

The README examples don't have `new Busboy` in a try catch which means that any request could easily crash the server.

## Current Error Handling
```js
var busboy;
try {
  busboy = new Busboy({ headers: req.headers })
} catch (e) {
  return next(e);
}

busboy.on('error', next);
// ...
req.pipe(busboy);
```

## Suggested Error Handling
```js
var busboy = new Busboy({ headers: req.headers })
busboy.on('error', next);
// ...
req.pipe(busboy);
```

Of course the constructor errors would have to be triggered on a `process.nextTick`, or only triggered once the request has been piped.

**Comment by mscdex** [comment]
IMHO throwing immediately is better for such cases because the errors are related to bad input. Emitting `'error'` events are better for asynchronous errors, like if a malformed multipart body was detected.

**Comment by simontabor** [comment]
Generally, I agree. If a developer constructs Busboy with invalid options then it should throw. However, `req.headers` isn't controlled by the developer, so it doesn't feel right to throw due to their properties.

Because of that, maybe it'd be nice to have the option of using Busboy like this...
```js
var busboy = new Busboy({ limits: { files: 1 } }); // throws if these are invalid
busboy.on('error', next);
// ...
busboy.start(req); // .start calls parseHeaders (which emits errors) and req.pipe(busboy)
```

**Comment by mscdex** [comment]
I'm not sure what you mean by '`req.headers` isn't controlled by the developer.' Of course it is, it's being passed to the constructor. If you want to *avoid* the exception, check the Content-Type before passing the headers object to `busboy`.

**Comment by simontabor** [comment]
By "not controlled" I mean not explicitly written, and highly unlikely to be parsed/checked before being passed to Busboy.

With this suggestion, I'm trying to reduce the amount of required code and potential for confusion when using Busboy. Feel free to disagree, but having to wrap the constructor in a try/catch (or pre-checking Content-Type AND the multipart boundary) feels wrong/unnecessary.

**Comment by charmander** [comment]
If it bothers you, consider:

```javascript
function busboy(options) {
    try {
        return new Busboy(options);
    } catch (error) {
        var errorEmitter = new stream.PassThrough();
        process.nextTick(function () {
            errorEmitter.emit('error', error);
        });
        return errorEmitter;
    }
}
```
