### ISSUE TITLE
when busboy.on('file',...)....

### ISSUE THREAD

**Issue by runhwguo** [mscdex/busboy#145]
(fieldname, file, filename, encoding, mimetype)
when filename is "", why this listener is fired!?

**Comment by mscdex** [comment]
`filename` is just the original filename. It could be technically any value though, although browsers typically just strip the directory information from the original path and use the resulting filename as the value.

Does the stream contents match that of the file that was uploaded?

**Comment by ldp-n** [comment]
If the client sends an empty form the request contains an empty file.
```
------WebKitFormBoundaryBRk1U4CARSbHRCKV
Content-Disposition: form-data; name="files"; filename=""
Content-Type: application/octet-stream

------WebKitFormBoundaryBRk1U4CARSbHRCKV
Content-Disposition: form-data; name="submit"

upload
------WebKitFormBoundaryBRk1U4CARSbHRCKV--
```
Is there an easy way to check file on empty before upload?

**Comment by mscdex** [comment]
Yes, you can check the file size before upload by accessing the `.size` property of the [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) instance. [MDN has examples of how to do just that.](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications)

**Comment by ldp-n** [comment]
I mean before receive the file stream on server side.

**Comment by mscdex** [comment]
@ldp-n That's what I'm talking about also. Read up on the links I posted.

**Comment by ldp-n** [comment]
I'm probably missing something, but the `File` API it's part of the client side (I do not have access to it). Everything that I have it's POST request on my server and I can't receive some extra data from client.

**Comment by mscdex** [comment]
@ldp-n If you don't have access to the client side then there is no way to tell if a file is empty before the server receives it. The server does not know what a part's size is in advance because that's kind of the point of multipart, you use boundaries to delineate parts, there is per-part `Content-Length` (at least for multipart/form-data).

One thing you *might* be able to do is try to read 0 bytes from the stream first and see if you get the appropriate `'end'` event or not (perhaps on the next tick), but I'm not sure 100% offhand if that'd work or not.

**Comment by jimmywarting** [comment]
stubble on this recently, i don't use any frontend javascript methods. ajax, File or FormData just plain old html form

i also notice when i left the file input empty it still sends a empty field like ntlvs mention also
```
------WebKitFormBoundaryBRk1U4CARSbHRCKV
Content-Disposition: form-data; name="files"; filename=""
Content-Type: application/octet-stream

```
why do browser send this at all?

**Comment by mscdex** [comment]
@jimmywarting I believe browsers by default send all form elements, empty or not, so this is not specific to file input fields.

**Comment by jimmywarting** [comment]
Yea, but why? What's the point of that?

**Comment by mscdex** [comment]
It's part of the HTML specification.

Specifically for file form fields [it says](https://www.w3.org/TR/html52/sec-forms.html#constructing-the-form-data-set) (emphasis mine):

> Otherwise, if the field element is an input element whose type attribute is in the File Upload state, then for each file selected in the input element, append an entry to the form data set with the name as the name, the file (consisting of the name, the type, and the body) as the value, and type as the type. **If there are no selected files, then append an entry to the form data set with the name as the name, the empty string as the value, and application/octet-stream as the type.**
