### ISSUE TITLE
Validating fields before streaming file

### ISSUE THREAD

**Issue by orenklein** [mscdex/busboy#146]
In a scenario where I don't have any control on the formdata fields order -
My server is streaming to another server/service (such as blob storage) a file that is being uploaded (using pipe), Is it possible to add validation rules/logic (DB integrated for example) to specific fields of formdata?

Validating fields only after a file has been uploaded is not an ideal approach.

As far as I understand "reformed" package is following fields order.

(#55 - I read the referenced issue, but I am not sure if there's any other solution for the above mentioned scenario)

**Comment by mscdex** [comment]
The order of the parts in the request are always followed in order, there is no other way (as long as you're not buffering of course). If you depend on certain fields arriving after a file part, then you're out of luck if you are not in control of the requests and you do not want to buffer or save the file to disk first.

As far as validation goes, that's outside the scope of this module. `reformed` does allow this, as do other modules built on top of `busboy`.

**Comment by orenklein** [comment]
Thank you for your quick response! 
In my case, enforcing fields order on the server as a workaround is good enough - 
Reject request if it does not meet the expected order (or if the validations have not been executed yet).
