### ISSUE TITLE
Dicer should have `error` handler attached

### ISSUE THREAD

**Issue by fogine** [mscdex/busboy#152]
[HERE](https://github.com/mscdex/busboy/blob/master/lib/types/multipart.js#L98) - new instance of Dicer stream is created but no `error` event handler is attached thus if an Error occurs, node throws it synchronously and handles it as `uncaughException`.

In my case, I got the following err as I explicitly called `busboy.end()`:
> uncaughtException: Part terminated early due to unexpected end of multipart data 

I'm aware of the #130 , specifically:
> @ValYouW I'm not sure it matters. The stream objects (both req and busboy) will just get GC'ed at some point anyway, so calling req.unpipe(busboy) on 'aborted' doesn't really gain you much since nothing else will happen with req after it's aborted.

However, I still think the case should be handled somehow and should not be let to get out of hand.
Another "special" event on a busboy instance makes most sense to me.

Thank  you for your contributions to OS.

**Comment by mscdex** [comment]
I'm not sure what you mean, there are error handlers attached to both [the `Dicer` instance](https://github.com/mscdex/busboy/blob/203b42f5122ed5bfe38a68874a511c0b35bae33c/lib/types/multipart.js#L280-L281) *and* [the part streams](https://github.com/mscdex/busboy/blob/203b42f5122ed5bfe38a68874a511c0b35bae33c/lib/types/multipart.js#L276-L279) it emits.

**Comment by fogine** [comment]
@mscdex I see, I'm sorry. I actually missed that in the source code. My bad.
Thanks.
