### ISSUE TITLE
Is a way to check the file size first then decide if the file is saving into the disk?

### ISSUE THREAD

**Issue by leoyli** [mscdex/busboy#154]
Hi,

I was assuming `file.on(data, function () {...})` can handle this, for example:

```
var busParams = {headers: req.headers, limits : {fileSize:10000, files:1}};
var busboy = new Busboy(busParams);
var filePath = path.join(path.normalize(__dirname + '/..'), 'public', 'images');

busboy.on('file', function (fieldname, file, filename, encoding, mimetype) {
        file.on('data', function () {
            if (data.size > busParams.limits.fileSize) {
                return console.log('FILE TOO BIG');
            } else {
                var saveTo = filePath + '/' + Date.now() + filename;
                var fStream = fs.createWriteStream(saveTo);
                file.pipe(fStream);
                file.on('end', function () {
                    console.log('FILE UPLOADED')
                });
            }
        });
});
```

However, the uploaded file is empty.  And I just realize that if `file.pipe(fStream)` is running inside of any event listener, then it gives an empty file which is reasonable but making the `'data'` event not so useful.  And the file have to save into the server memory first then being drained (by `fs.unlink(saveTo)` inside `file.on('limit', function () {})`), which is not so efficient.

So I just wonder if there is a way to check the file size first then decide if the file is saving into the disk?

**Comment by mscdex** [comment]
The nature of multipart (files/fields separated by a delimiter) means you do not know the file/field size up front.

Why not just start writing to disk immediately and if the file size limit is exceeded (`'limit'` event will be emitted on the `file` stream), close the `fs.WriteStream` and delete what was written to disk?

**Comment by leoyli** [comment]
Thank you for your responses.  I guess I got your point.

Originally, I thought the way that 'data' event does is it parse the data in client's browser, that's how the `data.length` gives you the size of the file.  And up to that moment the server actually have not yet received the full file from the client (the size of data is actually told by our clients, just like how we get MEMEtype).  But seems I was wrong?!

The reason why I see it is not so efficient is because, let's say I set the size limits to 1GB; however, a client somehow send me 1.01GB of data, which will be drained once it exceed the limit, but it ate my server's memory.  And if the uploading seed from the client is slow, it just not good for the user's experiences also.

**Comment by mscdex** [comment]
Never make any assumptions about `'data'` events in general in node (unless of course the stream is an object stream). The size of the chunk passed to `'data'` event handlers could be 1 byte, or 1 kilobyte, or the entire file depending on its size. It's a stream.

**Comment by mscdex** [comment]
> The reason why I see it is not so efficient is because, let's say I set the size limits to 1GB; however, a client somehow send me 1.01GB of data, which will be drained once it exceed the limit, but it ate my server's memory. And if the uploading seed from the client is slow, it just not good for the user's experiences also.

Ultimately there is no way around this, no matter how you accept files from a user. This is not an issue limited to multipart forms. For example, if someone sends a PUT command with `Transfer-Encoding: chunked`, you won't know you've reached the end until the client tells you. Meanwhile you have to do *something* with the data because you don't know when the request stream will end. So you either Buffer it in memory (not a good idea generally) or you save it to disk somewhere or stream it to some other network resource (e.g. S3). No matter what though, resources *somewhere* will be used at least temporarily until the request stream has finished.

**Comment by leoyli** [comment]
Thank you very much for those details!  I learn a lot from it!
