### ISSUE TITLE
The fieldsLimit event doesn't happen when parsing application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by polomoshnov** [mscdex/busboy#156]
But it's emitted properly when a request is sent with Content-Type multipart/form-data. Shouldn't the fields limit also work with the urlencoded requests?

To reproduce this issue set the fields limit to 1 but send your urlencoded request with 2 or more fields. One would expect to see the fieldsLimit event get emitted but it doesn't happen. My Busboy version is 0.2.14 and Node is 8.6.0.

**Comment by mscdex** [comment]
Do you have a reproducible test? Currently we already have a test for `fields: 1` for urlencoded requests...
