### ISSUE TITLE
Busboy 'field' never triggered

### ISSUE THREAD

**Issue by 616353553** [mscdex/busboy#158]
Hi, I am having this problem that the `field` or `file` functions never get triggered, and here is my code:

    const Busboy = require('busboy');

    exports.test = functions.https.onRequest((req, res) => {
        console.log("start");
        console.log(req.rawBody.toString());
        if (req.method === 'POST') {
            var busboy = new Busboy({ headers: req.headers});
            busboy.on('field', (fieldname, val, fieldnameTruncated, valTruncated, encoding, mimetype) => {
                console.log('field');
            });
            busboy.on('finish', function() {
                console.log('finish');
                res.json({
                    data: null,
                    error: null
                });
            });
            req.pipe(busboy);
        } else {
            console.log('else...');
        }
    });

And the output of my code is:

    Function execution started
    start
    --Boundary-43F22E06-B123-4575-A7A3-6C144C213D09
    Content-Disposition: form-data; name="json"

    {"name":"Alex","age":"24","friends":["John","Tom","Sam"]}
    --Boundary-43F22E06-B123-4575-A7A3-6C144C213D09--
    finish
    Function execution took 517 ms, finished with status code: 200

As you can see, the `file` function was never triggered, how can I fix this?
Also, I have tried POSTMAN to test my function, and the output was the same except the boundary.

**Comment by mscdex** [comment]
If you've already read the request data (as evidenced by the existence of a `req.rawBody`), then there is nothing for `busboy` to parse. You will need to either disable request body buffering *or* you will need to manually feed the buffered data to the `Busboy` instance via `busboy.end(req.rawBody)` instead of `req.pipe(busboy)`.

**Comment by 616353553** [comment]
Just updated my code like you suggested, and it still not working. Any idea? Here is my code:

    exports.test = functions.https.onRequest((req, res) => {
        console.log("start");
        console.log(req.rawBody.toString());
        if (req.method === 'POST') {
            var busboy = new Busboy({headers: req.headers});
            busboy.on('field', (fieldname, val, fieldnameTruncated, valTruncated, encoding, mimetype) => {
                console.log('field');
            });
            busboy.on('finish', () => {
                console.log('finish');
                res.json({
                    data: null,
                    error: null
                });
            });
            busboy.end(req.rawbody);
        } else {
            console.log('else...');
        }
    });
