### ISSUE TITLE
Get an array of data (i.e. checkboxes with the same name)

### ISSUE THREAD

**Issue by rngnrs** [mscdex/busboy#159]
Well, I have a GET/POST query like this: 
`post[]=74&post[]=75&post[]=76`
How can I get an array from such query? Can I do it "_natively_" in a proper way (without writing buggy code on its own)?

Related link: https://stackoverflow.com/questions/33245147/get-form-array-data-from-busboy

**Comment by mscdex** [comment]
You just check the field name and then append the value to an appropriate array.

**Comment by rngnrs** [comment]
Okay, I wrote this code.
```js
    let fields = {};
    busboy.on('field', (fieldname, val) => {
      let matches = fieldname.match(/(.+)\[(.*)]$/);
      if (!matches) {
        return fields[fieldname] = val;
      }
      if (!fields[matches[1]]) {
        fields[matches[1]] = [];
      }
      if (!matches[2]) {
        return fields[matches[1]].push(val);
      }
      if (!fields[matches[1]][matches[2]]) {
        fields[matches[1]][matches[2]] = [];
      }
      fields[matches[1]][matches[2]].push(val);
    });
```
