### ISSUE TITLE
Issue parsing binary content with standard node form-data (test case inside)

### ISSUE THREAD

**Issue by leefinaeo** [mscdex/busboy#160]
Hi Mscdex,

Fantastic project, tons of downloads, really killer man. I am having an issue creating FormData with a PNG file programmatically, and having busboy parse it. I am building some cool tools for AWS lambda, so this is outside of express land. 

This reads in `input.png` and outputs `output.png`. They are the identical size but the bytes are quite different. I suspect something to do with ASCII encoding, any chance you know whats going on? 

The first block creates FormData then streams it to a string, the second block streams the string back into busboy.

```
'use strict';

const FormData = require('form-data');
const Busboy = require('busboy');
const Readable = require('stream').Readable;
const Writable = require('stream').Writable;
const Q = require('q');
const fs = require('fs');

Q.try(() => {
  const deferred = Q.defer();
  const ws = new Writable();

  var form = new FormData();
  form.append('test', fs.createReadStream(`./input.png`));

  let formDataStr = '';
  ws._write = (data, encoding, next) => {
    formDataStr += data.toString('ascii');
    next();
  };

  ws.on('finish', () => {
    deferred.resolve([formDataStr, form.getBoundary()]);
  });

  form.pipe(ws);
  return deferred.promise;
}).spread((formDataStr, boundary) => {
  var deferred = Q.defer();
  var busboy = new Busboy({
    headers: {
      'content-type': `multipart/form-data; boundary=${boundary}`
    }
  });

  busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
    file.pipe(require('fs').createWriteStream('output.png'));
  });

  busboy.on('finish', function() {
    deferred.resolve();
  });

  var s = new Readable();
  s.push(formDataStr);
  s.push(null);

  s.pipe(busboy);

  return deferred.promise;
}).catch(e => {
  console.error('[ERROR] ', e);
});

```

**Comment by leefinaeo** [comment]
I have not been this confused for some time, I know its not directly related to busboy perhaps, but I would donate for some help here @mscdex  :)

<img width="1506" alt="screen shot 2018-01-26 at 11 15 03 am" src="https://user-images.githubusercontent.com/29896536/35451097-13767a52-0290-11e8-9ab3-c2fbab53d06f.png">

**Comment by leefinaeo** [comment]
Its obvious that its intermediary string, as this works great:

```
'use strict';

const FormData = require('form-data');
const Busboy = require('busboy');
const Readable = require('stream').Readable;
const Writable = require('stream').Writable;
const Q = require('q');
const fs = require('fs');

Q.try(() => {
  const deferred = Q.defer();

  var form = new FormData();
  form.append('test', fs.createReadStream(`./input.png`));

  var busboy = new Busboy({
    headers: {
      'content-type': `multipart/form-data; boundary=${form.getBoundary()}`
    }
  });

  busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
    file.pipe(require('fs').createWriteStream('output.png'));
  });

  busboy.on('finish', function() {
    deferred.resolve();
  });

  form.pipe(busboy);

  return deferred.promise;
}).catch(e => {
  console.error('[ERROR] ', e);
});
```

**Comment by mscdex** [comment]
You're converting binary image data (8 bits) to ASCII (7 bits), so there is most likely going to be data corruption. multipart/form-data is not always ASCII, it could be any kind of encoding depending on the contents of each part.

**Comment by leefinaeo** [comment]
@mscdex It does not work if I use 'binary' encoding either, is there any tips you might have, how would a request library create a proper body from multipart?

**Comment by leefinaeo** [comment]
@mscdex I would really appreciate any help, seriously.

**Comment by leefinaeo** [comment]
@mscdex You are right, I was only using `ascii` as it got me to the exact byte count as the original. Once switched to binary and then using Buffer.from(string, 'binary') in the second block, everything works as expected. Thanks for the great library bro!
