### ISSUE TITLE
Error events

### ISSUE THREAD

**Issue by rightaway** [mscdex/busboy#161]
In the documentation, there are 3 types of error events, `partsLimit`, `filesLimit`, `fieldsLimit`. However you can set many types of limits on the object:

```
fieldNameSize
fieldSize
fields
fileSize
files
parts
headerPairs
```

How can failures for those other limits be detected if they don't have error events of their own?

**Comment by charmander** [comment]
Some information is in the documentation for the other events. The `'field'` event is emitted with `fieldnameTruncated` and `valueTruncated`; the `'file'` event states:

> If a configured file size limit was reached, `stream` will both have a boolean property `truncated` (best checked at the end of the stream) and emit a 'limit' event to notify you when this happens.

The `headerPairs` limit behaves the same way as it does in Node: it ignores the rest of the headers.

The `fieldNameSize` limit doesn’t appear to be enforced on multipart requests. https://github.com/mscdex/busboy/blob/8f6752507491c0c9b01198fca626a9fe6f578092/lib/types/multipart.js#L5
