### ISSUE TITLE
Restify body parser plugin conflict

### ISSUE THREAD

**Issue by lanzosuarez** [mscdex/busboy#162]
Do you know a work around with restify body parser plugin middleware.
 It seems that form data is being modifed when the request is passing to the bodyParser middleware and busboy dont get any file data. but when i remove the middleware, busboy works

**Comment by mscdex** [comment]
If a middleware is reading the request data, then there is no data for busboy to read and nothing this module can do about that.

You will need to configure your body parser middleware to not handle `multipart/form-data` and/or `application/x-www-form-urlencoded` requests.
