### ISSUE TITLE
FieldLimit

### ISSUE THREAD

**Issue by andhure** [mscdex/busboy#169]
I am trying to listen to this event. But looks like it is never emitted. 

busboy.on('fieldsLimit',function(){
        console.log("Field Limit reached");
    });

Complete code from the example given:

 var busboy = new Busboy({ headers: req.headers });
    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      console.log('File [' + fieldname + ']: filename: ' + filename + ', encoding: ' + encoding + ', mimetype: ' + mimetype);
      file.on('data', function(data) {
        console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
      });
      file.on('end', function() {
        console.log('File [' + fieldname + '] Finished');
      });
    });
    busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated, encoding, mimetype) {
      console.log('Field [' + fieldname + ']: value: ' + inspect(val));
    });
busboy.on('fieldsLimit',function(){
        console.log("Field Limit reached");
    });
    busboy.on('finish', function() {
      console.log('Done parsing form!');
      res.writeHead(303, { Connection: 'close', Location: '/' });
      res.end();
    });
    req.pipe(busboy);

**Comment by mscdex** [comment]
That is correct, you will need to explicitly set limits in the config object passed to the `Busboy` constructor.
