### ISSUE TITLE
Using "Save all incoming files to disk" example (may) yield empty file

### ISSUE THREAD

**Issue by chrismessiah** [mscdex/busboy#175]
I'm using the _Save all incoming files to disk_ example and have noticed that for some files being uploaded the written file is empty (size of 0 bytes). I have tried upload different files and have noticed it for small `.md` and `.docx` files where the largest file is 8 Kb. Yet somehow it works fine when I try to upload larger files like images. Am I missing something?

The code is almost exactly the same as in the example. I have commented the changes

```javascript
var http = require('http'),
    path = require('path'),
    os = require('os'),
    fs = require('fs');

var Busboy = require('busboy');

var saveTo // change: make path to file global

http.createServer(function(req, res) {
  if (req.method === 'POST') {
    var busboy = new Busboy({ headers: req.headers });
    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      saveTo = path.join(os.tmpdir(), path.basename(fieldname));
      file.pipe(fs.createWriteStream(saveTo));
    });
    busboy.on('finish', function() {
      console.log('Size:', fs.statSync(saveTo).size) // change: Log file size
      res.writeHead(200, { 'Connection': 'close' });
      res.end("That's all folks!");
    });
    return req.pipe(busboy);
  }
  res.writeHead(404);
  res.end();
}).listen(8000, function() {
  console.log('Listening for requests');
});
```

**Comment by mscdex** [comment]
When you say the files are empty, are you verifying the actual size on disk or only judging by the result of the `fs.statSync()` call? Calling `fs.statSync()` in the `'finish'` event handler is subject to a race condition as `'finish'` simply means that all of the request data has all been processed. However, if you are writing file data to a stream, it's possible that not all data has actually been written/flushed to disk quite yet.

**Comment by chrismessiah** [comment]
Aha I see. This seems to be correct. If a `'finish'` event handler is created for the write stream it is indeed called when the data is written to the file as the following example shows.

```javascript
    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      var saveTo = path.join(os.tmpdir(), path.basename(fieldname));
      var writeStream = fs.createWriteStream(saveTo)
      writeStream.on('finish', function() { // change: add finish event handler on writeStream
        console.log('Size:', fs.statSync(saveTo).size)
      });

      file.pipe(writeStream);

    });
```

Should this be reflected by the example? Otherwise this comment could be used for future reference. 

Great thanks!
