### ISSUE TITLE
Performing DB operation on field before entering the file portion.

### ISSUE THREAD

**Issue by MjJuneja** [mscdex/busboy#176]
I have been trying hard with req.pause() and everything, I have to process the ID of image or person posting image in database and then if that matches I have to perform action on that specific image or file.
Please help me around this.

**Comment by MjJuneja** [comment]
@mscdex  in that case operation that needed to be performed once will happen multiple time in case of multiple images.

**Comment by mscdex** [comment]
I don't understand. Are you trying to perform multiple checks for multiple images from your form? Is the data used to perform these checks not all together (e.g. id1, id2, id3, file1, file2, file3) or are they separate (e.g. id1, file1, id2, file2, id3, file3)? If they are the latter, perhaps consider reordering your form submission to use the former layout so you can process them all up front.

**Comment by MjJuneja** [comment]
Basically I have a product schema in which id of product along with data is saved. So when images are posted for that particular product, imageId is provided, So while updating that image I need to first check if that product exist and if so its image with that id exist or not.

**Comment by mscdex** [comment]
Ok, I don't see what is wrong with `req.pause()` and/or not reading from the file before your database lookup finishes.

**Comment by MjJuneja** [comment]
@mscdex  I have kept console.logs on start of field reading, field end, file start and file end. Even after adding req.pause(), before the db call ends, file gets processed before hand, Problem is from the file section, I save that image schedule it for compression and after that schedule it for AWS uploading


busboy.on('field', function (fieldname, val, fieldnameTruncated, valTruncated) {
req.pause();
 data.productId = inspect(val);
dbOperation
   //callbacks req.resume()

})

busboy.on(file) 
//file operation


This is what am doing. Please tell if problem can be rectified anyway

**Comment by christykusuma** [comment]
I'm running into this issue too now, trying to get the product id from the DB operation and using it to name the image file. Tried putting a flag in for the 'file' event handler and it skips it entirely and finishes. Is there an example for this?
