### ISSUE TITLE
How to serve multipart/related contents?

### ISSUE THREAD

**Issue by zhouhao27** [mscdex/busboy#177]
I'd like to know if there are any example on how to serve multipart/related contents such as images etc.

**Comment by mscdex** [comment]
That's beyond the scope of this project, which is for *parsing* multipart/form-data and application/x-www-form-urlencoded.

**Comment by TLPcoder** [comment]
Would you consider a PR for an additional type "Related || MultipartRelated". If so multipart/related works based on relationships between a parent and child linked using a contentId/cid (will probably need to provide an option for a callback to get cid as there is no standard  which is always followed it can be in json, xml, etc.). Usually the parent has meta data explaining what the file/image is.

My idea would be to created a new event called relation once the parent and child connection is created. The event would provide a parent and child node { parent, child }. In those nodes would provide meta data such as content-type, encoding, contentId, content-description(often not provide in multipart/related), and the body itself.

The structure described above is very different than your current api and wondering if you would be ok with that or recommend one that may aline better with the current api.

I believe this can work with mostly cloning the current multipart type and tracking the relationship between two parts.

**Comment by mscdex** [comment]
As previously stated, compatibility with other (multipart or otherwise) formats is not a goal of this project, especially because they introduce other semantics. That kind of functionality is better suited to a different project (which could also be built upon the same underlying parser if desired).

**Comment by chrisgh1** [comment]
@TLPcoder I'm currently working on trying to do something similar for use with the [node-soap](https://github.com/vpulim/node-soap) project for reading multipart/related responses from soap calls.  I got it somewhat working with a package called [parse-multipart](https://github.com/freesoftwarefactory/parse-multipart) however it is lacking in performance and fails with large files.  This is what lead me to see if busboy could perform this function.  

Not really related to this issue just wanted to pass along the info.
