### ISSUE TITLE
emit close events

### ISSUE THREAD

**Issue by jonathanong** [mscdex/busboy#18]
i notice you emit a `limit` event, but IMO you should also emit a `close` event both on that specific file stream as well as the busboy parser stream to signify the parser has stopped. i use the `close` event to properly cleanup stuff.

http://nodejs.org/api/stream.html#stream_event_close

the `close` event should be emitted after the `limit` event.

**Comment by goatandsheep** [comment]
@mscdex has this been fixed?

**Comment by mscdex** [comment]
This should be resolved in `busboy` v1.0.0 and with modern versions of node, which will emit `'close'` natively on streams.
