### ISSUE TITLE
Better documentation of events

### ISSUE THREAD

**Issue by rightaway** [mscdex/busboy#180]
The `limit`, `close`, `end`, `finish` and `error` events are missing from https://github.com/mscdex/busboy#busboy-special-events, these should be documented and described. Same for whichever events get emitted when `fieldNameSize`, `fieldSize` and `headerPairs` limits are exceeded.

**Comment by mscdex** [comment]
* `'limit'` is documented in the `'file'` event description
* `'close'`, `'end'`, `'finish'`, and `'error'` are all standard node.js stream events, so they are not explicitly documented on purpose
* Both `fieldNameSize` and `fieldSize` simply result in truncation, so there are no events when those limits are reached
* `headerPairs` has no associated event, it simply stops parsing any header pairs past that limit

**Comment by rightaway** [comment]
I think these should be added to the documentation as it helps with understanding how to use them. Also just a one liner for the standard node.js stream events.
