### ISSUE TITLE
mimetype in nautilus is different from the mimetype given by busboy

### ISSUE THREAD

**Issue by phyyyl** [mscdex/busboy#184]
I am using `express-fileupload` `1.0.0-alpha.1`, whith ` busboy` `0.2.14` as a dependencie.

When I uploaded a .js file, the mimetype given by busboy was `application/x-javascript`, but in the file properties of nautilus (ubuntu file explorer) the type is specified as `application/javascript`.
`express-fileupload` does not change the mimetype.

Is there a specific reason for this?

**Comment by mscdex** [comment]
Mime types are supplied by the HTTP client (e.g. your browser), not `busboy`. You would probably need to consult the source code (if possible) for whichever HTTP client is being used to upload the file to find out why that mime type is being chosen.

**Comment by phyyyl** [comment]
OK, thanks :D 👍
