### ISSUE TITLE
Why limits not worked?

### ISSUE THREAD

**Issue by odykyi** [mscdex/busboy#185]
```
const busboy = new Busboy({
        headers: req.headers,
        limits: {
          files: 1,
          fileSize: 50000,
        },
      });
```

I upload file more then provided size
How I can see error like a "ERR uploading, max size 5mb"

**Comment by jaydenseric** [comment]
For starters, `50000` bytes is 0.05 MB. Are you saying the error message is a few decimal places off?

**Comment by mscdex** [comment]
See [the events documentation](https://github.com/mscdex/busboy#busboy-special-events) to learn how to detect when limits are reached.
