### ISSUE TITLE
Reproducible hang in busboy

### ISSUE THREAD

**Issue by robinhouston** [mscdex/busboy#188]
I’ve been investigating an occasional hang in our application, and tracked it down to what appears to be a busboy issue. There is a test case (client and server) in [this repository](https://github.com/kiln/busboy-issue). See the README in that repository for instructions and some discussion. A couple of key points from there:

* The problem only seems to occur when using the `.pipe()` method of the file object. Listening for `data` and `end` events works as expected, without hanging.
* It seems to depend on how the request is split across TCP/IP packets. Sending the terminator string in the same chunk as the final field also makes it work without hanging.

Issues of this sort seem to have been reported before (e.g. #116, mscdex/connect-busboy#15; probably others) without any resolution being reached. I hope having a simple test case will make it easier to find the root cause.

**Comment by robinhouston** [comment]
By adding some logging to the busboy code and looking at the patterns of reads in the failing case, I’ve been able to refine the test client so that the problem now happens reliably on the first request every time the test client is run.

**Comment by robinhouston** [comment]
I’ve now added a [standalone demonstration](https://github.com/kiln/busboy-issue/blob/master/standalone/index.js) that calls busboy directly, rather than using a client and a server.

Run:
```
(cd standalone && npm start)
```
and note that it does not print field `bar`, nor does it print `Completed successfully!`.

**Comment by robinhouston** [comment]
If I add this:

```js
  console.log(" *busboy* read chunk of length " + chunk.length);
```

to the beginning of the `Busboy.prototype._write()` method, we can see that the `_write` method is not being called for the final 56-byte chunk that is written.

**Comment by robinhouston** [comment]
Adding `fileHwm: 200000` to the busboy configuration options makes the test run successfully, which should be a clue as to where the problem lies.

**Comment by robinhouston** [comment]
FWIW, the following change to busboy seems to make my test work:

```diff
diff --git a/lib/types/multipart.js b/lib/types/multipart.js
index d33492a..c849c40 100644
--- a/lib/types/multipart.js
+++ b/lib/types/multipart.js
@@ -227,6 +227,7 @@ function Multipart(boy, cfg) {
         onEnd = function() {
           curFile = undefined;
           file.push(null);
+          self._pause = false;
         };
       } else {
         // non-file field
```

I don’t really understand what the purpose of the `_pause` flag is, so I have no idea whether or not this is a reasonable change to make. But in any case it may be interesting that this change seems to make it work!

**Comment by mscdex** [comment]
Thanks for repro repo! I ended up at the same conclusion as you, however I made the fix in a slightly different place because a `file.push(null)` may not translate to `'end'` being emitted immediately if the file stream is paused IIRC.

**Comment by robinhouston** [comment]
Great! Thank you so much for the quick fix.

Are you planning a release any time soon? I can switch to the unreleased version if not, but obviously it would be easier to use a release if there’s one coming up.

**Comment by jaydenseric** [comment]
@mscdex thanks for the quick fix, [`graphql-upload`](https://npm.im/graphql-upload) consumers had noticed this subtle issue but we couldn't pin it down at the time. 

But why is this release semver v0.3.0 instead of v0.2.15?

And could you please release v1.0.0. Consumers won't get fixes like this without every library author manually changing their `busboy` v0.x dependency and publishing a new release:

<img width="599" alt="screen shot 2019-01-10 at 10 32 46 am" src="https://user-images.githubusercontent.com/1754873/50936276-2432d480-14c3-11e9-8623-775235421560.png">

**Comment by jaydenseric** [comment]
Ahh, looks like the bumped supported Node.js version was the breaking change: https://github.com/mscdex/busboy/commit/db9b25f2b88fd4689d78d74b1fdc9de7f10d5f3d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12

**Comment by mscdex** [comment]
> Ahh, looks like the bumped supported Node.js version was the breaking change: [db9b25f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12](https://github.com/mscdex/busboy/commit/db9b25f2b88fd4689d78d74b1fdc9de7f10d5f3d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R12)

Correct.

As far as semver goes, none of my projects follow semver. It's easy enough to do `~0.3.0` to stay on that branch without any intentional breaking changes from v0.4.0.
