### ISSUE TITLE
 writeablestream.read is not a function at Busboy.

### ISSUE THREAD

**Issue by philross88** [mscdex/busboy#190]
I have a very simple code. I receive multi-part/form-data  and then I parse that using busboy. 
I am trying to read the content of the uploaded file and then email that as an attachment (using nodemailer).  
Here is the problem, you can write the content of the file to filesystem using `file.pipe(require('fs').createWriteStream('file.output'));`  but if you try to do `file.read() `you get null. SImilarly if you create a writeable stream and do file.pipe to writeablestream such as `file.pipe(someWriteableStream)`, I get an error message "writeablestream.read is not a function".

It seems like there is no way to pass a stream data to another stream (excluding filesystem) using busboy.

Below is the sample code:
  ```
var bb = new busboy({ headers: { 'content-type': contentType }});
  bb.on('file', function (fieldname, file, filename, encoding, mimetype) {
    console.log('File [%s]: filename=%j; encoding=%j; mimetype=%j; contents: %s', fieldname, filename, encoding, mimetype, file.read());
     //file.pipe(require('fs').createWriteStream('/tmp/output.pdf')); -- this works but the below doesn't
    file.pipe(writableStream);

    console.log("The file.read is %s",writableStream.read()); // this returns null. How do I pass the stream to nodemailer to create an attachment? I don't want to write files to a filesystem.
     file.on('data', function (data){
      console.log('File [%s] got %d bytes', fieldname, data.length)
      wholeData = wholeData.concat(data);
      wholeData+=data; // this converts binary files to string and the pdf attachments are not working properly
   
    });
    file.on('end', function() {
      fileContents = wholeData; // Here the fileContents, once emailed are messed up if the uploaded files are pdf or some binary format.
    });

  });
  bb.on('field', (fieldname, val) => {
    console.log('Field [%s]: value: %j', fieldname, val);
    if (fieldname.toString().trim() === 'email') {
     }
  })
  bb.on('finish', () => {
    console.log('Done parsing form!');
    sendEmail(fileContent)', function (err, data) { //send email sends 200 if all works
   });


  })
  .on('error', err => {
    console.log('failed', err);
    context.fail({ statusCode: 500, body: err, headers });
  });

  bb.end(bodyBuffer);
 
```

**Comment by mscdex** [comment]
Where does `writableStream` come from?

**Comment by mscdex** [comment]
It's normal for `file.read()` to return `null`, it just means no chunk is available at that moment (`'readable'` will be emitted when one is).

**Comment by philross88** [comment]
This is how I declared writeable stream 
`var writableStream = new Stream.Writable();`

So how come file.read() returns null while file.pipe can write it to file system? 
Can you suggest a way to get the stream of data without writing to file system? If you look at my code above, I am doing concatenation `wholeData+=data;` this is corrupting the binary files such as PDFs.
When I write the file to a file system using file.pipe(), re-reading and sending that works perfectly fine.

**Comment by mscdex** [comment]
If you pipe it, it's writing to the stream. However you need to have a fully implemented `Writable` stream (especially you need to do something with the data entering the `Writable` stream). See the [node documentation](https://nodejs.org/docs/latest/api/stream.html#stream_implementing_a_writable_stream) for more details on how to accomplish that.
