### ISSUE TITLE
how to handle exception when not any file uploaded

### ISSUE THREAD

**Issue by umar0107** [mscdex/busboy#197]
`const file = (req, user) => {
    return new Promise((resolve, reject) => {
        const busboy = new Busboy({ headers: req.headers });
        busboy.on('field', function (fieldname, val) {
            // some code
        });
        busboy.on('file', async (fieldname, file, filename, encoding, mimetype) => {
            //some code
            return resolve()
        });
       busboy.on('finish', function() {
           return reject()
       });
        busboy.end(req.rawBody);
    })
}`

when not any file uploaded then it works file but it also reject file uploaded
if i remove `busboy.on('finish', function() {
           return reject()
       });`
and not upload any file then it not return any response unless request fail

**Comment by mscdex** [comment]
I'm not quite sure I follow, but the `'finish'` event handler should always be called, so it would probably be best to put your accept/reject logic in there instead. You could set a flag in your `'file'` event handler that you then check in the `'finish'` event handler to know whether to accept or reject the promise.

**Comment by umar0107** [comment]
hi @mscdex 
is there any way to handle, if i upload any file against key or even not pass any param in body?
anyways above sound good let me try, then i will let you know if will in trouble
thanks

**Comment by markstos** [comment]
This issue can be closed.
