### ISSUE TITLE
Missing data when using busboy inside Lambda?

### ISSUE THREAD

**Issue by maxcrane** [mscdex/busboy#199]
Hi,

First off, thank you for writing this library. I'm hoping to use it in my current project. I am trying to use busboy on a lambda function to process a post request which is supposed to upload an image file. This is what I have in my client code:

```js
const formData = new FormData();
formData.append("file", params.file, params.file.name);

const request = new XMLHttpRequest();
request.open("POST", "https://myapi/uploadphoto");
request.setRequestHeader('Authorization', this.props.idToken);
request.send(formData);
```

and in my lambda function I have this method to get the file contents:

```js
function getFile(event) {
   const busboy = new Busboy({headers: event.headers});
   const result = {};

   return new Promise((resolve, reject) => {
      busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
         file.on('data', data => {
            result.content = data;
            console.log("got data... " + data.length + ' bytes');
         });

         file.on('end', () => {
            result.filename = filename;
            result.contentType = mimetype;
            resolve(result);
         });
      });

      busboy.on('error', error => reject(error));
      busboy.write(event.body, event.isBase64Encoded ? 'base64' : 'binary');
      busboy.end();
   });
}
```

When trying with an example photo, I notice that the "got data" console log is showing me that I am not receiving the whole file. The file I am using is 229707 bytes but the console log says that it received 217351 bytes. 

I tried changing the call to busboy.write to just use 'base64' since it looks like the file arrives in binary, but that didn't work either. 

I am wondering if I am using busboy wrong or if this is some quirk of lambda + api gateway. Any ideas or help troubleshooting is much appreciated. Thank you!

**Comment by mscdex** [comment]
`file` is a stream, so the file data could arrive in more than one chunk. You should collect these chunks and combine them in your `'end'` event handler if you really want to buffer the entire thing in memory.

**Comment by maxcrane** [comment]
Ok, so you're saying I need to collect the chunks in the ```'data'``` handler? The thing is I can see in my logs that the handler is only being called once, so I think that the problem has to be elsewhere. 

I also see that the encoding busboy is reporting is 7bit, and I am thinking that may the issue, but I'm not sure how to fix that.

**Comment by mscdex** [comment]
`'7bit'` is just the default encoding used when no `'Content-Transfer-Encoding'` header is specified for a part (which is what [the most recent multipart/form-data RFC recommends](https://tools.ietf.org/html/rfc7578#section-4.7) doing -- dropping such headers from parts).

Do you see your file `'end'` event handler being called?

**Comment by maxcrane** [comment]
Yes, the ```end``` event handler is definitely being called. I am able to see the results when the promise resolves.

**Comment by mscdex** [comment]
Are you able to reproduce the issue outside of Lambda, using the same file, same client-side code, and same server-side (as much as possible) code?

**Comment by maxcrane** [comment]
I just tried by modifying the example in the readme for this repo
```js
var http = require('http'),
    inspect = require('util').inspect;

var Busboy = require('busboy');

http.createServer(function(req, res) {
  if (req.method === 'POST') {
    var busboy = new Busboy({ headers: req.headers });
    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      console.log('File [' + fieldname + ']: filename: ' + filename);
      file.on('data', function(data) {
        console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
      });
      file.on('end', function() {
        console.log('File [' + fieldname + '] Finished');
      });
    });
    busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated) {
      console.log('Field [' + fieldname + ']: value: ' + inspect(val));
    });
    busboy.on('finish', function() {
      console.log('Done parsing form!');
      res.writeHead(303, { Connection: 'close', Location: '/' });
      res.end();
    });
    req.pipe(busboy);
  } else if (req.method === 'GET') {
    res.writeHead(200, { Connection: 'close' });
    res.end('<html><head></head><body>\
               <form method="POST" enctype="multipart/form-data">\
                <input type="file" name="image">\
                <input type="submit">\
              </form>\
            </body></html>');
  }
}).listen(3000, function() {
  console.log('Listening for requests');
});
```
the output:
```
Listening for requests
File [image]: filename: test-cat.png
File [image] got 65396 bytes
File [image] got 65536 bytes
File [image] got 65536 bytes
File [image] got 33239 bytes
File [image] Finished
```
Finder is telling me the file is 229,707 bytes which is still off compared to the 229,427 bytes which it look like busboy processed. However, it looks like using an html form with ``` enctype="multipart/form-data``` is already changing how busboy is processing this data compared to how it was working on my lambda function, so I'm thinking the problem has something to do with how I'm actually submitting the post request. I'll keep digging around for info related to that.

**Comment by Smoodle** [comment]
Hey sorry for the late response, had the same issue and finally got it working.
In my case i use AWS Lambdas so anyone still looking for a solution this is how i did it.

**This is not a busboy issue**, you just need to enable binary support in API Gateway (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html)

All your initial code is correct, this is my code:

```
module.exports.parseFormData = (event) => new Promise((resolve, reject) => {
	const busboy = new Busboy({
		headers: event.headers
	});

	let result = {
		files: []
	};

	busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
		file.on('data', data => {
			result.files.push({
				file: data,
				fileName: filename,
				contentType: mimetype
			});
		});
	});

	busboy.on('field', (fieldname, value) => {
		try {
			result[fieldname] = JSON.parse(value);
		} catch (err) {
			result[fieldname] = value;
		}
	});

	busboy.on('error', error => reject(`Parse error: ${error}`));
	busboy.on('finish', () => {
		event.body = result;
		resolve(event);
	});

	busboy.write(event.body, event.isBase64Encoded ? 'base64' : 'binary');
	busboy.end();
});

```


If you use serverless framework to manage your lambdas you just need to add this to provider setting

```
provider:
    apiGateway:
    binaryMediaTypes:
            - '*/*'
```

Hope this helps.

**Comment by mscdex** [comment]
Thanks @Smoodle for the info!

**Comment by canvaspixels** [comment]
I'm getting the same thing as @maxcrane I'm just doing a test locally that calls the handler directly and mocks the form-data binary stream, busboy seems to be dropping the mimetype.

**Comment by FaridSafi** [comment]
Thank you @Smoodle, you saved me a lot of time.
Here my version with little improvements.

```js
const Busboy = require("busboy");
const parseFormData = (event) => {
  return new Promise((resolve, reject) => {
    const busboy = new Busboy({
      headers: {
        ...event.headers,
        "content-type":
          event.headers["Content-Type"] || event.headers["content-type"],
      },
    });
    const result = {
      files: [],
    };

    busboy.on("file", (fieldname, file, filename, encoding, mimetype) => {
      file.on("data", (data) => {
        result.files.push({
          file: data,
          fileName: filename,
          contentType: mimetype,
        });
      });
    });
    busboy.on("field", (fieldname, value) => {
      try {
        result[fieldname] = JSON.parse(value);
      } catch (err) {
        result[fieldname] = value;
      }
    });
    busboy.on("error", (error) => reject(`Parse error: ${error}`));
    busboy.on("finish", () => {
      event.body = result;
      resolve(event);
    });
    busboy.write(event.body, event.isBase64Encoded ? "base64" : "binary");
    busboy.end();
  });
};
```

**Comment by Zeeeeta** [comment]
> Thank you @Smoodle, you saved me a lot of time.
> Here my version with little improvements.
> 
> ```js
> const Busboy = require("busboy");
> const parseFormData = (event) => {
>   return new Promise((resolve, reject) => {
>     const busboy = new Busboy({
>       headers: {
>         ...event.headers,
>         "content-type":
>           event.headers["Content-Type"] || event.headers["content-type"],
>       },
>     });
>     const result = {
>       files: [],
>     };
> 
>     busboy.on("file", (fieldname, file, filename, encoding, mimetype) => {
>       file.on("data", (data) => {
>         result.files.push({
>           file: data,
>           fileName: filename,
>           contentType: mimetype,
>         });
>       });
>     });
>     busboy.on("field", (fieldname, value) => {
>       try {
>         result[fieldname] = JSON.parse(value);
>       } catch (err) {
>         result[fieldname] = value;
>       }
>     });
>     busboy.on("error", (error) => reject(`Parse error: ${error}`));
>     busboy.on("finish", () => {
>       event.body = result;
>       resolve(event);
>     });
>     busboy.write(event.body, event.isBase64Encoded ? "base64" : "binary");
>     busboy.end();
>   });
> };
> ```

Thanks a lot, ```busboy.write(event.body, event.isBase64Encoded ? "base64" : "binary");``` this line saved me.

I was base64 decoding by myself using ```let decodedString = Buffer.from(body, 'base64').toString()```
and then submit to busboy with ```busboy.end(decodedString)```, I could get fields and plain text file from it, however for an image file such as png, it gives me a Buffer of roughly 1.8 times the original size, which I could not turn it back into a valid image.
With 
```
busboy.write(body, "base64");
busboy.end();
```
I am able to get the correct image back.

What's was the problem for decoding with my own way? Is that I need some extra processing on the image buffer in order to get it right?

**Comment by mscdex** [comment]
@Zeeeeta The default encoding for `buffer.toString()` is UTF-8, which could easily mangle binary data. If you dropped the `.toString()` and left it as a Buffer it would have been fine because the binary data would be intact.

**Comment by tomtom94** [comment]
Big mistake you didn't RTFM read the fucking manual.

https://github.com/mscdex/busboy/issues/199#issuecomment-625952696

when doing the `busboy.on('file')` event you better use `file.on('data')` & `file.on('end')` both combined.

Which would give you

```
    busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
      const buffers = [];

      file.on('data', function (data) {
        buffers.push(data);
      });

      file.on('end', function () {
        result.files.push({
          file: Buffer.concat(buffers),
          fileName: filename,
          contentType: mimetype,
        });
      });
    });
```

Cheers
