### ISSUE TITLE
Parsing fails if filename contains UTF-8 characters

### ISSUE THREAD

**Issue by avidenie** [mscdex/busboy#20]
Steps to reproduce:
1. Install and start the server
   
   > - mkdir test
   > - cd test
   > - npm install busboy
   > - vim server.js _<= paste the example from the readme.md_
   > - node server.js
2. Perform an upload using a file with ASCII characters

> curl -v -F 'id=123' -F "file=@test.mp4;type=video/mp4" http://localhost:8000

In console, you get this:

> File [file]: filename: test.mp4, encoding: 7bit
> File [file] got 65305 bytes
> Field [id]: value: '123'
> File [file] got 65536 bytes
> [...]
> File [file] Finished
> Done parsing form!

Curl call finishes correctly:

> < HTTP/1.1 100 Continue
> < HTTP/1.1 303 See Other
> < Connection: close
> < Location: /
> < Date: Tue, 10 Dec 2013 09:21:15 GMT
> < Transfer-Encoding: chunked
1. Perform an upload using a file with UTF-8 characters

> cp test.mp4 お疲れ様です.mp4
> curl -v -F 'id=123' -F "file=@お疲れ様です.mp4;type=video/mp4" http://localhost:8000

In console, you get this:

> Field [id]: value: '123'

Curl call will eventually timeout:

> < HTTP/1.1 100 Continue
> * Recv failure: Connection reset by peer
> * Closing connection 0

**Comment by bug249286** [comment]
Parsing fails if filename contains UTF-8 characters

Content-Disposition: form-data; name="file"; filename="**ทดสอบภาษาไทย.xlsx**"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

`const bb = busboy({ headers: req.headers ,defCharset:'utf8'});`

info {
  filename: '**à¸\x97à¸\x94à¸ªà¸­à¸\x9Aà¸ à¸²à¸©à¸²à¹\x84à¸\x97à¸¢.xlsx**',
  encoding: '7bit',
  mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
}

filename Parsing fail.
how to fix.

Thank you.

**Comment by mscdex** [comment]
@bug249286 Clients should be sending non-latin1 header parameter values using the format (encoded words) defined by [RFC5987](https://datatracker.ietf.org/doc/html/rfc5987). If they don't send that, then the values are assumed to be encoded as latin1.

You can safely convert the filename to utf-8 since latin1 preserves individual bytes. For example: `Buffer.from(filename, 'latin1').toString('utf8')` or using [`TextDecoder`](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder), node supports both.

**Comment by bug249286** [comment]
@mscdex Thank you very much.

**Comment by CleyFaye** [comment]
I am confused on how we are supposed to send UTF-8 (or other) strings. While [RFC5987](https://datatracker.ietf.org/doc/html/rfc5987) do mention extended parameters, [RFC7578](https://datatracker.ietf.org/doc/html/rfc7578#section-4.2) discourage their use, and some actual browser do not send the extra `filename*` (including Chrome, Edge and Firefox), instead putting the utf-8 name in `filename`.

As it is, we can to the aforementioned conversion by hand outside of busboy (or in my case multer), but is that really something that fall outside the scope of this library, seeing that the "supported" method of using `filename*` is not used much in the wild?

**Comment by mscdex** [comment]
@CleyFaye Writing a library like this that works for everyone everywhere is basically impossible. IMO it's safer to err on the side of history for compatibility purposes until all clients *overwhelmingly* assume UTF-8 values for filenames. The workaround I provided earlier in this issue is a valid solution if you are in control of the client and want to assume UTF-8.

**Comment by CleyFaye** [comment]
I agree that it is a valid solution (and I am using it already), but my question was more about how we are supposed to do this if we wanted to do it "properly". My use cases are limited to common browsers (and react-native to some extent) and no client send UTF-8 data the way described in RFC5987 (using extended parameters).

This, in addition to the comment in RFC7578 regarding not using extended parameters for filename in form data leaves me confused as to what's the proper way to handle this. In that sense, starting to add `filename*` into formdata client side would seem to go the opposite direction as everyone else (in addition to being tedious).

Anyway, I just now see that this is a quite old issue, so it's probably not the correct place to discuss this. I only found out recently through an update of the multer library. Sorry for the noise.

**Comment by mscdex** [comment]
@CleyFaye If you're using HTML forms, I would say either set the page's encoding to utf-8 or set the form's `accept-charset` attribute to utf-8 (it defaults to the page encoding if not set). If nothing else, another potential solution that would work for HTML and non-HTML would be to send the encoding as the first field in the form.
