### ISSUE TITLE
json blob within multipart

### ISSUE THREAD

**Issue by simllll** [mscdex/busboy#201]
I'm trying to achieve sending json and files within one request.
e.g. 

```js
const form = new FormData();
form.append('jsonStuff', new Blob([JSON.stringify({a: 1})], {type: 'application/json'});
form.append('myImage', image, 'imag.jpg')

```
The problem is that chrome, firefox and other browsers set a default filename for the "jsonStuff" blob (the fielname is "blob"). I can override it, but I cannot eleminate it. 
Unfortunately busboy checks if the content type is an octect stream or the filename is not undefined. So it's not a workaround to set an empty filename.
e.g. with `form.append('jsonStuff', new Blob([JSON.stringify({a: 1})], {type: 'application/json'}, '');`

The check of busboy https://github.com/mscdex/busboy/blob/da0e67d503cc39727dfa3a85c142d19de6f2c8c7/lib/types/multipart.js#L174

**My question** is now: Is there a reason why the check is filename !== undefined and not a simple `|| filename`). In this case I could set the filename to an empty string, and could go on with my approach. 

Any other options out there?
* e.g. ignore "blob" as filename
* come up with a custom filename that gets ignored
* ...?

see also https://github.com/mscdex/busboy/pull/200

Thanks
Simon

**Comment by mscdex** [comment]
> Is there a reason why the check is filename !== undefined and not a simple `|| filename`)

The reason is that historically the existence of a `filename` attribute has indicated the source of the part was a file and not something else.

**Comment by simllll** [comment]
Okay, and do you think it would be also okay to just check for the "value" of filename.. e.g.
`js
 if (contype === 'application/octet-stream' || filename) {
`?

**Comment by mscdex** [comment]
Not really, as that would treat files with empty names from being treated as 'files'.

**Comment by mscdex** [comment]
Not really, because that would treat files with empty filenames from being emitted as files.

**Comment by simllll** [comment]
And adding one custom special filename .. e.g. binary 0 that gets omnitted. So if someone sets the filename to \ 0 then it's parsed as field?

**Comment by simllll** [comment]
One more idea: What do you think about an option that allows some specific "filename" to get skipped, it's unset by default and so the behaviour would be the same. Just when you set the filename, to e.g. "blob", I can solve my situation easily ;)?

**Comment by mscdex** [comment]
I'm not really keen on adding niche features like that, I prefer to keep this module to the bare minimum of parsing forms and presenting them in a easily consumable format.

**Comment by simllll** [comment]
I agree, I added a PR on multer to solve this issue.
