### ISSUE TITLE
writing integration tests with busboy

### ISSUE THREAD

**Issue by GWSzeto** [mscdex/busboy#205]
I'm currently trying to write some integration tests using mocha and I'm trying to test streaming in an audio file from busboy into S3. I know as of right now that my fs setup for the test case is correct and is streaming properly when I stream it into my local directory.

As of right now, I think my problem is mocking the headers for the initialization of Busboy. Heres the code for the mocha test case

```JavaScript
  it.only('uploads the request to the specified s3 bucket', async () => {
    const mockStream = fs.createReadStream('tests/audioResources/test.mp3');
    const mockUploadAudio = sinon.stub().returns();
    const mockHeaders = {
      host: 'localhost:8000',
      'user-agent': 'curl/7.54.0',
      accept: '*/*',
      'content-length': '444127',
      expect: '100-continue',
      'content-type': 'multipart/form-data; boundary=------------------------dd65445e5a55dcc7',
    };

    const uploadStub = {
      maxPartSize: sinon.stub().returns(),
      concurrentParts: sinon.stub().returns(),
      on: sinon.stub().returns(),
    };

    const services = {
      s3Stream: {
        upload: sinon.stub().returns(uploadStub),
      },
    };
    const config = {
      AudioBucket: 'AudioBucket',
    };
    const audioManager = new AudioManager(services, config);

    await audioManager.upload(mockStream, mockHeaders, mockUploadAudio);
```

and heres the chunk of code it is testing

```JavaScript
  self.upload = async (reqStream, headers, uploadAudio = self.uploadToS3) => {
    const busboy = new Busboy({ headers });
    const busboyPromise = new Promise((resolve, reject) => {
      busboy.on('file', (fieldname, file, filename) => {
        const key = `${Date.now().tostring()}-${filename
          .tolowercase()
          .replace(/\s+/g, '-')
          .replace(/[^\w\-.]+/g, '')}`;

        const params = {
          bucket: AudioBucket,
          key,
        };

        const s3upload = s3Stream.upload(params);
        s3upload.maxpartsize(20971520);
        s3upload.concurrentparts(5);
        s3upload.on('error', (err) => reject(err));
        s3upload.on('uploaded', () => resolve());

        uploadAudio(file, s3upload);
      });
    });

    reqStream.pipe(busboy);

    return busboyPromise;
  };
```
When I do execute the code above, it just hangs and then times out

**Comment by mscdex** [comment]
It's not enough to just set `content-type`, you have to actually format the request appropriately. You might take a look at the `busboy` unit tests as a reference.

**Comment by GWSzeto** [comment]
I took a look at the unit tests and looked at some docs for request headers and from what I understand, I believe I have the correct media type. As for the boundary, I'm confused as to what should be the correct boundary since they appear to be a string of random characters.

**Comment by ErickWendel** [comment]
Any help with it?

**Comment by mscdex** [comment]
You need to format your request data appropriately according to the `multipart/form-data` type. It is not enough to set the appropriate Content-Type header and just send raw binary data.

If you discover you are still having issues after having crafted the body of your request correctly, let me know.
