### ISSUE TITLE
on file is not triggered

### ISSUE THREAD

**Issue by vimalchandhru** [mscdex/busboy#206]
busboy.on('finish',()={}) is triggered but on **file** and **field** are not triggered eventhough I sent multipart data( from restlet client)

`exports.uploadFile = functions.https.onRequest((request,response)=>{

    var busboy = new Busboy({ headers: request.headers });

    console.log("logtest===>");
console.log(JSON.stringify(request.headers));

    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
        console.log('File [' + fieldname + ']: filename: ' + filename);
        file.on('data', function(data) {
            console.log('File [' + fieldname + '] got ' + data.length + ' bytes');
        });
        file.on('end', function() {
            console.log('File [' + fieldname + '] Finished');
        });
    });

    busboy.on('field',()=>{
        console.log("comming to field");
    });
    busboy.on('finish',function(){
        console.log("busy boy finished===>");
        response.writeHead(200, { Connection: 'close', Location: '/' });
        response.end();
      
    })
    request.pipe(busboy);
})

==logged headers==
{"host":"localhost:5001","connection":"keep-alive","content-length":"147","origin":"chrome-extension://extensionId","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","content-type":"multipart/form-data; boundary=----WebKitFormBoundaryJibFiM6dZpDRgnDQ","accept":"*/*","accept-encoding":"gzip, deflate, br","accept-language":"en-GB,en-US;q=0.9,en;q=0.8"}

`

**Comment by mscdex** [comment]
I just tested with the Restlet client and had no problems after ensuring the request was setup properly (as multipart/form-data).

**Comment by vimalchandhru** [comment]
This is my setup.Correct me if I am wrong. @mscdex 
<img width="1329" alt="Screenshot 2019-06-14 at 9 40 13 AM" src="https://user-images.githubusercontent.com/10485165/59482914-8df74600-8e88-11e9-807a-6545bb4fd9eb.png">

**Comment by maranac0d3r** [comment]
@vimalchandhru  +1 . I also have this issue.

@mscdex

**Comment by mscdex** [comment]
From what I remember that looks right to me. Is it possible something else is consuming the request data so there is no data left for `busboy`? I tested with just a bare `require('http').createServer()`.

**Comment by vimalchandhru** [comment]
I am using this code in firebase functions. They are creating their own server by 

var functions = require('firebase-functions');

exports.uploadFile = functions.https.onRequest((req,res)=>{})

I don't think it will consuming the request data, because when I log req.body

` ------WebKitFormBoundarynBr6LRbVg79ajHsC
Content-Disposition: form-data; name="htmlfile"


------WebKitFormBoundarynBr6LRbVg79ajHsC
Content-Disposition: form-data; name="tetsdf"

dfsdfdsfds
------WebKitFormBoundarynBr6LRbVg79ajHsC--

`
this is printing...

FYI: [https://www.youtube.com/watch?v=qZ1EFnFOGvE&list=PL55RiY5tL51r5jyQoPZhwLueLpPeAV6P9&index=3](https://www.youtube.com/watch?v=qZ1EFnFOGvE&list=PL55RiY5tL51r5jyQoPZhwLueLpPeAV6P9&index=3
)

In this turtorial he is using busboy in firebase functions.

I don't know how to debug the problem :-|

**Comment by mscdex** [comment]
There are two clues that just confirmed what I suspected:

1. If you have a `req.body` like that by the time you go to create your `Busboy` instance, then you can't just do `req.pipe(busboy)` because obviously there is no data left for `busboy` to consume -- it's all stored in that property.

2. The video you linked to explicitly mentions (at the 20:00 mark) having to do `busboy.end(req.rawBody)` instead of `req.pipe(busboy)` because the request data is buffered in memory already by firebase.

Perhaps due to the nature of firebase functions, it is not possible to stream the request data (I'm not familiar with firebase), which is unfortunate.

**Comment by vimalchandhru** [comment]
It's ok. Thanks for your valuable time for analysing this.

If the stream is not available is there any way to give request  to busboy for parsing it?

**Comment by mscdex** [comment]
See point number 2 in my previous comment.

**Comment by vimalchandhru** [comment]
yep!!!
Its working. busboy.end wan't working yesterday so I called req.pipe() but now busboy.end is working and the file events are triggered (just coder things ;-) )

But when I upload the png image the below error is showing (for text files the on file event triggered normally)

` Error: Part terminated early due to unexpected end of multipart data
>      at /Users/vimal/firebase/pre/functions/node_modules/busboy/node_modules/dicer/lib/Dicer.js:65:36
>      at _combinedTickCallback (internal/process/next_tick.js:131:7)
>      at process._tickCallback (internal/process/next_tick.js:180:9)
`
in Dicer - lineno 57  - 81
` Dicer.prototype.emit = function(ev) {
  if (ev === 'finish' && !this._realFinish) {
    if (!this._finished) {
      var self = this;
      process.nextTick(function() {
        self.emit('error', new Error('Unexpected end of multipart data'));
        if (self._part && !self._ignoreData) {
          var type = (self._isPreamble ? 'Preamble' : 'Part');
          self._part.emit('error', new Error(type + ' terminated early due to unexpected end of multipart data'));
          self._part.push(null);
          process.nextTick(function() {
            self._realFinish = true;
            self.emit('finish');
            self._realFinish = false;
          });
          return;
        }
        self._realFinish = true;
        self.emit('finish');
        self._realFinish = false;
      });
    }
  } else
    WritableStream.prototype.emit.apply(this, arguments);
};`

Is anything wrong ?
@mscdex

**Comment by mscdex** [comment]
If you inspect the literal request data, do you see the final boundary marker at the end (it should have a `--` after it to signify the end of all of the multipart data).

**Comment by vimalchandhru** [comment]
Not all multipart data but the last one have -- this.

<img width="1150" alt="Screenshot 2019-06-14 at 10 45 40 PM" src="https://user-images.githubusercontent.com/10485165/59526314-44454480-8ef6-11e9-8c0c-0c1ec898442f.png">

**Comment by mscdex** [comment]
I meant in the raw request body on the node side.

**Comment by Vibing** [comment]
I also have this issue,  has it been solved?


<img width="586" alt="WX20190624-162647@2x" src="https://user-images.githubusercontent.com/10387532/60003327-0c2fc580-969d-11e9-9077-ad5f5912f406.png">

<img width="262" alt="WX20190624-162748@2x" src="https://user-images.githubusercontent.com/10387532/60003343-15209700-969d-11e9-92ba-8b856a67c382.png">

it only show finish in console

![WX20190624-162721](https://user-images.githubusercontent.com/10387532/60003426-40a38180-969d-11e9-920e-8cfe4b40564b.png)

**Comment by mscdex** [comment]
@Vibing If you're using a framework or other module for your http requests, it's possible that the request data has already been read (and possibly buffered and stored as a property on `req`). If that's the case, piping to `busboy` will not work because there is no data left. If the data has been buffered, you will need to find where it's stored and pass it to `busboy.end()` instead.

**Comment by Vibing** [comment]
@mscdex 
Thank you for your answer.
If you can, I hope to have examples of various mainstream frameworks. This can help most people solve this issue.😊😊😊

**Comment by vimalchandhru** [comment]
I decided to go with "application/x-www-form-urlencoded" upload instead of form upload "application/x-www-form-urlencoded" upload is working fine and firebase parse the body stream defaultly.
@mscdex
