### ISSUE TITLE
My upload image gets stuck on "finish" event. It doesn't upload image on Firebase Storage

### ISSUE THREAD

**Issue by rades12340** [mscdex/busboy#208]
I'm having an issue with uploading an image on Firebase Storage with Firebase functions. It all works until it gets to the the _finish_ event of BusBoy. I console logged some arbitral word in finish event, but it doesn't get called.

This is the code:
 ```
 exports.uploadImage = (req, res) => {
  const BusBoy = require('busboy')
  const path = require('path')
  const os = require('os')
  const fs = require('fs')

  const busboy = new BusBoy({ headers: req.headers })

  let imageFileName
  let imageToBeUploaded = {}

  busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
    if (mimetype !== 'image/jpeg' && mimetype !== 'image/png') {
      return res.status(400).json({ error: 'Wrong file type submitted' })
    }
    const imageExtension = filename.split('.')[filename.split('.').length - 1]
    const imageFileName = `${Math.round(
      Math.random() * 10000000000000000
    )}.${imageExtension}`

    const filepath = path.join(os.tmpdir(), imageFileName)
    imageToBeUploaded = { filepath, mimetype }
    file.pipe(fs.createWriteStream(filepath))
  })
  busboy.on('finish', () => {
    admin
      .storage()
      .bucket()
      .upload(imageToBeUploaded.filepath, {
        resumable: false,
        metadata: {
          metadata: {
            contentType: imageToBeUploaded.mimetype
          }
        }
      })
      .then(() => {
        const imageUrl = `https://storage.cloud.google.com/${
          config.storageBucket
        }/${imageFileName}?alt=media`
        console.log(imageUrl)
        return db.doc(`/users/${req.user.handle}`).update({ imageUrl })
      })
      .then(() => {
        return res.json({ message: 'Image uploaded successfully' })
      })
      .catch(err => {
        console.log(err)
        return res.status(500).json({ error: err.code })
      })
  })
  busboy.end(req.rawBody)
}
```

"busboy": "^0.3.1",
    "dotenv": "^8.0.0",
    "firebase": "^6.2.3",
    "firebase-admin": "^8.0.0",
    "firebase-functions": "^3.0.0"

**Link to the GithHub repo:**
[https://github.com/rades12340/socialape/blob/master/functions/handlers/users.js](url)

**Comment by mscdex** [comment]
Is `req.rawBody` somehow missing the terminating boundary line?

Does it get called if your `'file'` event handler simply only does `file.resume()`?

**Comment by Neveon** [comment]
I'm working on the same project. I had to rollback `firebase-tools`.

In functions folder
`npm rm firebase-tools`
`npm i -g firebase-tools@6.8.0`
Then add `config.storageBucket` to the `.bucket()` in the `'finish'` event handler

I can now sleep in peace knowing I defeated another bug

**Comment by rades12340** [comment]
> I had to rollback `firebase-tools`.
> 
> In functions folder
> `npm rm firebase-tools`
> `npm i -g firebase-tools@6.8.0`
> Then add `config.storageBucket` to the `.bucket()` in the `'finish'` event handler
> 
> I can now sleep in peace knowing I defeated another bug

This worked. Thanks. I couldn't imagine it was because of this.

**Comment by soriasayer** [comment]
There is no problem with code neither with firebase versions. Try to remove Content-Type from postman headers that is it.

**Comment by umerali523** [comment]
> There is no problem with code neither with firebase versions. Try to remove Content-Type from postman headers that is it.

Thank you soriasayer Issue resolved by removing headers
