### ISSUE TITLE
client not receiving response after unpiping busboy from from limit event

### ISSUE THREAD

**Issue by cmd430** [mscdex/busboy#209]
after unpiping busboy from the limit event handler no response is received by the client, not unpiping busboy works fine but requires the remainder of the upload to be sent to the server. 

unpiping and returning a response from a custom event in the same way works fine

```js

//Don't work
file.once('limit', () => {
  req.unpipe(req.busboy)
  return res.status(413).json({
    file: filename,
    status: 413,
    message: 'file too large'
  })
})

// Work fine
filesig.on('signature', signature => {
  if (!signature.mimetype.includes(fileinfo.type)) {
    req.unpipe(req.busboy)
    return res.status(415).json({
      file: filename,
      status: 415,
      message: 'invaild filetype'
    })
  }
})
```

**Comment by mscdex** [comment]
I'm not sure what you mean by 'custom event', but did you try adding `req.resume()` after unpiping?

**Comment by cmd430** [comment]
sorry by custom event I mean an event not provided by busboy

> did you try adding req.resume() after unpiping?
I have just put that into my code and the same issue occurs, 

`file starts uploading -> hits limit -> stops uploading -> connection times out`

no response is received by the client, however if i cancel it from another event (in my case a filetype check) it goes as expected

`file starts uploading -> hits limit -> stops uploading -> error response received by client `

maybe being able to view the whole code will help ?
[upload.js](https://github.com/cmd430/stash.red/blob/develop/logic/route/upload.js)

**Comment by mscdex** [comment]
I'm not sure if there's anything magic happening in express, but in plain node it should be as simple as doing:

```js
res.writeHead(413, { Connection: 'close' });
res.end();
```
