### ISSUE TITLE
busboy.on not invoke - gives error

### ISSUE THREAD

**Issue by Oner-T** [mscdex/busboy#214]
Hello
my problem is, my image upload function doesn't work, to firebase storage. It never fires busboy.on function and catches error 
 here is the code: 

```
exports.uploadImage = (req, res) => {
  const BusBoy = require("busboy");
  const path = require("path");
  const os = require("os");
  const fs = require("fs");
  const busboy = new BusBoy({ headers: req.headers });
  
  let imageToBeUploaded = {};
  let imageFileName;

  busboy.on("file", (fieldname, file, filename, encoding, mimetype) => {
    console.log(fieldname, file, filename, encoding, mimetype);
    if (mimetype !== "image/jpeg" && mimetype !== "image/png") {
      return res.status(400).json({ error: "Wrong file type submitted" });
    }
    // my.image.png => ['my', 'image', 'png']
    const imageExtension = filename.split(".")[filename.split(".").length - 1];
    // 32756238461724837.png
    imageFileName = `${Math.round(
      Math.random() * 1000000000000
    ).toString()}.${imageExtension}`;
    const filepath = path.join(os.tmpdir(), imageFileName);
    imageToBeUploaded = { filepath, mimetype };
    file.pipe(fs.createWriteStream(filepath));
  });
  busboy.on("finish", () => {
    admin
      .storage()
      .bucket()
      .upload(imageToBeUploaded.filepath, {
        resumable: false,
        metadata: {
          metadata: {
            contentType: imageToBeUploaded.mimetype
          }
        }
      })
      .then(() => {
        const imageUrl = `https://firebasestorage.googleapis.com/v0/b/${config.storageBucket}/o/${imageFileName}?alt=media`;
        return db.doc(`/users/${req.user.handle}`).update({ imageUrl });
      })
      .then(() => {
        return res.json({ message: "image uploaded successfully" });
      })
      .catch(err => {
        console.error(err);
        return res.status(500).json({ error: "something went wrong" });
      });
  });
  busboy.end(req.rawBody);
};
```

my console.error is:
```

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
>      at validateString (internal/validators.js:125:11)
>      at Object.basename (path.js:1289:5)
>      at Bucket.upload (/Users/apple/Desktop/Oner/social_app/functions/node_modules/@google-cloud/storage/build/src/bucket.js:2237:38)
>      at PromiseCtor (/Users/apple/Desktop/Oner/social_app/functions/node_modules/@google-cloud/promisify/build/src/index.js:71:28)
>      at new Promise (<anonymous>)
>      at Bucket.wrapper (/Users/apple/Desktop/Oner/social_app/functions/node_modules/@google-cloud/promisify/build/src/index.js:56:16)
>      at Busboy.busboy.on (/Users/apple/Desktop/Oner/social_app/functions/handlers/users.js:122:8)
>      at Busboy.emit (events.js:198:13)
>      at Busboy.emit (/Users/apple/Desktop/Oner/social_app/functions/node_modules/busboy/lib/main.js:37:33)
>      at /Users/apple/Desktop/Oner/social_app/functions/node_modules/busboy/lib/types/multipart.js:304:17

```

**Comment by mscdex** [comment]
Did you check the `Content-Type` of the request?

If that checks out, did you try adding a `'field'` event handler to see if your file is being sent as a non-file entry?

**Comment by Oner-T** [comment]
Can you explain how can I do these, I couldn't console.log inside busboy function, it never enters the busboy.on, gives error directly and jumps to catch part

**Comment by Oner-T** [comment]
This is, when I console.log(req) :
`IncomingMessage {
>    _readableState:
>     ReadableState {
>       objectMode: false,
>       highWaterMark: 16384,
>       buffer: BufferList { head: null, tail: null, length: 0 },
>       length: 0,
>       pipes: null,
>       pipesCount: 0,
>       flowing: true,
>       ended: true,
>       endEmitted: true,
>       reading: false,
>       sync: false,
>       needReadable: false,
>       emittedReadable: false,
>       readableListening: false,
>       resumeScheduled: false,
>       paused: false,
>       emitClose: true,
>       autoDestroy: false,
>       destroyed: false,
>       defaultEncoding: 'utf8',
>       awaitDrain: 0,
>       readingMore: false,
>       decoder: null,
>       encoding: null },
>    readable: false,
>    _events:
>     [Object: null prototype] { end: [Function: resetHeadersTimeoutOnReqEnd] },
>    _eventsCount: 1,
>    _maxListeners: undefined,
>    socket:
>     Socket {
>       connecting: false,
>       _hadError: false,
>       _handle: null,
>       _parent: null,
>       _host: null,
>       _readableState:
>        ReadableState {
>          objectMode: false,
>          highWaterMark: 16384,
>          buffer: BufferList { head: null, tail: null, length: 0 },
>          length: 0,
>          pipes: null,
>          pipesCount: 0,
>          flowing: true,
>          ended: false,
>          endEmitted: false,
>          reading: true,
>          sync: false,
>          needReadable: true,
>          emittedReadable: false,
>          readableListening: false,
>          resumeScheduled: false,
>          paused: false,
>          emitClose: false,
>          autoDestroy: false,
>          destroyed: true,
>          defaultEncoding: 'utf8',
>          awaitDrain: 0,
>          readingMore: false,
>          decoder: null,
>          encoding: null },
>       readable: false,
>       _events:
>        [Object: null prototype] {
>          end: [Array],
>          drain: [Array],
>          timeout: [Function: socketOnTimeout],
>          data: [Function: bound socketOnData],
>          close: [Array],
>          resume: [Function: onSocketResume],
>          pause: [Function: onSocketPause],
>          error: [Function: noop] },
>       _eventsCount: 8,
>       _maxListeners: undefined,
>       _writableState:
>        WritableState {
>          objectMode: false,
>          highWaterMark: 16384,
>          finalCalled: false,
>          needDrain: false,
>          ending: false,
>          ended: false,
>          finished: false,
>          destroyed: true,
>          decodeStrings: false,
>          defaultEncoding: 'utf8',
>          length: 0,
>          writing: false,
>          corked: 0,
>          sync: false,
>          bufferProcessing: false,
>          onwrite: [Function: bound onwrite],
>          writecb: null,
>          writelen: 0,
>          bufferedRequest: null,
>          lastBufferedRequest: null,
>          pendingcb: 0,
>          prefinished: false,
>          errorEmitted: true,
>          emitClose: false,
>          autoDestroy: false,
>          bufferedRequestCount: 0,
>          corkedRequestsFree: [Object] },
>       writable: false,
>       allowHalfOpen: true,
>       _sockname: null,
>       _pendingData: null,
>       _pendingEncoding: '',
>       server:
>        Server {
>          _events: [Object],
>          _eventsCount: 2,
>          _maxListeners: undefined,
>          _connections: 0,
>          _handle: [Pipe],
>          _usingWorkers: false,
>          _workers: [],
>          _unref: false,
>          allowHalfOpen: true,
>          pauseOnConnect: false,
>          httpAllowHalfOpen: false,
>          timeout: 120000,
>          keepAliveTimeout: 5000,
>          maxHeadersCount: null,
>          headersTimeout: 40000,
>          _pipeName:
>           '/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock',
>          _connectionKey:
>           '-1:/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock:-1',
>          [Symbol(IncomingMessage)]: [Function],
>          [Symbol(ServerResponse)]: [Function],
>          [Symbol(asyncId)]: 15 },
>       _server:
>        Server {
>          _events: [Object],
>          _eventsCount: 2,
>          _maxListeners: undefined,
>          _connections: 0,
>          _handle: [Pipe],
>          _usingWorkers: false,
>          _workers: [],
>          _unref: false,
>          allowHalfOpen: true,
>          pauseOnConnect: false,
>          httpAllowHalfOpen: false,
>          timeout: 120000,
>          keepAliveTimeout: 5000,
>          maxHeadersCount: null,
>          headersTimeout: 40000,
>          _pipeName:
>           '/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock',
>          _connectionKey:
>           '-1:/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock:-1',
>          [Symbol(IncomingMessage)]: [Function],
>          [Symbol(ServerResponse)]: [Function],
>          [Symbol(asyncId)]: 15 },
>       timeout: 120000,
>       parser: null,
>       on: [Function: socketOnWrap],
>       _paused: false,
>       _httpMessage:
>        ServerResponse {
>          _events: [Object],
>          _eventsCount: 1,
>          _maxListeners: undefined,
>          output: [],
>          outputEncodings: [],
>          outputCallbacks: [],
>          outputSize: 0,
>          writable: true,
>          _last: false,
>          chunkedEncoding: false,
>          shouldKeepAlive: true,
>          useChunkedEncodingByDefault: true,
>          sendDate: true,
>          _removedConnection: false,
>          _removedContLen: false,
>          _removedTE: false,
>          _contentLength: null,
>          _hasBody: true,
>          _trailer: '',
>          finished: false,
>          _headerSent: false,
>          socket: [Circular],
>          connection: [Circular],
>          _header: null,
>          _onPendingData: [Function: bound updateOutgoingData],
>          _sent100: false,
>          _expect_continue: false,
>          req: [Circular],
>          locals: [Object: null prototype] {},
>          [Symbol(isCorked)]: false,
>          [Symbol(outHeadersKey)]: [Object] },
>       [Symbol(asyncId)]: 18,
>       [Symbol(lastWriteQueueSize)]: 0,
>       [Symbol(timeout)]:
>        Timeout {
>          _called: false,
>          _idleTimeout: -1,
>          _idlePrev: null,
>          _idleNext: null,
>          _idleStart: 1525,
>          _onTimeout: null,
>          _timerArgs: undefined,
>          _repeat: null,
>          _destroyed: false,
>          [Symbol(unrefed)]: true,
>          [Symbol(asyncId)]: 19,
>          [Symbol(triggerId)]: 18 },
>       [Symbol(kBytesRead)]: 147456,
>       [Symbol(kBytesWritten)]: 47 },
>    connection:
>     Socket {
>       connecting: false,
>       _hadError: false,
>       _handle: null,
>       _parent: null,
>       _host: null,
>       _readableState:
>        ReadableState {
>          objectMode: false,
>          highWaterMark: 16384,
>          buffer: BufferList { head: null, tail: null, length: 0 },
>          length: 0,
>          pipes: null,
>          pipesCount: 0,
>          flowing: true,
>          ended: false,
>          endEmitted: false,
>          reading: true,
>          sync: false,
>          needReadable: true,
>          emittedReadable: false,
>          readableListening: false,
>          resumeScheduled: false,
>          paused: false,
>          emitClose: false,
>          autoDestroy: false,
>          destroyed: true,
>          defaultEncoding: 'utf8',
>          awaitDrain: 0,
>          readingMore: false,
>          decoder: null,
>          encoding: null },
>       readable: false,
>       _events:
>        [Object: null prototype] {
>          end: [Array],
>          drain: [Array],
>          timeout: [Function: socketOnTimeout],
>          data: [Function: bound socketOnData],
>          close: [Array],
>          resume: [Function: onSocketResume],
>          pause: [Function: onSocketPause],
>          error: [Function: noop] },
>       _eventsCount: 8,
>       _maxListeners: undefined,
>       _writableState:
>        WritableState {
>          objectMode: false,
>          highWaterMark: 16384,
>          finalCalled: false,
>          needDrain: false,
>          ending: false,
>          ended: false,
>          finished: false,
>          destroyed: true,
>          decodeStrings: false,
>          defaultEncoding: 'utf8',
>          length: 0,
>          writing: false,
>          corked: 0,
>          sync: false,
>          bufferProcessing: false,
>          onwrite: [Function: bound onwrite],
>          writecb: null,
>          writelen: 0,
>          bufferedRequest: null,
>          lastBufferedRequest: null,
>          pendingcb: 0,
>          prefinished: false,
>          errorEmitted: true,
>          emitClose: false,
>          autoDestroy: false,
>          bufferedRequestCount: 0,
>          corkedRequestsFree: [Object] },
>       writable: false,
>       allowHalfOpen: true,
>       _sockname: null,
>       _pendingData: null,
>       _pendingEncoding: '',
>       server:
>        Server {
>          _events: [Object],
>          _eventsCount: 2,
>          _maxListeners: undefined,
>          _connections: 0,
>          _handle: [Pipe],
>          _usingWorkers: false,
>          _workers: [],
>          _unref: false,
>          allowHalfOpen: true,
>          pauseOnConnect: false,
>          httpAllowHalfOpen: false,
>          timeout: 120000,
>          keepAliveTimeout: 5000,
>          maxHeadersCount: null,
>          headersTimeout: 40000,
>          _pipeName:
>           '/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock',
>          _connectionKey:
>           '-1:/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock:-1',
>          [Symbol(IncomingMessage)]: [Function],
>          [Symbol(ServerResponse)]: [Function],
>          [Symbol(asyncId)]: 15 },
>       _server:
>        Server {
>          _events: [Object],
>          _eventsCount: 2,
>          _maxListeners: undefined,
>          _connections: 0,
>          _handle: [Pipe],
>          _usingWorkers: false,
>          _workers: [],
>          _unref: false,
>          allowHalfOpen: true,
>          pauseOnConnect: false,
>          httpAllowHalfOpen: false,
>          timeout: 120000,
>          keepAliveTimeout: 5000,
>          maxHeadersCount: null,
>          headersTimeout: 40000,
>          _pipeName:
>           '/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock',
>          _connectionKey:
>           '-1:/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock:-1',
>          [Symbol(IncomingMessage)]: [Function],
>          [Symbol(ServerResponse)]: [Function],
>          [Symbol(asyncId)]: 15 },
>       timeout: 120000,
>       parser: null,
>       on: [Function: socketOnWrap],
>       _paused: false,
>       _httpMessage:
>        ServerResponse {
>          _events: [Object],
>          _eventsCount: 1,
>          _maxListeners: undefined,
>          output: [],
>          outputEncodings: [],
>          outputCallbacks: [],
>          outputSize: 0,
>          writable: true,
>          _last: false,
>          chunkedEncoding: false,
>          shouldKeepAlive: true,
>          useChunkedEncodingByDefault: true,
>          sendDate: true,
>          _removedConnection: false,
>          _removedContLen: false,
>          _removedTE: false,
>          _contentLength: null,
>          _hasBody: true,
>          _trailer: '',
>          finished: false,
>          _headerSent: false,
>          socket: [Circular],
>          connection: [Circular],
>          _header: null,
>          _onPendingData: [Function: bound updateOutgoingData],
>          _sent100: false,
>          _expect_continue: false,
>          req: [Circular],
>          locals: [Object: null prototype] {},
>          [Symbol(isCorked)]: false,
>          [Symbol(outHeadersKey)]: [Object] },
>       [Symbol(asyncId)]: 18,
>       [Symbol(lastWriteQueueSize)]: 0,
>       [Symbol(timeout)]:
>        Timeout {
>          _called: false,
>          _idleTimeout: -1,
>          _idlePrev: null,
>          _idleNext: null,
>          _idleStart: 1525,
>          _onTimeout: null,
>          _timerArgs: undefined,
>          _repeat: null,
>          _destroyed: false,
>          [Symbol(unrefed)]: true,
>          [Symbol(asyncId)]: 19,
>          [Symbol(triggerId)]: 18 },
>       [Symbol(kBytesRead)]: 147456,
>       [Symbol(kBytesWritten)]: 47 },
>    httpVersionMajor: 1,
>    httpVersionMinor: 1,
>    httpVersion: '1.1',
>    complete: true,
>    headers:
>     { 'content-type':
>        'multipart/form-data; boundary=--------------------------287084099110881836222359',
>       authorization:
>        'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4NDI1Zjk0YmVlMWU0N2YxNGQ3OWZhYmQ4MTIyNTRiMWJmOTE4YzAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsLWFwcC1jMjY3MSIsImF1ZCI6InNvY2lhbC1hcHAtYzI2NzEiLCJhdXRoX3RpbWUiOjE1Njc2NzU4NDgsInVzZXJfaWQiOiJ3QmN2b25OanFmUzY2aE1TcmNCQ3N0Q055ekIyIiwic3ViIjoid0Jjdm9uTmpxZlM2NmhNU3JjQkNzdENOeXpCMiIsImlhdCI6MTU2NzY3NTg0OCwiZXhwIjoxNTY3Njc5NDQ4LCJlbWFpbCI6ImxhdGVzdEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibGF0ZXN0QGVtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.RU9BFVFLgl9ByAy6rmgwvt_9bc6YVOfW9aPA2hZRhRENC05lTBIyKvb8ESfe7Fqa_kFfhaGIKUE-XfbOMivXOyV-ELu29WyIWJ-jqZuQcGDzqDGCx6uXJdVuAMudZkuYOrye2wnr6OATMiUMDdUeUEh6tkCjIsFt39Rsni6Fs1n6KKVqu7IKa58Q8zKg3V8KVqTfjeT3qB_PZdAehpRiwN7Lb2Pp0yhKTVPMVwYdjjzO84eX2thQyZNdKzBWAWs5o3T91dIfKQWoPm-UNKlB2YZjjs9F_y42Mk-S_ZaFd9YcLFSfK5VbXw_aymem5V0SLfP2m_gal_HAZFmUCP4akQ',
>       'user-agent': 'PostmanRuntime/7.16.3',
>       accept: '*/*',
>       'cache-control': 'no-cache',
>       'postman-token': 'c9631dba-b4c5-4d8b-9633-f2a47fbce55d',
>       host: 'localhost:5001',
>       'accept-encoding': 'gzip, deflate',
>       'content-length': '143037',
>       connection: 'keep-alive' },
>    rawHeaders:
>     [ 'content-type',
>       'multipart/form-data; boundary=--------------------------287084099110881836222359',
>       'authorization',
>       'Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImM4NDI1Zjk0YmVlMWU0N2YxNGQ3OWZhYmQ4MTIyNTRiMWJmOTE4YzAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc29jaWFsLWFwcC1jMjY3MSIsImF1ZCI6InNvY2lhbC1hcHAtYzI2NzEiLCJhdXRoX3RpbWUiOjE1Njc2NzU4NDgsInVzZXJfaWQiOiJ3QmN2b25OanFmUzY2aE1TcmNCQ3N0Q055ekIyIiwic3ViIjoid0Jjdm9uTmpxZlM2NmhNU3JjQkNzdENOeXpCMiIsImlhdCI6MTU2NzY3NTg0OCwiZXhwIjoxNTY3Njc5NDQ4LCJlbWFpbCI6ImxhdGVzdEBlbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibGF0ZXN0QGVtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.RU9BFVFLgl9ByAy6rmgwvt_9bc6YVOfW9aPA2hZRhRENC05lTBIyKvb8ESfe7Fqa_kFfhaGIKUE-XfbOMivXOyV-ELu29WyIWJ-jqZuQcGDzqDGCx6uXJdVuAMudZkuYOrye2wnr6OATMiUMDdUeUEh6tkCjIsFt39Rsni6Fs1n6KKVqu7IKa58Q8zKg3V8KVqTfjeT3qB_PZdAehpRiwN7Lb2Pp0yhKTVPMVwYdjjzO84eX2thQyZNdKzBWAWs5o3T91dIfKQWoPm-UNKlB2YZjjs9F_y42Mk-S_ZaFd9YcLFSfK5VbXw_aymem5V0SLfP2m_gal_HAZFmUCP4akQ',
>       'user-agent',
>       'PostmanRuntime/7.16.3',
>       'accept',
>       '*/*',
>       'cache-control',
>       'no-cache',
>       'postman-token',
>       'c9631dba-b4c5-4d8b-9633-f2a47fbce55d',
>       'host',
>       'localhost:5001',
>       'accept-encoding',
>       'gzip, deflate',
>       'content-length',
>       '143037',
>       'connection',
>       'keep-alive' ],
>    trailers: {},
>    rawTrailers: [],
>    aborted: true,
>    upgrade: false,
>    url: '/user/image',
>    method: 'POST',
>    statusCode: null,
>    statusMessage: null,
>    client:
>     Socket {
>       connecting: false,
>       _hadError: false,
>       _handle: null,
>       _parent: null,
>       _host: null,
>       _readableState:
>        ReadableState {
>          objectMode: false,
>          highWaterMark: 16384,
>          buffer: BufferList { head: null, tail: null, length: 0 },
>          length: 0,
>          pipes: null,
>          pipesCount: 0,
>          flowing: true,
>          ended: false,
>          endEmitted: false,
>          reading: true,
>          sync: false,
>          needReadable: true,
>          emittedReadable: false,
>          readableListening: false,
>          resumeScheduled: false,
>          paused: false,
>          emitClose: false,
>          autoDestroy: false,
>          destroyed: true,
>          defaultEncoding: 'utf8',
>          awaitDrain: 0,
>          readingMore: false,
>          decoder: null,
>          encoding: null },
>       readable: false,
>       _events:
>        [Object: null prototype] {
>          end: [Array],
>          drain: [Array],
>          timeout: [Function: socketOnTimeout],
>          data: [Function: bound socketOnData],
>          close: [Array],
>          resume: [Function: onSocketResume],
>          pause: [Function: onSocketPause],
>          error: [Function: noop] },
>       _eventsCount: 8,
>       _maxListeners: undefined,
>       _writableState:
>        WritableState {
>          objectMode: false,
>          highWaterMark: 16384,
>          finalCalled: false,
>          needDrain: false,
>          ending: false,
>          ended: false,
>          finished: false,
>          destroyed: true,
>          decodeStrings: false,
>          defaultEncoding: 'utf8',
>          length: 0,
>          writing: false,
>          corked: 0,
>          sync: false,
>          bufferProcessing: false,
>          onwrite: [Function: bound onwrite],
>          writecb: null,
>          writelen: 0,
>          bufferedRequest: null,
>          lastBufferedRequest: null,
>          pendingcb: 0,
>          prefinished: false,
>          errorEmitted: true,
>          emitClose: false,
>          autoDestroy: false,
>          bufferedRequestCount: 0,
>          corkedRequestsFree: [Object] },
>       writable: false,
>       allowHalfOpen: true,
>       _sockname: null,
>       _pendingData: null,
>       _pendingEncoding: '',
>       server:
>        Server {
>          _events: [Object],
>          _eventsCount: 2,
>          _maxListeners: undefined,
>          _connections: 0,
>          _handle: [Pipe],
>          _usingWorkers: false,
>          _workers: [],
>          _unref: false,
>          allowHalfOpen: true,
>          pauseOnConnect: false,
>          httpAllowHalfOpen: false,
>          timeout: 120000,
>          keepAliveTimeout: 5000,
>          maxHeadersCount: null,
>          headersTimeout: 40000,
>          _pipeName:
>           '/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock',
>          _connectionKey:
>           '-1:/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock:-1',
>          [Symbol(IncomingMessage)]: [Function],
>          [Symbol(ServerResponse)]: [Function],
>          [Symbol(asyncId)]: 15 },
>       _server:
>        Server {
>          _events: [Object],
>          _eventsCount: 2,
>          _maxListeners: undefined,
>          _connections: 0,
>          _handle: [Pipe],
>          _usingWorkers: false,
>          _workers: [],
>          _unref: false,
>          allowHalfOpen: true,
>          pauseOnConnect: false,
>          httpAllowHalfOpen: false,
>          timeout: 120000,
>          keepAliveTimeout: 5000,
>          maxHeadersCount: null,
>          headersTimeout: 40000,
>          _pipeName:
>           '/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock',
>          _connectionKey:
>           '-1:/var/folders/63/yw229ch14pv_k8l7rg2frf5m0000gn/T/firebase_emulator_invocation_2511.sock:-1',
>          [Symbol(IncomingMessage)]: [Function],
>          [Symbol(ServerResponse)]: [Function],
>          [Symbol(asyncId)]: 15 },
>       timeout: 120000,
>       parser: null,
>       on: [Function: socketOnWrap],
>       _paused: false,
>       _httpMessage:
>        ServerResponse {
>          _events: [Object],
>          _eventsCount: 1,
>          _maxListeners: undefined,
>          output: [],
>          outputEncodings: [],
>          outputCallbacks: [],
>          outputSize: 0,
>          writable: true,
>          _last: false,
>          chunkedEncoding: false,
>          shouldKeepAlive: true,
>          useChunkedEncodingByDefault: true,
>          sendDate: true,
>          _removedConnection: false,
>          _removedContLen: false,
>          _removedTE: false,
>          _contentLength: null,
>          _hasBody: true,
>          _trailer: '',
>          finished: false,
>          _headerSent: false,
>          socket: [Circular],
>          connection: [Circular],
>          _header: null,
>          _onPendingData: [Function: bound updateOutgoingData],
>          _sent100: false,
>          _expect_continue: false,
>          req: [Circular],
>          locals: [Object: null prototype] {},
>          [Symbol(isCorked)]: false,
>          [Symbol(outHeadersKey)]: [Object] },
>       [Symbol(asyncId)]: 18,
>       [Symbol(lastWriteQueueSize)]: 0,
>       [Symbol(timeout)]:
>        Timeout {
>          _called: false,
>          _idleTimeout: -1,
>          _idlePrev: null,
>          _idleNext: null,
>          _idleStart: 1525,
>          _onTimeout: null,
>          _timerArgs: undefined,
>          _repeat: null,
>          _destroyed: false,
>          [Symbol(unrefed)]: true,
>          [Symbol(asyncId)]: 19,
>          [Symbol(triggerId)]: 18 },
>       [Symbol(kBytesRead)]: 147456,
>       [Symbol(kBytesWritten)]: 47 },
>    _consuming: true,
>    _dumped: false,
>    next: [Function: next],
>    baseUrl: '',
>    originalUrl: '/user/image',
>    _parsedUrl:
>     Url {
>       protocol: null,
>       slashes: null,
>       auth: null,
>       host: null,
>       port: null,
>       hostname: null,
>       hash: null,
>       search: null,
>       query: null,
>       pathname: '/user/image',
>       path: '/user/image',
>       href: '/user/image',
>       _raw: '/user/image' },
>    params: {},
>    query: {},
>    res:
>     ServerResponse {
>       _events: [Object: null prototype] { finish: [Array] },
>       _eventsCount: 1,
>       _maxListeners: undefined,
>       output: [],
>       outputEncodings: [],
>       outputCallbacks: [],
>       outputSize: 0,
>       writable: true,
>       _last: false,
>       chunkedEncoding: false,
>       shouldKeepAlive: true,
>       useChunkedEncodingByDefault: true,
>       sendDate: true,
>       _removedConnection: false,
>       _removedContLen: false,
>       _removedTE: false,
>       _contentLength: null,
>       _hasBody: true,
>       _trailer: '',
>       finished: false,
>       _headerSent: false,
>       socket:
>        Socket {
>          connecting: false,
>          _hadError: false,
>          _handle: null,
>          _parent: null,
>          _host: null,
>          _readableState: [ReadableState],
>          readable: false,
>          _events: [Object],
>          _eventsCount: 8,
>          _maxListeners: undefined,
>          _writableState: [WritableState],
>          writable: false,
>          allowHalfOpen: true,
>          _sockname: null,
>          _pendingData: null,
>          _pendingEncoding: '',
>          server: [Server],
>          _server: [Server],
>          timeout: 120000,
>          parser: null,
>          on: [Function: socketOnWrap],
>          _paused: false,
>          _httpMessage: [Circular],
>          [Symbol(asyncId)]: 18,
>          [Symbol(lastWriteQueueSize)]: 0,
>          [Symbol(timeout)]:
>           Timeout {
>             _called: false,
>             _idleTimeout: -1,
>             _idlePrev: null,
>             _idleNext: null,
>             _idleStart: 1525,
>             _onTimeout: null,
>             _timerArgs: undefined,
>             _repeat: null,
>             _destroyed: false,
>             [Symbol(unrefed)]: true,
>             [Symbol(asyncId)]: 19,
>             [Symbol(triggerId)]: 18 },
>          [Symbol(kBytesRead)]: 147456,
>          [Symbol(kBytesWritten)]: 47 },
>       connection:
>        Socket {
>          connecting: false,
>          _hadError: false,
>          _handle: null,
>          _parent: null,
>          _host: null,
>          _readableState: [ReadableState],
>          readable: false,
>          _events: [Object],
>          _eventsCount: 8,
>          _maxListeners: undefined,
>          _writableState: [WritableState],
>          writable: false,
>          allowHalfOpen: true,
>          _sockname: null,
>          _pendingData: null,
>          _pendingEncoding: '',
>          server: [Server],
>          _server: [Server],
>          timeout: 120000,
>          parser: null,
>          on: [Function: socketOnWrap],
>          _paused: false,
>          _httpMessage: [Circular],
>          [Symbol(asyncId)]: 18,
>          [Symbol(lastWriteQueueSize)]: 0,
>          [Symbol(timeout)]:
>           Timeout {
>             _called: false,
>             _idleTimeout: -1,
>             _idlePrev: null,
>             _idleNext: null,
>             _idleStart: 1525,
>             _onTimeout: null,
>             _timerArgs: undefined,
>             _repeat: null,
>             _destroyed: false,
>             [Symbol(unrefed)]: true,
>             [Symbol(asyncId)]: 19,
>             [Symbol(triggerId)]: 18 },
>          [Symbol(kBytesRead)]: 147456,
>          [Symbol(kBytesWritten)]: 47 },
>       _header: null,
>       _onPendingData: [Function: bound updateOutgoingData],
>       _sent100: false,
>       _expect_continue: false,
>       req: [Circular],
>       locals: [Object: null prototype] {},
>       [Symbol(isCorked)]: false,
>       [Symbol(outHeadersKey)]: [Object: null prototype] { 'x-powered-by': [Array] } },
>    body:
>     <Buffer 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 32 38 37 30 38 34 30 39 39 31 31 30 38 38 31 38 33 36 32 32 32 33 ... >,
>    _body: true,
>    length: undefined,
>    route:
>     Route {
>       path: '/user/image',
>       stack: [ [Layer], [Layer] ],
>       methods: { post: true } },
>    user:
>     { iss: 'https://securetoken.google.com/social-app-c2671',
>       aud: 'social-app-c2671',
>       auth_time: 1567675848,
>       user_id: 'wBcvonNjqfS66hMSrcBCstCNyzB2',
>       sub: 'wBcvonNjqfS66hMSrcBCstCNyzB2',
>       iat: 1567675848,
>       exp: 1567679448,
>       email: 'latest@email.com',
>       email_verified: false,
>       firebase: { identities: [Object], sign_in_provider: 'password' },
>       uid: 'wBcvonNjqfS66hMSrcBCstCNyzB2',
>       handle: 'LatestUser' } }`

**Comment by mscdex** [comment]
Perhaps this is the same issue as https://github.com/mscdex/busboy/issues/208 ?

**Comment by Oner-T** [comment]
unbelievable... yes, same problem and I fixed it with that solution. many thanks
