### ISSUE TITLE
Reading the stream outside of the 'file' event

### ISSUE THREAD

**Issue by darrenrahnemoon** [mscdex/busboy#217]
Is there a way to read the stream outside of the 'file' event? 
I would like to do some validation before I read the file stream but the validation is somewhere outside of busboy's scope.
For some reason I can't pipe the stream. It returns blank, whereas inside the event receiver it works fine. 
What I got so far is that I save it to tempdir, do my validation, if I don't want it I'd delete it, if I want it, move it outside of tempdir.

**Comment by mscdex** [comment]
Perhaps you should show a simple example of what you have tried.

If you are performing validation based other, non-file fields and you're in control of the form, you should reorder the form before submission (this is a lot easier via xhr).
