### ISSUE TITLE
Duplicate file names.

### ISSUE THREAD

**Issue by danhumphrey** [mscdex/busboy#218]
Hi,

Assuming I have an inline image in my email (image001.jpg) and an attachment (image001.jpg) how can I differentiate between the two?

`busboy.on("file"...` provides the fieldname of `attachment-1` and `attachment-2` and each file has a different number of bytes, but how do I tell programatically which file was inline, and which was attached to the email?

It would be ideal if the `on("file"...` handler specified/identified the source of the file.... or is there another way?

Thanks,
Dan

**Comment by danhumphrey** [comment]
Thanks for your quick response. Although I am parsing a web form, it's sent from a third party and was originally parsed from an email.

I will look into dicer as you suggest.

Thanks again!

**Comment by jh-pu** [comment]
Hi,  @mscdex 

This is another issue as below, under the `on("header"...`event there will call method `parseParams` which request header contains `content-disposition`. 
`"form-data; name="my_file.csv"; filename="Uodacæµä¸»è§æç»æè¡æ¦ (4).csv"; filename*="UTF-8''Uodac%E6%B5%8B%E4%B8%BB%E8%A7%82%E6%9C%80%E7%BB%88%E6%8E%92%E8%A1%8C%E6%A6%9C%20%284%29.csv""`
They will parse 2 fields both named `filename`. 
Here's the code: 
https://github.com/mscdex/busboy/blob/master/lib/types/multipart.js#L151-L162
The first value `filename` will be covered by the second, I can understand it coz the second has the encoding 'UTF-8'. But it will decode twice, the first in `parseParams` it will parse to correct such as 'A->a', but the second will decode back -> 'a->A' which we need 'a' actually.

Why need another decoding step? 
Thanks!

**Comment by allenz8512** [comment]
I found this problem too.
For compatibility reason many http client(like Postman) send two filename params('filename' and 'filename*') in content-disposition，busboy parse the charset correctly but doesn't decode the 'filename*' value using the charset

also see
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
https://tools.ietf.org/html/rfc6266

**Comment by mscdex** [comment]
FWIW `busboy` v1.0.0 will prefer the encoded filename variant if it's available.
