### ISSUE TITLE
Somewhere busboy/deps/encoding/encoding.js is accessing emailjs-stringencoding 1.0.0

### ISSUE THREAD

**Issue by siva-srini** [mscdex/busboy#221]
Based on [NIQS report](https://www.sonatype.com/nexus-iq-server), the mentioned file is shown as accessing [emailjs-stringencoding 1.0.0](https://www.npmjs.com/package/emailjs-stringencoding) which does not have license.  Have reached out to them about that.  However, looks like it is deprecated.  Is it possible to use different library/dependency for busboy. The version we are facing issue is busboy@0.2.14 which is the version used by multer@1.4.2

**Comment by charmander** [comment]
Their shared code comes from https://github.com/inexorabletash/text-encoding/blob/master/lib/encoding.js and is licensed according to the file header in busboy:

https://github.com/mscdex/busboy/blob/5ef3f9b1d08e7ccb7c9b3690e4c071089e66285c/deps/encoding/encoding.js#L1-L38

False positive.

**Comment by mscdex** [comment]
`busboy` v1.0.0 will no longer use the third-party text decoding library, so it's even less of an issue.
