### ISSUE TITLE
Using deprecated Buffer constructor, which results in errors

### ISSUE THREAD

**Issue by krizzje** [mscdex/busboy#222]
The busboy library uses the new Buffer(...) construction, which is deprecated, and results in this error message using node v13.5.0:

```[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.```

**Comment by hubgit** [comment]
It looks like this was fixed in https://github.com/mscdex/busboy/commit/db9b25f2b88fd4689d78d74b1fdc9de7f10d5f3d
