### ISSUE TITLE
file end event and stream write close event are not in sync.

### ISSUE THREAD

**Issue by DungeonMasterAkshay** [mscdex/busboy#225]
Busboy finish event should trigger only when stream write close event(for single and multiple files) completed.

```js
import express from 'express'
import fs from 'fs'
import  path from 'path'
import Busboy from 'busboy'
let app = new express()

app.post('/api/upload_video',(req,res) =>{
    var busboy = new Busboy({ headers: req.headers });
    let size = 0
    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      var saveTo = path.join(path.join("C:\\Users\\Akshay\\Desktop\\oops_nodesj\\" +Date.now() +".mp4"));
      let ws  = fs.createWriteStream(saveTo)
      
    file.on('end',() => {
        console.log('read end')
      })

    ws.on('open',() => {
        console.log('wd - open')
        file.pipe(ws)
      })

    ws.on('close',() => {
          size = ws.bytesWritten
          console.log(size)
          //res.send("That's all folks!")
      })
});
 
 busboy.on('finish', function() {
        console.log('read finish')
      res.writeHead(200, { 'Connection': 'close' });
      res.end("That's all folks!");
    });


    req.pipe(busboy);
})


app.listen('3000',() => {
    console.log('HellYeah')
})
```

**OUTPUT :** 
```
HellYeah
wd - open
read end
read finish
Object {}
46675770
```

**Comment by mscdex** [comment]
`busboy` emits `'finish'` once all of the data for the entire form has been consumed (including every separate stream emitted in `'file'`). However, it has no knowledge of *what* consumed it, so it's impossible for it to wait for `ws` to finish sending the last chunk to the operating system and close its file descriptor.

**Comment by DungeonMasterAkshay** [comment]
Actually i want to get size of file(for single and multiple upload).
So that I can calculate byteswritten.

But tried this code for file size(Added to above code).

    file.on('end',() => {
        console.log('read end')
        console.log(file.bytesRead)
      })

Output (But I am getting undefined.)
HellYeah
wd - open
read end
**undefined**
read finish
46675770

**Comment by mscdex** [comment]
There is no `bytesRead` for plain streams, you're probably thinking of sockets in node core or something else that adds that property. If you want that information you'd need to set up a counter yourself.

**Comment by DungeonMasterAkshay** [comment]
I find a solution after on file.end event -- > let t = fs.statSync(<file with complete disk path>)

**Comment by mscdex** [comment]
If you're writing the file to disk (via `fs.createWriteStream()`), then the `fs.WriteStream` from node should have a `bytesWritten` property that you should be able to use.

**Comment by Martin-Luther** [comment]
```javascript
file.on('end',() => {
    console.log('read end');
    console.log(this._dataLen); // ???
})
```
