### ISSUE TITLE
Uploading Large Files (~100MBs) issue | Port forwarding

### ISSUE THREAD

**Issue by mustafalii** [mscdex/busboy#232]
I am trying to upload a couple of ~100MB image files from my react front end to node.js, express backend. After struggling with the same issue using Multer, I decided to use busboy but unfortunately still haven't solved my problem. 

My application is running perfectly on my local windows machine. However, after I set up my node backend on a personal linux server, and use ssh port forwarding to communicate with the backend, the files take forever to upload and the request eventually times out. Although, small files (a few MBs) still upload perfectly in any case. 
Here is my relevant server side code:

```
// Post request to /upload to handle detection of cards
router.post('/', async (req, res) => {

    var files = 0, finished = false;
    req.busboy.on('file', function (fieldname, file, filename) {
        console.log("Begin uploading: " + filename);
        ++files;
        const uploadPath = path.join(__dirname, "public", "images", "scannedCards", filename);
        let fstream = fs.createWriteStream(uploadPath);
        file.pipe(fstream);

        // On finish of file upload
        fstream.on('close', function () {
            --files;
            console.log(`(on close) Upload of '${filename}' finished`);
            console.log("(on close) # Files Left: ", files);

            if (files === 0 && finished) {
                console.log("(on close) ALL UPLOADING FINISHED");
                runPythonScript((slotLetter, detectedCards) => {
                    console.log(slotLetter, detectedCards);
                    res.send({
                        files: detectedCards,
                        slotLetter: slotLetter
                    });
                    fsExtra.emptyDirSync(path.join(__dirname, 'public', 'images', 'scannedCards'));
                });
            }
        });

    });

    req.busboy.on('finish', function () {
        console.log("Busyboy finish called");
        finished = true;
    });

    req.pipe(req.busboy);
});
```

Since the app is running fine locally, could this be an issue specific to the ssh port forwarding? Am I missing anything in the code? I also tried setting some values for highWaterMark and fileHwm, but with no luck.
I've been on this for a few days and just can't see what I'm missing. Any help would be highly appreciated. Thanks!

(Also, please excuse my unconventional way of waiting for all files to be uploaded)

**Comment by mscdex** [comment]
I don't see anything particularly wrong with the code.

**Comment by mustafalii** [comment]
@mscdex Yep, it runs with no issues locally. Do you think this might be specific to the port forwarding aspect? Any ideas on what I could try?

**Comment by mscdex** [comment]
You could just temporarily do:

```js
//req.pipe(req.busboy);
req.on('data', (chunk) => {
  chunk = chunk.toString('latin1');
  console.log('req data:');
  console.dir(chunk);
}).on('end', () => {
  console.log('req end');
});
```

and see if the end of the request comes and if you see the ending boundary (should look like a normal part boundary but ends with a `--`) in the last chunk.
