### ISSUE TITLE
Enhancement: Detect mime type from file content

### ISSUE THREAD

**Issue by armand1m** [mscdex/busboy#236]
Currently, the mime type returned relies on setting the `Content-Type` header for each file in a multipart request, otherwise, it defaults to `text/plain` or `application/octet-stream`.

However, this does not guarantee that the file is actually of that mime-type. 
For example, one could easily write a random file in a text format and upload it as an mp3 file doing something like this: 

`curl -v -F "file=@./fake-mp3.mp3;type=audio/mpeg" http://localhost:3000/upload`

#51 was related to this in some way, I believe.

Would be awesome if this could be detected from the content of the file itself. Using https://github.com/sindresorhus/file-type makes this a breeze.

This could also be shipped as a constructor config property.

I'd be willing to open a PR with this feature if the maintainers are interested.

**Comment by mscdex** [comment]
This is sort of thing is outside the scope of this module. This module generally just follows the specification(s) as far as default values go for mime type, encoding, etc.. Besides, even most content inspection methods can be fooled as they are not thorough enough or cover enough file formats.

Lastly I should add that it's not just the mime type that could be a potential issue, I would say *all* parts of the user input should not be trusted. Malicious file paths could be inserted into the filename, malware could be inserted into the content, etc.. This is a general programming philosophy about user input that most developers should heed.

**Comment by armand1m** [comment]
Thanks for the explanation and I agree with everything you just said. Thanks for maintaining this module and for your contributions 🙂
