### ISSUE TITLE
simultaneously encryption and upload file to server?

### ISSUE THREAD

**Issue by akshaybhuradia2020** [mscdex/busboy#240]
I need to do encryption as well on uploaded file. As user upload file, encryption also done parallelly. anyone can give suggestion.
what is best practice for this use case?

**Comment by mscdex** [comment]
General programming questions like this be posted to [stackoverflow.com](https://stackoverflow.com/) or the [nodejs/help repo](https://github.com/nodejs/help/issues) instead of this issue tracker.
