### ISSUE TITLE
Support for other multipart formats

### ISSUE THREAD

**Issue by mielp** [mscdex/busboy#249]
Hi,

The `Multipart` format only parses `multipart/form-data` requests. I am being tasked to interpret other multipart formats (namely, `multipart/mixed`), and was wondering if there was a way to extend busboy to support these other formats.

Thanks for your help! 😃

**Comment by mscdex** [comment]
As far as multipart formats go, this module is focused on multipart/form-data only. If you want to handle other kinds of multipart formats, you could use `dicer` (the module that `busboy` uses internally for parsing multipart forms) directly.
