### ISSUE TITLE
No more "file" events when fileHwm is hit

### ISSUE THREAD

**Issue by silverwind** [mscdex/busboy#25]
Hey, I was debugging an issue which was caused by uploading ~750 Files at once, and noticed that for some strange reason, I wasn't getting any more "file" events on seemingly random times during the transfer, and the upload would freeze in turn. I was uploading the same folder (recursively) over and over, and on rare occasion, it even finished.

For now, I've increased the fileHwm to 1Mb which seemed to have eliminated the issue, but I'm not sure, if that's the right approach to this, or if I may have uncovered a bug in this module.

Also to note, the issue really looks like it's related to the amount of files here, as I can upload a 10GB single file just fine.

**Comment by mscdex** [comment]
@silverwind Are you still encountering this problem?

**Comment by mscdex** [comment]
If you can provide a minimal reproduction against the current master branch, let me know.
