### ISSUE TITLE
Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by Sushant-Keny** [mscdex/busboy#251]
I have created a function to parse the multipart/form-data.

```
export function parseMultipartFormData(event) {
  return new Promise((resolve, reject) => {
    const busboy = new Busboy({
      headers: {
        'content-type': event.headers['Content-Type'],
      },
    });

    const body = {};

    busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
      body.filename = filename;
      body.encoding = encoding;
      body.mimetype = mimetype;

      const buffer = [];

      file
        .on('data', (chunk) => {
          buffer.push(chunk);
        })
        .on('end', () => {
          body.documentContent = Buffer.concat(buffer);
        });
    })
      .on('field', (fieldname, val) => {
        body[fieldname] = val;
      })
      .on('finish', () => {
        resolve(body);
      })
      .on('error', (err) => {
        reject(err);
      });

    busboy.end(event.body);
  });
}

```

When I execute this function I am getting a warning,

`(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

Currently I am using the version `^0.3.1`

Could you please suggest me how to solve it? I have tried using a stream directly still I'm getting this warning.

**Comment by charmander** [comment]
#223

**Comment by kibertoad** [comment]
This was fixed in https://github.com/fastify/busboy

**Comment by mscdex** [comment]
This is now solved in two ways:

* `dicer` has updated its dependency on `streamsearch`
* `busboy` v1.0.0 will no longer depend on `dicer`
