### ISSUE TITLE
Busboy with AWS Lambda function

### ISSUE THREAD

**Issue by Sushant-Keny** [mscdex/busboy#252]
Hi Everyone,

I am trying to use busboy to parse multipart/form-data coming from AWS API Gateway to AWS Lambda. I have used LAMBDA_PROXY integration.

My parser is as follows:

```
export function parseMultipartFormData(event) {
  return new Promise((resolve, reject) => {
    const busboy = new Busboy({
      headers: {
        'content-type': event.headers['Content-Type'],
      },
    });

    const body = {};
    let buffer = '';

    busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
      body.filename = filename;
      body.encoding = encoding;
      body.mimetype = mimetype;

      file.setEncoding('base64');

      file.on('data', (chunk) => {
        buffer += chunk;
      });

      file.once('end', () => {
        body.documentContent = buffer;
      });
    })
      .on('field', (fieldname, val) => {
        body[fieldname] = val;
      })
      .on('finish', () => {
        resolve(body);
      })
      .on('error', (err) => {
        reject(err);
      });

    busboy.end(event.body);
  });
}
```

Parser is working fine for fields. When I upload a .pdf file it gets corrupted.
So I checked the same file's base_64 encoded string on my local machine using this block of code:

```
const fs = require('fs');
const { Buffer } = require('buffer');
const path = require('path');

const stream = fs.createReadStream(path.join(__dirname, 'file.pdf'));

let buffer = '';

stream.setEncoding('base64');

stream.on('data', (chunk) => {
  buffer += chunk;
});

stream.on('end', () => {
  console.log(buffer);
});
```

Then I compared the base_64 encoded string with the string generated by busboy parser and somehow that string is not matching for the same file and encoding.

Is there anything wrong with using busboy with lambda? Or something is wrong in my integration?

**Comment by Sushant-Keny** [comment]
No, that's not encoded.

But I also tried using `Buffer.concat()`

```
export function parseMultipartFormData(event) {
  return new Promise((resolve, reject) => {
    const busboy = new Busboy({
      headers: {
        'content-type': event.headers['Content-Type'],
      },
    });

    const body = {};
    const chunks = [];

    busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
      body.filename = filename;
      body.encoding = encoding;
      body.mimetype = mimetype;

      file.on('data', (chunk) => {
        chunks.push(chunk);
      });

      file.once('end', () => {
        body.documentContent = Buffer.concat(chunks);
      });
    })
      .on('field', (fieldname, val) => {
        body[fieldname] = val;
      })
      .on('finish', () => {
        resolve(body);
      })
      .on('error', (err) => {
        reject(err);
      });

    busboy.end(event.body);
  });
}
```

Same issue with this code.

**Comment by mscdex** [comment]
What is the value of `encoding` and `mimetype`?

If those values indicate binary data (e.g. `body.documentContent` does not contain a base64-encoded string, but actually raw bytes), what if you use `crypto` to create a sha1 hash of `body.documentContent` and compare that to the sha1 hash of the original file? Do those differ?

**Comment by Sushant-Keny** [comment]
Encoding is `7-bit`
Mimetype is `application/pdf`

![Logs](https://user-images.githubusercontent.com/71064169/132294869-08048cfa-f136-4a98-8476-b31c3350385d.png)


**Hash on Lambda**
```
busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
      file.on('readable', () => {
        let chunk;
        /* eslint-disable */
        while (null !== (chunk = file.read())) {
          console.log('Chunk', chunk);
          chunks.push(chunk);
        }
      });

      file.on('end', () => {
        content = chunks.join('');
        const buffer = content;
        const hash = crypto.createHash('sha1').update(buffer).digest('hex');
        console.log(hash);
      });
    })
```
Hash: `994bf10c1efe5b51a858fa7436cd65f98f317553`

**Hash on Local**

```
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const readable = fs.createReadStream(path.join(__dirname, 'Report.pdf'));

const chunks = [];
let buffer;

readable.on('readable', () => {
  let chunk;
  while (null !== (chunk = readable.read())) {
    chunks.push(chunk);
  }
});

readable.on('end', () => {
  buffer = chunks.join('');
  const hash = crypto.createHash('sha1').update(buffer).digest('hex');
  console.log(hash);
});

```
Hash: `51a955ac8d9272ea7fc4ea144de9488f67bc25a4`

The hash are not matching for the same file. Is there any problem with encoding?

**Comment by mscdex** [comment]
```js
content = chunks.join('');
```

needs to be

```js
content = Buffer.concat(chunks);
```

otherwise you're just converting to string again.

**Comment by mscdex** [comment]
Also just to be sure, is `event.body` raw bytes (e.g. a Buffer or typed array like a Uint8Array) or is it a string?

**Comment by Sushant-Keny** [comment]
Thanks for your support. The file size vary between S3 and local machine. On S3 its 22KB while on local machine the size of the original file is 15KB

**Comment by Sushant-Keny** [comment]
> Also just to be sure, is `event.body` raw bytes (e.g. a Buffer or typed array like a Uint8Array) or is it a string or something else?

Event body is base64 encoded string.

When I convert it into utf-8 it looks like this:

`"body": "----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"documentName\"\r\n\r\nReport-1\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"documentType\"\r\n\r\nReport for Risk Analysis\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"clientId\"\r\n\r\ne4db0c94f84467f3c4d6\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"clientName\"\r\n\r\nHDFC Bank\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"documentDescription\"\r\n\r\nRisk analysis report of John Doe\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"documentExtension\"\r\n\r\npdf\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"documentPk\"\r\n\r\nb4b6a8c598dafe0e0dda\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"uploadUserId\"\r\n\r\nfe47b8bcd5ac11c77102\r\n----------------------------740586622815871533210431\r\nContent-Disposition: form-data; name=\"sourceApp\"\r\n\r\nSP_Pro\r\n----------------------------740586622815871533210431--\r\n"`

**Comment by Sushant-Keny** [comment]
> ```js
> content = Buffer.concat(chunks);
> ```

Previously I was using `Buffer.concat` only but it didn't work

**Comment by mscdex** [comment]
If `event.body` is a base64-encoded string, then you need to either convert it to a Buffer first (from base64) and pass that to `busboy.end()` instead or pass the encoding as the second argument to `busboy.end()` so that Busboy can correctly deal with the actual raw, binary form data.

Also the file varying between S3 and your local machine sounds suspect. Maybe it did get corrupted during upload to S3 after all?

**Comment by mscdex** [comment]
> Previously I was using `Buffer.concat` but it didn't work

It is the correct way for buffering binary data though and will work for either text or non-text data.

**Comment by Sushant-Keny** [comment]
> If `event.body` is a base64-encoded string, then you need to either convert it to a Buffer first (from base64) and pass that to `busboy.end()` instead or pass the encoding (`'base64'`) as the second argument to `busboy.end()` so that Busboy can correctly deal with the actual raw, binary form data.
> 
> Also the file varying between S3 and your local machine sounds suspect. Maybe it did get corrupted during upload to S3 after all?

Thank you so much! This worked :)

Steps
- Add `multipart/form-data` to AWS API Gateway. Due to this API Gateway will look at the Content-Type and Accept HTTP headers to decide how to handle the body. In case of `multipart/form-data` it encodes the body into base64
- Add busboy parser as follows

```
export function parseMultipartFormData(event) {
  return new Promise((resolve, reject) => {
    const busboy = new Busboy({
      headers: {
        'content-type': event.headers['Content-Type'],
      },
    });

    const body = {};
    const chunks = [];

    busboy.on('file', (fieldname, file, filename, encoding, mimetype) => {
      body.filename = filename;
      body.encoding = encoding;
      body.mimetype = mimetype;

      file.on('readable', () => {
        let chunk;
        while (null !== (chunk = file.read())) {
          chunks.push(chunk);
        }
      });

      file.on('end', () => {
        body.documentContent = Buffer.concat(chunks);
      });
      .on('field', (fieldname, val) => {
        body[fieldname] = val;
      })
      .on('finish', () => {
        resolve(body);
      })
      .on('error', (err) => {
        reject(err);
      });

    busboy.end(event.body, 'base64');
  });
}

```
- AWS API Gateway has recently added the support to binary data and it requires specific way of passing the data (in our case it was `base64`) to work properly
- Hence when I added `busboy.end(event.body, 'base64')` it worked smoothly

Thanks for your support @mscdex. I'm so thankful to you and **busboy** community.

**Comment by kingcaubalejo** [comment]
How did you manage to solve this issue? I'm facing the same issue when I upload and check the file in S3 it is broken
