### ISSUE TITLE
busboy behind an nginx reverse proxy

### ISSUE THREAD

**Issue by soubhikchatterjee** [mscdex/busboy#254]
If I spin up a nodejs server and use busboy then I am able to upload large files (10+ gbs) but when i use the same nodejs code and use nginx as a reverse proxy then nginx throws "413 request entity too large"

I know this is related to nginx, but has anyone encountered such issue? How do we solve this? I know i can set a "client_max_body_size" variable but this would mean there will still be a hard limit of the file.

My nginx config looks like the following:

```

server {
  listen 80;
  server_name *.example.local;

  location /api {
    proxy_pass   http://host.docker.internal:5000;
    proxy_pass_header Accept;
    proxy_pass_header Server;
    keepalive_requests 1000;
    proxy_redirect off;
    proxy_buffering off;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header    X-Real-IP       $remote_addr;
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_connect_timeout       600;
    proxy_send_timeout          600;
    proxy_read_timeout          600;
    send_timeout                600;
    client_max_body_size        100M;
  }

}
```

**Comment by mscdex** [comment]
You'll probably be better off asking nginx questions on a place like serverfault.

**Comment by soubhikchatterjee** [comment]
Cool, thanks for your help
