### ISSUE TITLE
how to use await inside 

### ISSUE THREAD

**Issue by soubhikchatterjee** [mscdex/busboy#255]
Is there anyway i use async await as in the following code snippet?

```
busboy.on("file",  async (fieldname, file, filename, encoding, mimetype) => {
  const x = await User.findOne()
}))

```

**Comment by mscdex** [comment]
General questions like this are better suited for [stackoverflow](https://stackoverflow.com) or the [node.js/help repo](https://github.com/nodejs/help/issues).
