### ISSUE TITLE
Empty forms are not correctly handled

### ISSUE THREAD

**Issue by alonsohki** [mscdex/busboy#275]
When an empty form is sent to Busboy, it throws the following exception:
`Error: Unexpected end of form`

An empty form should be an acceptable valid state, and cause busboy to simply invoke the 'finish' callback.

Code to reproduce:
```js
import { PassThrough } from 'stream';
import FormData from 'form-data';
import Busboy from 'busboy';

const form = new FormData();
const busboy = Busboy({ headers: form.getHeaders() });

form.pipe(busboy);
new PassThrough().pipe(busboy);
```

**Comment by mscdex** [comment]
I'd argue that `form-data` should be emitting at least the end boundary marker.

When the end boundary marker is missing, it's almost always a data error (e.g. wrong boundary). In fact, issues where this was the case have been filed before, so having the error alerts you to that fact. If `busboy` ignored that, you would wonder why you never saw any data from your form.

**Comment by mscdex** [comment]
I should also add that browsers appear to always send the end boundary marker for empty forms. You can verify this (without `busboy`) with a form like:

```html
<html>
  <head></head>
  <body>
    <form method="POST" enctype="multipart/form-data"></form>
    <a href="#" onclick="document.forms[0].requestSubmit()">Submit</a>
  </body>
</html>
```

and then simply logging the raw request data on the server side.

**Comment by alonsohki** [comment]
Thanks for the feedback @mscdex . You are totally correct there, it seems that there's an issue with form-data.
