### ISSUE TITLE
on field and on file stopped working for no reason

### ISSUE THREAD

**Issue by 8483** [mscdex/busboy#281]
It worked yesterday, and now it stopped without any changes made to the code. What is going on?

**Client**

    async function uploadFile(file) {
        let formData = new FormData();

        formData.append("recordUid", recordUid);
        formData.append("fieldUid", fieldUid);
        formData.append("file", file);

        await fetchPostFormData("/api/files", formData);
    }

    async function fetchPostFormData(url, formData) {);
        try {
            let result = await (
                await fetch(url, {
                    method: "POST",
                    withCredentials: true,
                    credentials: "include",
                    headers: {
                        Authorization: localStorage.getItem("token"),
                    },
                    body: formData,
                })
            ).json();
    
            return result;
        } catch (err) {
            return err;
        }
    }

**Server**

    router.post("/api/files", async (req, res, next) => {
        try {
            console.log("starting upload..."); // <------------------- THIS ONE IS LOGGED
    
            let bb = busboy({
                headers: req.headers,
                limits: {
                    fileSize: 20 * 1024 * 1024, // 20 mb
                },
            });
    
            let fields = {};
    
            // Get any text values
            bb.on("field", (fieldname, val, fieldnameTruncated, valTruncated) => {

                console.log("on.field", fieldname, val); // <------------------ NOT FIRING

                fields[fieldname] = val;
            });
    
            bb.on("file", (fieldname, file, filename, encoding, mimetype) => {

                console.log("on.file"); // <----------------------------------- NOT FIRING
    
                let parts = filename.filename.split(".");
                let name = parts[0];
                let extension = parts[parts.length - 1];
    
                let finalName = `${+new Date()}-${name}.${extension}`;
                let filePath = `${filesFolderPath}${finalName}`;
    
                // Open writeable stream to path
                let writeStream = fs.createWriteStream(filePath);
    
                // Pipe the file to the opened stream
                file.pipe(writeStream);
    
                // Check for errors
                writeStream.on("error", (err) => {
                    console.log(err);
                });
    
                writeStream.on("close", async (err) => {
                    let sizeBytes = fs.statSync(filePath).size;
                });
            });
    
            bb.on("finish", () => {
                res.status(200).send({ success: true });
            });
        } catch (err) {
            next(err);
        }
    });

**Comment by mscdex** [comment]
Questions:

1. Node version?
2. `busboy` version?
3. What is in `req.headers['content-type']`?
4. Does it work without `limits` set?
5. Did you try logging the raw request data instead of piping to `busboy`? Is it properly formatted?

**Comment by 8483** [comment]
Managed to solve it @mscdex.

The problem was the missing `req.pipe(bb)` at the very end.

Can you please explain why this was the missing pieice? What does it do?

```
        // previous code... ^^^^^

        bb.on("finish", () => {
            res.status(200).send({ success: true });
        });

        req.pipe(bb)  // <------------- THIS RIGHT HERE

    } catch (err) {
        next(err);
    }
});
```

**Comment by mscdex** [comment]
[`pipe()`](https://nodejs.org/docs/latest/api/stream.html#readablepipedestination-options) is what hooks the streams together. Without it, you're not feeding `busboy` any data to parse.
