### ISSUE TITLE
Slow file upload to cloud storage

### ISSUE THREAD

**Issue by dev2k22** [mscdex/busboy#283]
FWIW, I have also posted this [issue ](https://github.com/googleapis/nodejs-storage/issues/1795) in NodeJS google storage issues as well under (Questions label), the purpose of asking this question here is to have my code inspected by maintainers of both NodeJS google storage APIs and busboy as well. 

**Problem**
For uploading video files (40 MB with 1920x1080 resolution), the average time it takes to upload video to GCP takes about 19 to 25 minutes with the best time (1182652.762 ms) which is quite slow. I am streaming upload directly to GCP storage without storing in temporary memory, similarly uploading pdf files (1700 KB) also takes 7-8 seconds as well. I am looking to optimize my code wrt performance as I think my code is not configured properly to upload videos or files for that matter.

**Code**
Here is the code I am using for uploading videos to GCP

```
try {
    const busboy = Busboy({
      headers: req.headers,
    });

    const { title } = req.query;

    let newVideo;

    busboy.on('file', (name, file, info) => {
      const { filename, encoding, mimeType } = info;
      console.log(
        `File [${name}]: filename: %j, encoding: %j, mimeType: %j`,
        filename,
        encoding,
        mimeType
      );

      if (!isVideoValid(mimeType)) {
        return res.status(422).json({
          message: 'File type is not valid',
        });
      }

      const extension = mimeType.split('/').pop();

      newVideo = courseBucket.file(
        `${title}.${extension}`
      );

      file
        .pipe(newVideo.createWriteStream({ gzip: 'auto', resumable: true }))
        .on('error', (err) => {
          console.log(err);
        })
        .on('finish', () => {
          console.log(`File ${name} upload finished`);
          newVideo
            .getSignedUrl({ action: 'read', expires: '03-17-2024' })
            .then((url) => {
              res.status(201).json(url[0]);
            });
        });
    });

    busboy.on('close', () => {
      console.log('Done parsing form!');
    });

    req.pipe(busboy);
  } catch (err) {
    console.log(`Internal Server Error, ${err}`);
    res.status(500).json({ message: err.message, error: err });
  }
```
I think I am writing to GCP bucket on 'file' event listener rather than on 'close' event listener.

**Comment by mscdex** [comment]
What happens when you take GCP out of the equation? For example, what if you save the file locally to disk (e.g. `fs.createWriteStream()` instead of `newVideo.createWriteStream()`)?

**Comment by dev2k22** [comment]
I haven't tested it that way, will do that and let you know! 
Is there a proper way to upload files to GCP storage? I was looking at an [example ](https://gist.github.com/sarfarazansari/59d5cf4bb3b03acf069396ca92a79b3e) that used S3 bucket in Amazon and it uploaded within 'finish' event listener

**Comment by mscdex** [comment]
> Is there a proper way to upload files to GCP storage?

That's beyond the scope of this module, you would have to ask the GCP folks about that.

**Comment by dev2k22** [comment]
Yes its writing to disk within half a second, I think I will undertake another approach for this (first upload file in temp directory) then upload those files to cloud without streaming. 
Thanks for your timely input

**Comment by mscdex** [comment]
Sounds like it's a GCP issue then. They might have suggestions about faster stream-based uploads.

**Comment by dev2k22** [comment]
Yup, also helps that I raised this issue on both repos 😄 
Thanks again for your help, helped me a lot
