### ISSUE TITLE
Document the `error` event

### ISSUE THREAD

**Issue by cristi8** [mscdex/busboy#286]
If busboy is used as currently documented, sending a malformed multipart header will crash the server.

One has to use `.on('error', ...)` to handle errors and avoid crashes.

I think the documentation should mention this, as without this, servers are vulnerable to DenialOfService.

**Comment by mscdex** [comment]
The object that the exported function returns is documented as being a standard [Writable stream](https://nodejs.org/docs/latest/api/stream.html#writable-streams), which is a node.js core object type that is fully documented on the node.js API website.

**Comment by cristi8** [comment]
Oh! So it's considered ok to have sample code on the main page that has a security vulnerability? (DOS)

You know a lot of people will copy-paste and edit when starting with busboy..

Ok then
