### ISSUE TITLE
SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by haseebsaif** [mscdex/busboy#288]
```
node_modules/busboy/lib/utils.js:465
    } catch {}
            ^

SyntaxError: Unexpected token {
```

from past week I am getting this error within the library.
any one else facing it?

Node V: `10.16.0`
NPM: `6.9.0`
In package.json it saying for busboy `^1.4.0`

**Comment by mscdex** [comment]
You're using an older version of node. Most likely v8.x or before. node v10.x supports the newer try-catch syntax in question.

**Comment by haseebsaif** [comment]
I have mentioned the node version, which is v10.16.0
and btw i also checked it with 12.22.10, error is still there. @mscdex

**Comment by mscdex** [comment]
I don't know what to tell you then. That syntax error can only occur on older pre-node v10.0.0 versions where V8 did not support optional exception variables, so somehow your code is being executed with an older node executable.

**Comment by yajindragautam** [comment]
I am also facing his issue while I am deploying my app on production with node version node carbon - v8.17
Please help me to fix it ?
![image](https://user-images.githubusercontent.com/58351637/180427579-28cf7410-a8c4-4e3e-9279-d18c76e81291.png)

**Comment by mscdex** [comment]
@yajindragautam As I said, node versions prior to v10.16.0 are not supported. You need to upgrade your copy of node.

**Comment by mngyng** [comment]
Guys, just add a pair of parenthesis, pass the error parameter for nothing, and work around like this:
`} catch (e) {};`
Works for me, and I don't see any problem in it.
