### ISSUE TITLE
Control when file ends to upload (not in use)

### ISSUE THREAD

**Issue by luispozoquerol** [mscdex/busboy#289]
Maybe cause I'm too new but when I upload a single file many times (all the timse the same file) I get an error: file in use
How do i control when file ends to upload and save in disk?

**Comment by mscdex** [comment]
I'm not quite sure what you're asking. File streams are just normal [node.js Readable streams](https://nodejs.org/docs/latest/api/stream.html#readable-streams). It emits various events, including a `'close'` event when there is no more data.

If you're asking how to handle concurrent write access to the same file, that's out of the scope of this project and is something you'll need to come up with a solution to on your own.
