### ISSUE TITLE
Typescript don't recognize `defParamCharset` attribute

### ISSUE THREAD

**Issue by andresgutgon** [mscdex/busboy#291]
# What?
Hi, I just noticed using the latest version of `busboy@1.5.0` the types in TS don't recognize `defParamCharset`. Maybe is missing generating new types?

![image](https://user-images.githubusercontent.com/49499/158432679-42f161fc-42a1-4f58-97b5-1b648b142569.png)

**Comment by andresgutgon** [comment]
Btw any reason why `defParamCharset` doesn't have as default `utf8` as `defCharset`?

**Comment by mscdex** [comment]
I don't manage anything related to TypeScript, so I can't help you there.



> any reason why `defParamCharset` doesn't have as default `utf8` as `defCharset`?

`defCharset` is referring to the body of the part, `defParamCharset` is referring to parameters in the part's header

**Comment by andresgutgon** [comment]
Ok no problem, I'll try to add it here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59301

**Comment by andresgutgon** [comment]
The PR is merged. For those Typescript fans now you have this param there : )
