### ISSUE TITLE
[Bug] "file" event is not fired when filename contain char "

### ISSUE THREAD

**Issue by BartekCK** [mscdex/busboy#292]
Hey,

I tried to exclude file from request with busboy usage. Every time when file contain `"` char in filename, then event `bb.on('file', (name, file, info) => {...}))` doesn't make any action. 

### Example of filenames:
- test".png
- a"a.jpeg
etc ...

### Request data

- headers
```js
'content-type': 'multipart/form-data; boundary=--------------------------783977461283951785291019',
'content-length': '68052'
```
- start of data
```
----------------------------783977461283951785291019
Content-Disposition: form-data; name="file"; filename="test".png"
Content-Type: image/png

�PNG

IHDR�i�u
        jiCCPICC ProfileH��WXS��[�����H �       "�H     �E�*I �ĘT쨨��E+�*��ZYT�^��

```

### Example code 
```ts
import * as http from 'http';
import busboy from 'busboy';
import * as fs from "fs";
import * as path from "path";


const server = http.createServer((req, res) => {
    const bb = busboy({ headers: req.headers });
    bb.on('file', (name, file, info) => {
        console.log(info);
        const location = path.join(__dirname, '../files', info.filename)
        file.pipe(fs.createWriteStream(location));
    });

    bb.on('field', (name, val, info) => {
        console.log(`Field [${name}]: value: %j`, val);
    });

    bb.on('close', () => {
        res.writeHead(200, { 'Connection': 'close' });
        res.end(`That's all folks!`);
    });
    req.pipe(bb);

});

server.listen(3000, () => {
    console.log('App started')
})
```

### System
- Node v14.18.2
- Busboy 1.5.0

**Comment by mscdex** [comment]
The quote in the filename needs to be properly escaped with a preceding backslash.

**Comment by BartekCK** [comment]
Thank you for response! Yes but what in case when user doesn't have knowledge about how properly escape (`\"`) and he did request by postman? Backend also doesn't have information about file, when user made this kind of mistake.

**Comment by mscdex** [comment]
If postman is not properly escaping/encoding header parameters, then you will need to file an issue on their issue tracker.
