### ISSUE TITLE
Upload Progress

### ISSUE THREAD

**Issue by hashweather** [mscdex/busboy#293]
Thanks once again for this amazing work.

I don't know how to but I really need to find out how to calculate the upload progress on busboy.

Are there any pointers to achieve this?

```
busboy.on('file', function (fieldname, file, filename, encoding, mimetype) {
   //get file upload progress here. How can it be achieved        
}
```

Thank you

**Comment by mscdex** [comment]
There isn't any real way to do this, due to the nature of multipart requests. You could come up with workarounds, but nothing that would be reliable. You're better off just reporting how much has transferred (because you don't know how much data is coming in advance).

**Comment by hashweather** [comment]
@mscdex  I see. So how do I get how much has been transferred so far?

**Comment by mscdex** [comment]
Just add your own counter that counts bytes as you get data in the `file` stream.

**Comment by hashweather** [comment]
Okay. Great!!!....Done that thank you!!!
