### ISSUE TITLE
Allow strictly only Video and Images

### ISSUE THREAD

**Issue by hashweather** [mscdex/busboy#294]
In the multipart data. When it comes to Files, how do i ensure that only Images and Videos are strictly uploaded. No scripts should be accepted.

What I was doing initially was checking the file extension and I only just detected that, that was a very lame way to check the file type.

What is a better way to achieve this with busboy?

**Comment by mscdex** [comment]
You can check the mime type (which is passed to `'file'` event handlers), but the only reliable solution is going to be by inspecting the actual data.
