### ISSUE TITLE
piped request end and close events seem not to be fired 

### ISSUE THREAD

**Issue by abissens** [mscdex/busboy#295]
Hi, 

Piping request stream to busboy seems to prevent request end and close event from firing
Could this indicate some leak issues ? 

**Test code**

```javascript
test('request end/close events are fired', done => {
      let [end, close] = [false, false];
      http.createServer((req, res) => {
          req.on('end', () => end = true)
              .on('close', () => close = true)
              .pipe(busboy({headers: req.headers}))
              .on('close', () => res.writeHead(204, {'Connection': 'close'}).end());
      }).listen(8080);
  
      const req = http.request({
          host: 'localhost',
          port: 8080,
          method: 'POST',
          headers: {
              'Content-Type': 'multipart/form-data; boundary=--------------------------719223781919663014682861'
          }
      }, (res) => {
          expect(res.statusCode).toEqual(204);
          expect([close, end]).toEqual([true, true]);
          done();
      });
      Readable.from(body).pipe(req);
  })
  
  const body = ['----------------------------719223781919663014682861',
      'Content-Disposition: form-data; name="file"; filename="test_file"',
      'Content-Type: application/octet-stream',
      '',
      'File content',
      '----------------------------719223781919663014682861--'].join('\r\n')
```

I also noticed that when the [busboy stream forced end](https://github.com/mscdex/busboy/blob/2b73b9d60aa422ac7c24cf84693ced9aa6104963/lib/types/multipart.js#L435) is commented out the test passes

**System**
Node v16.14.0
Busboy 1.5.0

PS: this also keeps from using the promisified stream.pipeline with busboy since the resulting promise wouldn't resolve

**Comment by mscdex** [comment]
You're not reading the file data from the busboy instance. If you don't do that then the busboy stream will never end/close.

**Comment by abissens** [comment]
I think that it resumes by default. But still even when explicitly resuming the test don't pass
May be the request reader stream should be explicitly resumed when forcing busboy end
i've tried this : https://github.com/abissens/busboy/commit/322c4cfc44fa938f724f50255a809a2cf112b973

**Comment by mscdex** [comment]
I'll remove it anyway, it just means that useless (or potentially useful depending on your use case) data can possibly pass through `busboy`. If that ever becomes an issue for someone, we can revisit it I guess.

**Comment by slewsys** [comment]
Perhaps  `this.end()` should be conditioned on something (maybe type of input)?

I'm using  [async-busboy](https://github.com/m4nuC/async-busboy)  patched for **busboy** version 1.5 (see, e.g., [@revoinc/async-busboy](https://www.npmjs.com/package/@revoinc/async-busboy)).  `npm run test` completes successfully, but times out with **busboy** version 1.6.

**Comment by mscdex** [comment]
@slewsys Does it work if you add `stream.end()` in your tests? If so, I don't think that is asking too much :man_shrugging: . It's hard to please everyone.

**Comment by slewsys** [comment]
Good exercise :)  I'll try to provide a solution.  In the mean time, I'm able to successfully use @revoinc/async-busboy with busboy v1.6 in another package, the Koa Joi router.  So it would appear that it is indeed the async-busboy testsuite that is at fault.

**Comment by slewsys** [comment]
Yes, adding `stream.end()` works, thank you!

In particular, the async-busboy test suite defines a request as:

```javascript
import Stream from "stream"
function request () {
  const stream = new Stream.PassThrough()
  stream.headers = {
    'content-type': 'multipart/form-data; boundary=---------------------------paZqsnEHRufoShdX6fh0lUhXBP4k',
  }
  stream.write([
    '-----------------------------paZqsnEHRufoShdX6fh0lUhXBP4k',
    'Content-Disposition: form-data; name="file_name_0"',
    '',
    'super alpha file',
    '-----------------------------paZqsnEHRufoShdX6fh0lUhXBP4k',
    ...
    ].join('\r\n'))
  return stream
}
 
```
Inserting `stream.end()` after `stream.write()` and before `return stream` allows the tests to complete successfully with busboy v1.6.
