### ISSUE TITLE
multipart: filename is double nested

### ISSUE THREAD

**Issue by nick-zh** [mscdex/busboy#303]
I am using `@middy/http-multipart-body-parser` and they bumped from `busybox:0.3.1` to `busybox:1.6.0`
There were no changes on [middy side](https://github.com/middyjs/middy/issues/864), but i get my file data now double nested, so instead of
```
{
  file: {
    filename: 'image.png',
    mimetype: 'image/png',
    encoding: '7bit',
    truncated: false,
    content: <Buffer>
  }
}
```
I am now getting:
```
{
  file: {
    filename: {
      filename: 'image.png',
      encoding: '7bit',
      mimeType: 'image/png'
    },
    mimetype: undefined,
    encoding: undefined,
    truncated: false,
    content: <Buffer>
  }
}
```

I am fairly certain i am using it the same way as before. I would appreciate any insight no this
Also many thanks for creating a great product :pray:

**Comment by mscdex** [comment]
The signature for the `'file'` event changed, they need to update their code. They should review the [list of v1.x changes](https://github.com/mscdex/busboy/issues/266) as linked in the readme to see if there are other changes they need to make.

**Comment by nick-zh** [comment]
@mscdex thx for the swift reply 🙏
