### ISSUE TITLE
[Bug] try/catch err resolution for older node version

### ISSUE THREAD

**Issue by elvis-lam** [mscdex/busboy#305]
https://github.com/mscdex/busboy/blob/9aadb7afbcb8c70c81c93b1018313c1b1835afb0/lib/utils.js#L469

`} catch (err) {
console.error(err)
} `

**Comment by mscdex** [comment]
This isn't a problem if you use a required node version as indicated in the README, which is node v10.16.0+ as of this writing. Additionally if you install with npm (and possibly other package managers) using an older/unsupported node version, it should display a warning during installation.
