### ISSUE TITLE
Using an = in the boundary returns a malformed content-type error

### ISSUE THREAD

**Issue by LeviHarman** [mscdex/busboy#306]
Hello.
= should be considered a valid character to use for the boundary in a multipart/form-data request.

example content-type that can produce the problem multipart/form-data; boundary====1656457491496===

Seems like it's returning an error in parseContentType

**Comment by mscdex** [comment]
Unquoted parameter values must consist only of [token](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.6) characters, which does not include '='.
