### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by Floby** [mscdex/busboy#31]
Just to say thanks, this module saved me a lot of time today =)

**Comment by NoahBuscher** [comment]
+ over 9000

Within 15 minutes, this module saved me 15% (or maybe more!) on my development time.

In all seriousness, thank you. :+1:

**Comment by lijunfan** [comment]
Thank you!
Works excellent.

**Comment by mercmobily** [comment]
Actually, every time I find a module that is 10000% amazing, I find out that it's yours... THANK YOU!
