### ISSUE TITLE
Infinite field event

### ISSUE THREAD

**Issue by Eexy** [mscdex/busboy#311]
Hi I'm using firebase cloud function and I'm trying to create a middleware to upload image to firebase cloud storage with busboy. For now I'm just trying to test the middleware without file. Here is the code :

```
import { NextFunction, Request, Response } from "express";
import * as busboy from "busboy";

export async function extractPaymentImg(
  req: Request,
  res: Response,
  next: NextFunction
) {
  const bb = busboy({
    headers: req.headers,
    limits: {
      fileSize: 10 * 1024 * 1024,
    },
  });

  // @ts-ignore

  bb.on(
    "file",
    (
      fieldname: any,
      file: any,
      filename: any,
      transferEncoding: any,
      mimeType: any
    ) => {
      file.resume();
    }
  );

  bb.on("field", (key, value) => {
    console.info(key);
    req.body[key] = value;
  });

  bb.on("close", () => {
    next();
  });

  // @ts-ignore
  if (req.rawBody) {
    // @ts-ignore
    bb.end(req.rawBody);
  } else {
    req.pipe(bb);
  }
}
```
But I'm getting an infinite loop on the field event. It keep getting triggered infinitely. I precise that I have already done some research. Here is the link that I tried to use to fix my problem :

[Handling multipart/form-data POST with Express in Cloud Functions](https://stackoverflow.com/questions/48289824/handling-multipart-form-data-post-with-express-in-cloud-functions)

https://github.com/mscdex/busboy/issues/61

https://www.mikesukmanowsky.com/blog/firebase-file-and-image-uploads

I also precise that I use postman for my test

**Comment by mscdex** [comment]
Can you provide the test raw body you're writing to the `busboy` instance (keeping everything intact, including CRs and LFs) that's causing this?

**Comment by mscdex** [comment]
Can you copy and paste the output of `console.log(req.rawBody.toString('base64'))` ? I need the entirety of the actual data to try to reproduce the issue on my side.

What version of node and what version of `busboy` are you encountering this issue with?

**Comment by Eexy** [comment]
I'am using node `v16.14.0` and busboy `1.6.0`. Here is my req.rawBody in base64 : 

` LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLTI1NTMwOTA1NDExMTA1NjcwMjYzNzM3MQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJ0ZXN0Ig0KDQp0ZXN0DQotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tMjU1MzA5MDU0MTExMDU2NzAyNjM3MzcxLS0NCg==`

**Comment by mscdex** [comment]
I cannot reproduce the issue. Here is my reproduction code, using your form data and configuration:

```js
'use strict';

const busboy = require('busboy');

const data = Buffer.from('LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLTI1NTMwOTA1NDExMTA1NjcwMjYzNzM3MQ0KQ29udGVudC1EaXNwb3NpdGlvbjogZm9ybS1kYXRhOyBuYW1lPSJ0ZXN0Ig0KDQp0ZXN0DQotLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tMjU1MzA5MDU0MTExMDU2NzAyNjM3MzcxLS0NCg==', 'base64');
const bb = busboy({
  headers: {
    'content-type': 'multipart/form-data; boundary=--------------------------255309054111056702637371'
  },
  limits: {
    fileSize: 10 * 1024 * 1024,
  },
});
bb.on('file', (...args) => {
  console.log('file', args);
});
bb.on('field', (...args) => {
  console.log('field', args);
});
bb.on('close', () => {
  console.log('close');
});
bb.end(data);
```

and the resulting output:

```
field [
  'test',
  'test',
  {
    nameTruncated: false,
    valueTruncated: false,
    encoding: '7bit',
    mimeType: 'text/plain'
  }
]
close
```

**Comment by mscdex** [comment]
Perhaps something is calling your `extractPaymentImg` function for the same request?

**Comment by Eexy** [comment]
`extractPaymentImg` is only use in one place for a test router. No other routes use it

**Comment by Eexy** [comment]
I found the error thanks to you. I was going to delete the test router and quit and then I saw that I was calling `testRouter ` in the `testRouter`
