### ISSUE TITLE
How can we use busboy to upload a file in object storage without using os.tmpdir(), since by doing this we are creating a temporary storage for it. I don't want that i directly want to call object storage

### ISSUE THREAD

**Issue by Maleeha456** [mscdex/busboy#313]

**Comment by mscdex** [comment]
I don't know what you're asking. `busboy` does not touch any kind of storage, it only provides streams. It's up to you to direct where the data goes. Maybe you're confusing `busboy` with some other module?

**Comment by Maleeha456** [comment]
If I have to upload data directly to object storage, what I am
comprehending is that first, file event will be triggered and in that, I
would have to call os.tempdir to write the uploded file  (and save it in
temporary storage) and when the streaming is finished, I can call the
finish event of busboy and pass this temporary file to the object storage.
Is that correct?
If it is so, what I don’t want is, not saving in temporary storage (via
os.tempdir) and directly pass it to object storage.

**Comment by mscdex** [comment]
That's beyond the scope of this project. If the library or service you're using to store the upload does not support streaming directly to the cloud/object storage, that is their problem. There is nothing `busboy` can do about that, as it only provides streams which never touch the local disk.

**Comment by Maleeha456** [comment]
Okay, thanks
I just wanted to confirm one thing, why is os.tempdir() used when we have
to upload in firebase. I saw it in the code.

**Comment by mscdex** [comment]
`busboy` does not use temporary directories. You will need to ask that question on the issue tracker of the module that handles uploads to firebase, as I presume they are the ones using a temporary directory.

If you're referring to the use of a temporary directory in the example in the readme, then that is because it is simply that -- an example. It's not something you have to do.
