### ISSUE TITLE
Depends on vulnerable versions of dicer-- High

### ISSUE THREAD

**Issue by RashadTanjim** [mscdex/busboy#328]
node_modules/busboy
It depends on vulnerable versions of dicer
please remove or update dicer

**
Severity: High
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
No fix available

**Comment by mscdex** [comment]
I think you posted this to the wrong repository?

**Comment by haydn** [comment]
Yeah, looks like `dicer` was a dependency in an older version of `busboy`. It was removed in https://github.com/mscdex/busboy/commit/54a86838c15bba1fc78eebdfa3c6a986a5e57dd9.

@RashadTanjim You've probably got a transitive dependency that requires an older version of busboy.
