### ISSUE TITLE
multipart/form-data windows-1251

### ISSUE THREAD

**Issue by UncleVic** [mscdex/busboy#334]
If a form contains charset=windows-1251, data can't be decoded correctly. After parsing a request a string will be corrupted.

**Comment by mscdex** [comment]
You can modify the default character sets by passing in a configuration object. However, you will be limited to what node has built-in support for (meaning via `Buffer` encodings).

You will probably want to use an intermediate encoding like `'latin1'` and then convert that to windows-1251 using whatever you like, whether it be `util.TextEncoder`/`util.TextDecoder` if your node binary was built with full (or possibly system) ICU or a 3rd party module (like [`iconv-lite`](https://github.com/ashtuchkin/iconv-lite)).

**Comment by mscdex** [comment]
Actually, I believe if you want to rely on ICU availability, you should already be able to specify an encoding that `TextDecoder` accepts and `busboy` will use that to decode strings.

**Comment by UncleVic** [comment]
I hoped the library can get charset from headers...
Unfortunately, I don't use the busboy directly. There is a big chain, NestJs -> multer -> busboy.
And as I can see, the multer doesn't pass any default charsets. I understand, it's multer problem, I think so. But why don't take a charset from the headers?

**Comment by UncleVic** [comment]
I figured out. My problem in the Multer.
You are right, if I pass `defParamCharset=latin1` after that I can decode my string by
`iconv.decode(Buffer.from(stringFromBusboy, 'latin1'), 'win1251')`

But Multer calls the Busboy constructor as `Busboy({headers: req.headers, limits: limits, preservePath: preservePath})`
and after that, I have broken UTF8 string.
