### ISSUE TITLE
Bug on UTF-8 filenames

### ISSUE THREAD

**Issue by wesleimarinho** [mscdex/busboy#339]
After updating to the lasting version, I've noticed that filenames containing utf-8 characters such as 'Declaração.pdf' are not processed correctly by busboy anymore, giving wrong file name after its processing.

**Comment by wesleimarinho** [comment]
Found how to solve it using the configuration defParamCharset.

**Comment by andylwelch** [comment]
I just updated from v0.3 and this also caught me.  Ideally this should be more obvious in the "Breaking Changes" guide, or the `defParamCharset` should be `utf8` instead of `latin1` to maintain backwards compatibility.
