### ISSUE TITLE
Need example for reading field-post data 1st and then files-post data.

### ISSUE THREAD

**Issue by rthakur-sourcebits** [mscdex/busboy#43]
Hi, 

I am successfully able to use read POST data on request-received.
But, when I put file-read event after checking/reading field value then, request hang. 

Can you tell me a way from your code. How can we register file-read-event after checking the field value from database.
basically a serial request to read field 1st and then after its say read file-data then, file read event should get executed. 

Thanks,

**Comment by lexigren** [comment]
Hello, sorry, if my question is stupid, but I still can't get it right.
My form data contains fields before files for sure, I'm receiving field event first, but it anyway gives me 'Cannot switch to old mode now.', when I'm trying to pause request.
I've already created callback way to read fields and read/write DB, before uploading a file, but it looks kinda monstrous.
So, is there a way to pause stream on field, read/write DB, and than proceed to file uploading?

**Comment by mscdex** [comment]
@lexigren Streams already start in a paused state, so there is no need to manually pause them after you see a `file` event emitted.

You might post your relevant code though to see if there might be anything else amiss.

**Comment by lexigren** [comment]
Thank you for helping.
At this moment I've found pause-stream module, which helping to clear some code, but still requires a lot of callbacks.
What I'm asking is if it possible to do something like this:

	 var id;	
	 if(req.busboy) {
		req.busboy.on('field', function(fieldName, fieldValue, valTruncated,keyTruncated) {
		    //so here I want to pause my stream	
		    req.pause();
		 
		    //deal with DB
		    Item.create(JSON.parse(fieldValue);, function (err, item) {
		        if (err) {
		        } else {
		            fileSystem.createFolder("client/res/img/" + item._id, function (err) {
		                if(!err){                            
		                    id=item._id;
				    //if item and folder for files are created - resume stream
		                    req.resume();
		                }else {
		                }
		            });
		        }
		    });
		});
		//this event shouldn't be fired until item and folder are created
		req.busboy.on("file", function(fieldName, fileStream, fileName, encoding, mimeType) {

		        fstream = fs.createWriteStream("client/res/img/"+id+"/"+ fileName);
		        fileStream.pipe(fstream);
		        fstream.on('close', function () {
		        });

		    }
		});
		req.busboy.on('finish', function() {
		});
		req.pipe(req.busboy);
	    }

As I understand, since we've started stream by req.pipe(req.busboy), there is no way to pause it?
If so, how to get field value to perform DB and folder actions before starting the stream?

**Comment by mscdex** [comment]
@lexigren Perhaps a better way would be to move the async calls inside the `file` event handler, since there'd be no use in creating folders, etc. if there doesn't happen to be a file stream. Then change your `field` handler to just save `fieldValue` to some variable in the parent scope so you can get at it in your `file` event handler.

**Comment by lexigren** [comment]
Actually this is sort of what I'm doing now. It's good for one file, but when there is many of them, they are all start to make Item/folder creation requests simultaneously, and so I need to run only first, and then introduce some requests Queue. 


	    var item, id;

	    function createItem(callback){
		Item.create(item, function (err, item) {
		    if (err) {
		    } else {
		        fileSystem.createFolder("client/res/img/" + item._id, function (err) {
		            if(!err){
		                id=item._id;
                                //after DB/folder success starting id delivery
		                callback();
		            }else {
		            }
		        });
		    }
		});
	    }

            //Queue for all id requests		
	    var callbacksQueue=[];
	    var itemCreationStarted=false;
	    function getId(callback){
		//filling queue
		callbacksQueue.push(callback);
	        //if item creation wasn't started - starting it
		if(!itemCreationStarted){
		    itemCreationStarted=true;			
		    createItem(function () {
                        //if item created - responding to every request for id
		        for(var i=0;i<callbacksQueue.length;i++){
		            callbacksQueue[i]();
		        }
		    })
		}
	    }

	    if(req.busboy) {
		req.busboy.on('field', function(fieldName, fieldValue, valTruncated,keyTruncated) {
		    item=JSON.parse(fieldValue);
		});
		req.busboy.on("file", function(fieldName, fileStream, fileName, encoding, mimeType) {
		    var pStream;
		    //file writting   
		    function writeFile(){
		        fstream = fs.createWriteStream("client/res/img/"+id+"/"+ fileName);
		        if(pStream) {
		            pStream.pipe(fstream);
		            pStream.resume();
		        }else{
		            fileStream.pipe(fstream);
		        }
		        fstream.on('close', function () {
		        });

		    }
                    //if id isn't presented yet - making request for it
		    if(!id) {
			//meanwhile - buffering filestream to pauseStream
		        pStream = pauseStream();
		        fileStream.pipe(pStream.pause());
		        getId(writeFile);
		    }else{
		        writeFile();
		    }
		});
		req.busboy.on('finish', function() {
		});
		req.pipe(req.busboy);
	    }
	    else {
	    }

So, as far as I understand, there is no other way, than to do something like this, when trying proceed DB/files operations in single request?

**Comment by hitchcott** [comment]
`readFieldsFirst: true` option would be awesome. I don't think it's a great solution to rely on the client sending fields in the correct order. What if I want the file field to appear first in the form --`{position:absolute; top:0;}` :smile: ?

:+1:
