### ISSUE TITLE
Transfer-Encoding: chunked uploads

### ISSUE THREAD

**Issue by fabien** [mscdex/busboy#45]
I seem to have an issue with Transfer-Encoding: chunked uploads - the file is not fully streamed to disk, even though the browser sent all the data. In fact, it only writes out the first chunk, and treats each additional chunk as a new transfer (without writing it to disk).

Does busboy usually handle this scenario, or do I have to tweak my code for it?

**Comment by paulm17** [comment]
I know this is an old issue.  But was `Transfer-Encoding: chunked` added?  I have the same issue where only the first chunk is saved.  I'm using react-uploady.  Happy to make an example.

**Comment by charmander** [comment]
@paulm17 As far as I know, the same comment still applies, so yes, you should make an example.
