### ISSUE TITLE
Handling XHR2 Uploads ?

### ISSUE THREAD

**Issue by daslicht** [mscdex/busboy#47]
Hello,
when I try to upload files using ajax the content type will always be 
```application/octet-stream ``` even if I set it to ```multipart/form-data```.

Thats my current approach:
http://www.filecatalyst.com/xhr2-uploads-intro

How to properly upload files using ajax , how to force ```application/octet-stream ```for?

This is not enough:
```
<form enctype="multipart/form-data" id="uploadForm">
select file(s): <input name="files" type="file" multiple="multiple" id="files"/>
<input id="uploadFiles" type="button" value="Upload File" />
</form>
```

**Comment by DefiantBidet** [comment]
sorry to bring up a very dead issue,  I came across the "Error: Multipart: Boundary not found" issue today. in the vein of helping some poor schlep, like myself, that is banging their heads....  The Content-Type field for multipart entities requires the "boundary" parameter .. i.e. `Content-Type: multipart/mixed; boundary=gc0p4Jq0M2Yt08jU534c0p` from this SO answer: http://stackoverflow.com/a/10932533

**Comment by diosney** [comment]
@DefiantBidet http://stackoverflow.com/a/29749232/881286 helped me a lot too.
