### ISSUE TITLE
use busboy in multiple middleware that handles the same request

### ISSUE THREAD

**Issue by MiroRadenovic** [mscdex/busboy#55]
Hello, i'm having problems to use busboy in different express middlewares that handles the same request:

```
function midleware1(req, res, next){
    var option = {
        headers: req.headers
    };
    var busboy = new Busboy(option);

    busboy.on('field', function(fieldname, val) {
       // some code... needed for a specific validation
    });

    busboy.on('finish', function() {
        next();
    });

    return req.pipe(busboy);
}

function midleware2(req, res, next){
    var option = {
        headers: req.headers
    };
    var busboy = new Busboy(option);

   busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
       // some other code that handle the file upload...
    });

    busboy.on('finish', function() {
        next();
    });

    return req.pipe(busboy);
}

```

and if i try to use the this two middleware to handle the same request

```
   app.post("/url",midleware1,midleware1);
```

Unfortunately it just hangs when /url is requested.

I need to split busboy in two separate middlewares, because i want first to check some params, and only if certain requirements are met, allow the file upload

I have tried to do also req.unpipe(busy) in midleware1, but it does not work. 
Can you please help me understand how this can be accomplished with busboy?

**Comment by bikeshrestha** [comment]
Hello MiroRadenovic

> Ok! thank you very much for your help!
> i will start the refactor then :)

What did you get
