### ISSUE TITLE
Missing Content-Type?

### ISSUE THREAD

**Issue by nicholaswyoung** [mscdex/busboy#70]
I'm working with Busboy in Koa, and passing ```this.headers``` into Busboy's options hash. For some reason, Busboy is missing the ```headers``` option. Here's the content type object from Koa's headers:

```
'content-type': 'multipart/form-data; boundary=----WebKitFormBoundary7Q0vAPYV6vaXrhS5',
```

Parsing seems to work fine. I can pipe file streams and everything, yet this error persists.

**Comment by mscdex** [comment]
Can you show the actual code you're using?

**Comment by nicholaswyoung** [comment]
It's pretty basic:

```javascript
var app = require('koa')()l

app.use(function *() {
   var context = this.req || this
   ,     parser = new Busboy({ headers: context.headers });

   busboy.on('file' function (args) {});
   // etc

   context.pipe(parser);
});
```

**Comment by mscdex** [comment]
I'm not familiar enough with co/koa/etc., but as you can see, busboy merely [checks that `headers` exists and `headers['content-type']` is a string](https://github.com/mscdex/busboy/blob/a4cca9480aa771795d772f276602edd8afe2becd/lib/main.js#L20). So as long as `typeof context.headers === 'object' && typeof context.headers['content-type'] === 'string'` there shouldn't be any problem...

**Comment by jonathanong** [comment]
not sure what's going on, but you should do `this.request.is('urlencoded', 'multipart')` before trying to use busboy.

**Comment by nicholaswyoung** [comment]
Hmmm. I'm kinda at a loss, because it looks like everything I'm passing in from Koa is correct.

```javascript
var app    = require('koa')()
,   Busboy = require('busboy');

app.use(function *() {
  var context = this.req || this
  ,   files   = {}
  ,   parser  = new Busboy({ headers: this.req.headers });

  parser.on('error', function (err) {
    throw err;
  });

  parser.on('file', function (field, stream, name, enc, mime) {
    files[field] = name;
    stream.resume();
  });

  parser.on('finish', function () {
    console.log(files);
  });

  this.req.pipe(parser);

  this.body = "Yo, this is a test.";
});

app.listen(process.env.PORT || 9292);
```

**Comment by aprilmintacpineda** [comment]
I'm getting this error now, I can see `Content-Type` on the header and it seems valid, I guess it wants a lower case?
