### ISSUE TITLE
Callbacks not called on finish (io.js v1.2.0)

### ISSUE THREAD

**Issue by matylla** [mscdex/busboy#71]
Please have a look at the example below. Executing the logic within `file.on("end")` callback does not report a proper uploaded file size, nor does the logic in `bus.on("finish")`. To be 100% sure that upload parsing succeeded and uploaded file is finally written to disk I had to hook into my `stream.on("finish")` event (`fs` event).

Is this a desired behaviour? I though that when `bus.on("finish")` is fired we can be 100% positive that all the logic associated with this multipart upload finished. Also I'm not sure if this is the io.js problem (doubt that) or a global node > 0.10.0 issue.

````
$ node -v
v1.2.0
````
````js
http.createServer(function (req, res) {
    if (req.method !== "POST") {
        res.writeHead(404);
        return res.end();
    }

    var destination = "foobar.jpg";

    var bus = new busboy({
        headers: req.headers
    });

    bus.on("field", function (field, value) {
        // fields processing logic here
    });

    bus.on("file", function (field, file, filename) {
        file.on("end", function () {
            console.log(fs.statSync(destination).size); // <---- 0 bytes
        });

        var stream = fs.createWriteStream(destination);

        stream.on("finish", function () {
            console.log(fs.statSync(destFile).size); // proper 5592 bytes here
        });

        file.pipe(stream);
    });

    bus.on("finish", function () {
        console.log(fs.statSync(destination).size); // <---- 0 bytes
    });

    req.pipe(bus);
}).listen(8000);
````

**Comment by mscdex** [comment]
The busboy instance emits `finish` once all data has been processed. This includes taking into account all file streams. However there is no way for busboy to know what you're doing with the data read from file streams, so it's very possible that files are not completely written *to disk* before processing finishes, due to `fs.ReadStream`s' internal buffering and such.

**Comment by matylla** [comment]
Ok, thanks for the explanation. Closing this issue as this is not a bug by any means.

However could you advice a proper way of handling this? I'm interested in parsing the whole form (fields _and_ files) and writing uploaded file in a location of my choice. Once all of this is done I would need a final callback. I guess there's no way around this other than listening on the filesystem's `finish` event like I did in the example above?

Also last question about `busboy` - does it first save the file in a temporary location and from there the file is streamed or is the file streamed directly from the upcoming request?

**Comment by mscdex** [comment]
`busboy` does not write anything to disk, it streams directly from the input stream.

Typically you will use some sort of counter that you increase on the `file` event and decrease inside the `fs.ReadStream`'s `finish` event. Then it's just a matter of checking if the new value of the counter is zero. If it is, and `busboy` has emitted `finish`, then you know you are completely done saving all files to disk. This is basically what [`multer`](https://github.com/expressjs/multer/blob/master/index.js) and other modules built on busboy end up doing.
