### ISSUE TITLE
Invalid busboy behavior on incomplete multipart

### ISSUE THREAD

**Issue by thomas-riccardi** [mscdex/busboy#73]
With busboy 0.2.9 when piping an incomplete multipart to `busboy` the last (incomplete) part is emitted on source end (field emitted, or file stream end emitted), then busboy stops emitting events (no file `end`, no `finish`, no `error`).
It should instead emit an error: the multipart is invalid (because incomplete) and should not emit the current part, because it's not finished.

head commit e70d9e462b21f5554c54aa16bc20620e5f5e3eff fixes part of this issue: now busboy emits an error (`Error: Unexpected end of multipart data`), but the current incomplete part is still emitted.
For field events we should just not emit them and emit `error` on busboy.
For file events we should emit `error` on file, on busboy or on both, I'm not sure which.
Busboy also emits `finish`, I'm not sure if we want that _in addition to_ the `error` event.

I'm not sure how to properly handle errors in a pipe involving multiple streams (in my case: http request incoming message, busboy, aws-sdk S3 upload; the S3 upload needs an explicit abort on source error, and the http request needs a reply): busboy readme doesn't show any error handling example.

**Comment by mscdex** [comment]
I'm always open to pull requests to improve busboy.

**Comment by rbriank** [comment]
I've seen this problem too.  My workaround is to add a flag to the file end event and check it in the busboy finish event.  If it's not set, I know file end was never called so I can reject.

**Comment by FranckFreiburger** [comment]
ping !

**Comment by tomasdev** [comment]
@thomas-riccardi did you fix it? what was your workaround?

**Comment by thomas-riccardi** [comment]
@tomasdev Sorry I don't remember, it was too long ago, I stopped using node.js since.

**Comment by mscdex** [comment]
Closing this for now with the new implementation in master and with changes to node streams in general in modern versions of node. `'close'` is now the event to listen for whether there was an error or not and `'finish'` should only be emitted if there was no error.
