### ISSUE TITLE
Finish Event not being emitted

### ISSUE THREAD

**Issue by crispen-smith** [mscdex/busboy#74]
I'm calling this from within a locomotive app, I would expect some sort of finish event to be emitted, but it seems like my callback is never called.

    /*jslint node:true */
    "use strict";
    Var Busboy = require("busboy"),
          fs = require('fs');

    module.exports = function (next) {
      if (this.req.method && this.req.method === "POST") {
          var busboy = new Busboy({headers: this.req.headers});
          busboy.on('file', function (fieldname, file, filename, encoding, mimetype) {
              if (typeof this.files === "undefined") {
                  this.files = [];
              }

              this.files.push({field: fieldname, file: file});
          }.bind(this));

          busboy.on("field", function (key, value, keyTruncated, valueTruncated) {
              this.req.query[key] = value;
          }.bind(this));

          busboy.on("finish", function () {
             // THIS NEVER GETS CALLED
              console.log("\n\n\n INSIDE FINISH FUNCTION");]
              next();
          });
    
          this.req.pipe(busboy);
      } else {
          next();
      }
    };

**Comment by mscdex** [comment]
Are you actually reading from your `file` streams? If you don't, you won't see the `finish` event because the stream backpressure mechanism is doing its thing.

**Comment by crispen-smith** [comment]
Okay, that does make sense...  I'd planned on adding a subsequent filter and passing the streams into that filter downstream (as it were).  This is due to not wanting to start another Asynch in the middle of the pipe and having the operation of that Asynch complete after the results were required. 

I felt that it would be cleaner to do something along the lines of 

     GetFiles(next);
     ProcessFiles(next);
     ProcessOutput();

      Run( GetFiles(ProcessFiles(ProcessOutput);

But if I *need* to do something with the file streams  I will look at:

     GetFiles(next) {
          foreach(file).processFiles();
      }
      ProcessOuput();

       Run();


I'm a little scared about the Asynch return timing as I outlined above but I'll see what I can do with it.

**Comment by crispen-smith** [comment]
So I've been working towards resolving this and while I believe this is my error, I just can't seem to figure out what it is.

Here's what I've got for code:

    /*jslint node:true */
    "use strict";
    var cloudinary = require('cloudinary'),
        Busboy = require("busboy"),
        fs = require('fs');

    module.exports = function (next) {


        if (this.req.method && this.req.method === "POST") {
            var busboy = new Busboy({headers: this.req.headers});
               busboy.on('file', function (fieldname, file, filename, encoding, mimetype) {
                    var stream = cloudinary.uploader.upload_stream(function (result) {
                    this.req.query[fieldname] = result.url;
                }.bind(this));
            
                file.on('data', stream.write);
                file.on('end', stream.end);
            }.bind(this));
            busboy.on("field", function (key, value, keyTruncated, valueTruncated) {
                this.req.query[key] = value;
             }.bind(this));

            busboy.on("finish", function () {
               next();
            });
        this.req.pipe(busboy);
        } else {
            next();
        }
    };


Which gives me:

    _stream_writable.js:180
      if (state.ended)
               ^
    TypeError: Cannot read property 'ended' of undefined
        at FileStream.Writable.write (_stream_writable.js:180:12)
        at FileStream.emit (events.js:95:17)
        at FileStream.<anonymous> (_stream_readable.js:765:14)
        at FileStream.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:427:10)
        at emitReadable (_stream_readable.js:423:5)
        at readableAddChunk (_stream_readable.js:166:9)
        at FileStream.Readable.push (_stream_readable.js:128:10)
        at PartStream.onData     (/Users/crispensmith/Documents/ctstore/Site/node_modules/busboy/lib/types/multipart.js:215:28)
    at PartStream.emit (events.js:95:17)
    20 Mar 00:13:00 - [nodemon] app crashed - waiting for file changes before starting...

Any help you could provide would be greatly appreciated.  I'm quite new to streams so it's probably something very simple that I'm not catching.

**Comment by mscdex** [comment]
What version of node are you using?

**Comment by crispen-smith** [comment]
0.10.36 on a Mac

**Comment by mscdex** [comment]
Ok I think I see the problem. You're passing `stream.write` and `stream.end` as event handlers. This won't work like you'd expect because when you pass those functions, it's passing the bare function with no context attached to it. So when a `data` event occurs for example, the function is called but now the `this` inside `stream.write` is not pointing to `stream` anymore.

Typically the way to solve this is to bind the function with `stream.write.bind(stream)` or using a closure like `file.on('data', function(d) { stream.write(d); });`. However since you already have a real Writable stream, you can just pipe the two together:

```javascript
var stream = cloudinary.uploader.upload_stream(function (result) {
  this.req.query[fieldname] = result.url;
}.bind(this));

file.pipe(stream);
```

This way is much simpler and backpressure is handled automatically.

**Comment by crispen-smith** [comment]
Thanks for a very thorough explanation, that makes excellent sense now.

**Comment by crispen-smith** [comment]
Unfortunately my original fears about timing seem to have played out and the Cloudinary callback  may be called after the initial stream completes.  The way I see it there are two options: 1) I can wire in some sort of debouncing tool or 2) I can write to disk and then read from there.   

In either case, I believe this can be closed as the original concern was resolved and stemmed from my lack of familiarity with streams & busboy.
