### ISSUE TITLE
busboy doesn't error when over limit?

### ISSUE THREAD

**Issue by canebat** [mscdex/busboy#76]
I've got a busboy with options:
```
var busboyParser = busboy({
    limits: {
        fileSize: 1000000,       // 1 mb
        files: 2,
    }
});
```
My code is basically from the README:
```
    if (req.busboy) {
        req.busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
            var saveTo = path.join(os.tmpDir(), path.basename(fieldname));
            console.log("saved to " + saveTo);
            file.resume();
        });
        req.busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated) {
            console.log('Field [' + fieldname + ']: value: ' + val);
        });
        req.busboy.on('finish', function() {
            console.log('Done parsing form!');
        });
        req.busboy.on('error', function() {
            console.log("ERROR");
        });
        req.pipe(req.busboy);
    }
```

But if I upload a file that's over 1MB or upload more than 2 files, busboy won't throw any errors. Instead  busboy just proceeds to process the file(s):
```
Field [flowChunkNumber]: value: 3
Field [flowChunkSize]: value: 1048576
Field [flowCurrentChunkSize]: value: 1048576
Field [flowTotalSize]: value: 8210139
Field [flowIdentifier]: value: 8210139-guidepdf
Field [flowFilename]: value: guide.pdf
Field [flowRelativePath]: value: guide.pdf
Field [flowTotalChunks]: value: 7
saved to /tmp/file
Done parsing form!
```

How should I handle errors relating to the defined limits?

**Comment by mscdex** [comment]
As documented in the [readme](https://github.com/mscdex/busboy#busboy-special-events), there are two ways to determine if a file stream has been truncated: checking `file.truncated === true` and/or listening for the `limit` event on the `file` stream. If you want to know when a file limit is reached, listen for `filesLimit` event on the busboy instance.

**Comment by sam1111** [comment]
There is no event for fileSize limit?

**Comment by mscdex** [comment]
@sam1111 Yes, it's called `limit` and it's emitted on the `file` stream.

**Comment by sam1111** [comment]
Got it!! Thanks!!

**Comment by sam1111** [comment]
One more query. Can we stop busboy.on('finish') to be called if file.on('limit') is called?

**Comment by mscdex** [comment]
@sam1111 You can simply unpipe busboy from the source stream if you want to halt parsing and possibly call `busboy.removeListener('finish', myFinishListener)`.
