### ISSUE TITLE
gridfs-stream compatability

### ISSUE THREAD

**Issue by pos1tron** [mscdex/busboy#79]
I am trying to use your library to stream multipart file uploads directly into [gridfs](http://docs.mongodb.org/manual/core/gridfs/) using [gridfs-stream](https://github.com/aheckmann/gridfs-stream). I'm having an issue with the encoding of the original file changing. If I pipe the busboy file stream into an fs writestream, then read the file back out with an fs readstream and pipe it to gridfs, all is well. but if I skip the fs streams and go directly to gridfs, the encoding gets messed up.

I have an issue open with gridfs-stream, but I wanted to check if there's anything I could do from this end.

https://github.com/aheckmann/gridfs-stream/issues/76

**Edit:**

Here's how I want to do it, followed by what is actually working for me.

Results in bad/incorrect encoding when read back out:

	exports.create = function(req, res) {
		var busboy = new Busboy({ headers: req.headers });
		var fileId = new mongoose.Types.ObjectId();

	    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
	    	var writeStream = gfs.createWriteStream({
				_id: fileId,
			    filename: filename,
				mode: 'w',
			    content_type: mimetype,
			    metadata: {
		        	uploadedBy: req.user._id,
		        	encoding: encoding,
		    	}
			});

			file.pipe(writeStream);
	    });

	    busboy.on('finish', function() {
	  		return res.status(200).send({
				message: fileId.toString()
			});
	    });

	    req.pipe(busboy);
	};

works:

	exports.create = function(req, res) {
		var busboy = new Busboy({ headers: req.headers });
		var fileId = new mongoose.Types.ObjectId();
		
	    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
	    	var tmpPath = '/tmp/' + filename;
	    	var fsWriteStream = fs.createWriteStream(tmpPath);

	    	busboy.on('finish', function() {

	    		var fsReadStream = fs.createReadStream(tmpPath);

	    		var writeStream = gfs.createWriteStream({
					_id: fileId,
				    filename: filename,
					mode: 'w',
				    content_type: mimetype,
				    metadata: {
			        	uploadedBy: req.user._id,
			        	encoding: encoding,
			    	}
				});

				fsReadStream.on('end', function() {
					fs.unlink(tmpPath, function (err) {
						if (err) throw err;
						res.status(200).send({
							message: fileId.toString()
						});	
					});
				});

				fsReadStream.pipe(writeStream);

	    	});

			file.pipe(fsWriteStream);
	    });

	    req.pipe(busboy);
	};

**Comment by mscdex** [comment]
Out of curiosity, what if you try moving:

```javascript
return res.status(200).send({
  message: fileId.toString()
});
```

inside the `file` event handler like so:

```javascript
// ...
writeStream.on('finish', function() {
  res.status(200).send({
    message: fileId.toString()
  });
});
file.pipe(writeStream);
```

?

**Comment by pos1tron** [comment]
Thanks for the suggestion @mscdex but unfortunately, that didn't help.

**Comment by mscdex** [comment]
I dunno then, all data in the file stream is kept intact exactly as it was in the request. There are no data conversions or anything like that.

Have you tried comparing the data straight from the file stream against the data coming from the file on disk from your working solution? If they match, then that may point to an issue in `gridfs-stream`?

**Comment by pos1tron** [comment]
Here's a simple implementation that I copied from another developer and modified. This is working for me: (I'm still trying to figure out why it won't work in my original express app. Something seems to be interfering)

https://gist.github.com/pos1tron/094ac862c9d116096572

    var Busboy = require('busboy'); // 0.2.9
    var express = require('express'); // 4.12.3
    var mongo = require('mongodb'); // 2.0.31
    var Grid = require('gridfs-stream'); // 1.1.1"
    var app = express();
    var server = app.listen(9002);
     
    var db = new mongo.Db('test', new mongo.Server('127.0.0.1', 27017));
    var gfs;
    db.open(function(err, db) {
      if (err) throw err;
      gfs = Grid(db, mongo);
    });
     
    app.post('/file', function(req, res) {
      var busboy = new Busboy({ headers : req.headers });
      var fileId = new mongo.ObjectId();
     
      busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
        console.log('got file', filename, mimetype, encoding);
        var writeStream = gfs.createWriteStream({
          _id: fileId,
          filename: filename,
          mode: 'w',
          content_type: mimetype,
        });
        file.pipe(writeStream);
      }).on('finish', function() {
        // show a link to the uploaded file
        res.writeHead(200, {'content-type': 'text/html'});
        res.end('<a href="/file/' + fileId.toString() + '">download file</a>');
      });
     
      req.pipe(busboy);
    });
     
    app.get('/', function(req, res) {
      // show a file upload form
      res.writeHead(200, {'content-type': 'text/html'});
      res.end(
        '<form action="/file" enctype="multipart/form-data" method="post">'+
        '<input type="file" name="file"><br>'+
        '<input type="submit" value="Upload">'+
        '</form>'
      );
    });
     
    app.get('/file/:id', function(req, res) {
      gfs.findOne({ _id: req.params.id }, function (err, file) {
        if (err) return res.status(400).send(err);
        if (!file) return res.status(404).send('');
        
        res.set('Content-Type', file.contentType);
        res.set('Content-Disposition', 'attachment; filename="' + file.filename + '"');
        
        var readstream = gfs.createReadStream({
          _id: file._id
        });
        
        readstream.on("error", function(err) {
          console.log("Got error while processing stream " + err.message);
          res.end();
        });
        
        readstream.pipe(res);
      });
    });

**Comment by wdawson4** [comment]
@pos1tron I am experiencing the same issue. Were you able to figure out what was causing this?

**Comment by adityab** [comment]
@wdawson4 In my case, `connect-livereload` was indeed corrupting responses (ODT/zip files). This was completely unpredictable; some files downloaded fine while others were doubled in size (800 KB to 1.6 MB, weird stuff).

I'll investigate more on why this happens, but thanks for saving me many more hours of hair pulling.

**Comment by pos1tron** [comment]
Thanks @adityab, and sorry for not replying to you @wdawson4, My problem was also with connect-livereload.

**Comment by adityab** [comment]
Cool! Just for completion/posterity, the comment here describes how to workaround this issue instead of getting rid of that middleware altogether. https://github.com/intesso/connect-livereload/issues/39#issuecomment-102150216

**Comment by SOSANA** [comment]
1+ thanks everyone! helped me as well
