### ISSUE TITLE
How is busboy different from dicer, for dummies?!

### ISSUE THREAD

**Issue by shakiba** [mscdex/busboy#82]
I know that busboy depends on dicer, but how is it different and when should I use each of them?

**Comment by mscdex** [comment]
Dicer is for parsing any standard/general multipart type (regardless of semantics). You feed it data and it emits parsed headers and a body stream for each part.

Busboy builds on top of dicer by performing some additional work to take into account `multipart/form-data`-specific details such as detecting files vs regular input fields, parsing `Content-Disposition` headers for field names and filenames for file parts, adding configurable limits, etc.

So if you're working with `multipart/form-data`, you'd want to use busboy. If you're parsing some other kind of `multipart/*` type with different semantics, you will probably want dicer.

**Comment by shakiba** [comment]
Thanks! :)
