### ISSUE TITLE
Outdated readable-stream

### ISSUE THREAD

**Issue by genediazjr** [mscdex/busboy#83]
any chance for readable-stream to be updated to [v2.0](https://www.npmjs.com/package/readable-stream)?

**Comment by mscdex** [comment]
Are you using node v0.8?

**Comment by genediazjr** [comment]
no sir. I'm using v0.12.

**Comment by mscdex** [comment]
`readable-stream` is only used for node v0.8 users, otherwise the built-in streams are used.

**Comment by genediazjr** [comment]
Ah I see. Thank you sir!
