### ISSUE TITLE
Need to document how to handle errors

### ISSUE THREAD

**Issue by jimmywarting** [mscdex/busboy#84]
It throws some error but you don't know how to handle them...

such as this:
 - Missing Content-Type
 - Unsupported content type
 - Multipart: Boundary not found

I have this code but it never fire this event
 
	busboy.on('error', function (err) {
		console.error('Error while parsing the form: ', err);
		// some code
	})

**Comment by charmander** [comment]
The constructor can throw; wrap it in a `try`.

**Comment by markstos** [comment]
I'd like docs on error handling recommendations for as well. For example. When parsing a field ab exception might be thrown, but calling `res.send()` there won't stop the control flow, as handlers will continue to fire for other fields that get parsed, resulting in accidentally sending headers multiple times.

**Comment by mscdex** [comment]
@markstos Busboy should not throw exceptions during actual parsing. If it is, please file a new issue.

Additionally, in general you shouldn't send a response from within a `file` or `field` event handler, but instead from a `finish` event handler. The exception to this might be if you strictly want to respond only when a (last) file is completely written to disk first.

**Comment by markstos** [comment]
@mscdex, thanks for the prompt and helpful response.

My case is that I'm calling `JSON.parse` in a field handler, and trying to handle the exception that JSON.parse might throw.   Would you recommend accumulating errors that might come up in the `field` or `file` handlers, then reporting them once in the `finish` handler?

In my case, I know once the first JSON.parse exception is thrown, there's no need to parse other fields or  files.

**Comment by mscdex** [comment]
@markstos In that case, you could just unpipe the request from the busboy instance, remove your event handlers, and send a response back from the `catch` portion of your try-catch that wraps the `JSON.parse()`.

**Comment by markstos** [comment]
Thanks for the suggestion.

**Comment by mscdex** [comment]
The rule of thumb for errors is that if it is an error that occurs due to function argument problems (e.g. validation), an error will be thrown immediately. Otherwise all other errors that occur (after the next tick) are emitted as `'error'` events.

**Comment by tiblu** [comment]
For others struggling to understand how Busboy errors should be handled, take a look at Multers-s code or use Multer instead - https://github.com/expressjs/multer/blob/master/lib/make-middleware.js#L45
