### ISSUE TITLE
File event not invoke

### ISSUE THREAD

**Issue by KyiMoeCho** [mscdex/busboy#86]
I have a simple route handler that accepts file uploads. However, the following code doesn't work. The route gets called but file event is not fired. I've been checking my code against examples and couldn't find what causing this. I appreciate much anyone could point out what causing this.

    restify = require('restify'),
    BusBoy	= require('busboy');
    request			= require('request');
    session = require('restify-session')({
        debug : false,
        ttl : 200           // Time to live in seconds
    });
    server = restify.createServer();
    server.post('/files', uploadFile);    

    server.listen(8082);
    function uploadFile(req, res, next) {   
        var fileStream = new BusBoy({ headers: req.headers });                      
        req.pipe(fileStream);       
        fileStream.on('file', function(fieldname, file, filename, encoding, mimetype) {
            console.log('File [' + fieldname + ']: filename: ' + filename + ', encoding: ' + encoding + ', mimetype: ' + mimetype); 
            res.end();      
        });
    }

**Comment by mscdex** [comment]
What does `console.dir(req.headers['content-type'])` show?

**Comment by KyiMoeCho** [comment]
It shows 'multipart/form-data; boundary=------------------------------201507131017555996559'

**Comment by mscdex** [comment]
If you add a `field` event handler, does your "file" show up there? If not, you might try changing:

```javascript
req.pipe(fileStream);
```

with something like:

```javascript
req.on('data', function(d) {
  console.dir(d.toString());
});
```

to see what, if any, data is coming through.

**Comment by KyiMoeCho** [comment]
I've tried with field. It doesn't get called either. I just tested with data event just like you said, and I can see the data coming.

**Comment by mscdex** [comment]
Can you post the raw data somewhere?

**Comment by KyiMoeCho** [comment]
It's a very small gif file. I output the raw data to a file inside your data event callback function - http://s000.tinyupload.com/?file_id=09426211067626086587

**Comment by mscdex** [comment]
If that file is the exact contents of your request data stream (what you see with the `req.on('data', ...)` code snippet I posted earlier), then the data is not formatted properly as a `multipart/form-data` request.

Can you show what you are using to make the request to the server?

**Comment by KyiMoeCho** [comment]
You are right! The data is not formatted properly. I was using Invoke-restmethod from powershell and set the content-type to multipart. I thought that's sufficient enough to upload files. My supervisor pointed that out as well. Thanks a heap for your time!!

**Comment by jgujgu** [comment]
A code snippet from above really helped me out. I'm sending an audiofile from Faraday as a multipart post. 

```js
var fileStream = new BusBoy({ headers: req.headers });                      
    req.pipe(fileStream);       
    fileStream.on('file', function(fieldname, file, filename, encoding, mimetype) {
        console.log('File [' + fieldname + ']: filename: ' + filename + ', encoding: ' + encoding + ', mimetype: ' + mimetype); 
        res.end();      
    });
```
And the Rails/Ruby:

```ruby
url = 'http://localhost:8080/'
conn = Faraday.new(:url => url ) do |c|
    c.request :multipart
    c.request :url_encoded
    c.adapter :net_http
end
payload = { :file => Faraday::UploadIO.new(file_path, content_type) }
response = conn.post '', payload
json = JSON.parse response.body
puts response.body

```

**Comment by mscdex** [comment]
@jgujgu FWIW it may not be safe to call `res.end()` inside the `'file'` event as the `file` stream may not have buffered the entire file contents and `res.end()` may close the connection too soon. If you meant to only parse the first file, then you might consider instead placing `res.end()` inside a `file.on('end', ...)` handler and maybe even removing the `'file'` event handler at the same time to be extra sure.

**Comment by jgujgu** [comment]
Thank you for advice, @mscdex. I ended up using the busboy "finish" listener quite successfully here. I changed the var names a bit from before.

```js
var busboy = new Busboy({ headers: req.headers });
req.pipe(busboy);
busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
    audioFileName = filename + ".ogg";
    var saveTo = path.join("audio_temp", path.basename(audioFileName));
    file.pipe(fs.createWriteStream(saveTo));
});
busboy.on('finish', function() {
    //Finish it
}
```
