### ISSUE TITLE
busboy receive uploaded files from FormData not working for me

### ISSUE THREAD

**Issue by morfies** [mscdex/busboy#87]
Hi, someone please come and give me a hand. Big thanks ahead.
Here is my server side code:
```javascript
req.busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
			var name = Date.now()+filename;
			var dest = path.join(__dirname + "/../public/uploads/" + name);
			console.log(dest);
			var writer = fs.createWriteStream(dest);
			file.pipe(writer);
			req.filename = name;
});
```
it basically read file streams from request and then pipe to my upload folder with renamed filename.

Client code:
```javascript
var formData = new FormData();
formData.append("file",$(filename)[0].files[i]);
$.ajax({
	url: posturl,  //server script to process data
	type: 'POST',
	data: formData,
	cache: false,
	contentType: false,
	processData: false,
	success: function(data){}
});
```
These codes are just like many a examples do, but files uploaded onto the server are not right for me.  The size gets bigger and once I open the uploaded file, most of the images are just broken, with sometimes some images get partly correct like this:
![1437594077838node usage](https://cloud.githubusercontent.com/assets/10559010/8824903/cfbc8eee-30ac-11e5-8de9-d6686c4aa546.png)

Another problem is the size of one same pic would vary between different tries.

**Comment by mscdex** [comment]
Inside your `file` event handler, what does `console.log('mimetype=%j; encoding=%j', mimetype, encoding);` show?

Would it be possible for you to save the raw request data and upload it somewhere for me to look at? For example, remove busboy usage and do something like:

```javascript
var ws = fs.createWriteStream('/tmp/req.txt');
req.pipe(ws).on('finish', function() {
  console.log('Done writing request');
  res.sendStatus(200);
});
```

**Comment by morfies** [comment]
thanks.
if I console.log all the params the result shows:
===filename:Full-Stack-Dev.png;fieldname:file;mimetype:image/png;encoding:7bit

The req.txt is something unreadable, how can i send it to u then

**Comment by mscdex** [comment]
Ok, those values all look fine. You can attach the file via email and send it to mscdex_at_mscdex.net (no underscores).

**Comment by mscdex** [comment]
Both of the raw data files you sent me had extra carriage returns throughout the file. If you're still having trouble and can come up with a simple, minimal, reproducible example, I can try it out on my end (also if you can make the same exact image file available too for completeness that would be great).

**Comment by morfies** [comment]
I will try it on another server env. If that fails too, I will come up with a minimal example.  thanks

**Comment by morfies** [comment]
Hi buddy, I finally figured out what's wrong with my code.
I added 
req.setEncoding('utf-8');
to my req at I don't know when and why.

After I commented out this line.
Everything works as expected, both busboy and connect-busboy

I am terribly sorry for my bad.

**Comment by mscdex** [comment]
No problem. I'm glad you got it working :-)
