### ISSUE TITLE
Parsing error with deep data

### ISSUE THREAD

**Issue by yanickrochon** [mscdex/busboy#88]
When I perform a query like 

```
$.ajax({ 
  method: 'PUT',
  url: '/foo/bar',
  data: { 
    key1: [ 
      { 
        key2: [
          {
            key3: [
              {
                key3a:"foo",
                key3b:"bar",
                key3c:"buz"
              }
            ]
          }
        ]
      }
    ]
  }
});
```

Then the parsed data returned is

```
{
  "key1": [
    {
      "key2": [
        {
          "key3": [
            {
              "[key3a]": "foo",
              "[key3b]": "bar",
              "[key3c]": "buz"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by mscdex** [comment]
This module does not implicitly parse/handle nesting. Can you show the code you're using?

**Comment by yanickrochon** [comment]
I just figured posting here. I'm actually using `co-busboy` as a middleware with `koa`. I'm not sure what code to show you, really...

**Comment by mscdex** [comment]
Can you post the raw body payload here, as sent by the browser?

**Comment by yanickrochon** [comment]
The payload is this 

```
key1[0][key2][0][key3][0][key3a]:foo
key1[0][key2][0][key3][0][key3b]:bar
key1[0][key2][0][key3][0][key3c]:buz
```

or raw

```key1%5B0%5D%5Bkey2%5D%5B0%5D%5Bkey3%5D%5B0%5D%5Bkey3a%5D=foo&key1%5B0%5D%5Bkey2%5D%5B0%5D%5Bkey3%5D%5B0%5D%5Bkey3b%5D=bar&key1%5B0%5D%5Bkey2%5D%5B0%5D%5Bkey3%5D%5B0%5D%5Bkey3c%5D=buz```

**Comment by mscdex** [comment]
I'm not able to reproduce that with `co-busboy`. Even looking at that module's code, there is nothing in there that tries to parse the brackets into an object like you originally showed. Also as far I'm aware of after briefly looking at koa's code, they don't do any kind of transformations there either.

Perhaps you're using some other middleware that is performing the data conversion?

**Comment by yanickrochon** [comment]
You are right, I just found the other probable culprit; `koa-body-parser`. I'll open the issue with that project. Thank you, and sorry :)
