### ISSUE TITLE
node file upload middleware

### ISSUE THREAD

**Issue by cesarvargas00** [mscdex/busboy#91]
Hi, I'm trying to create a middleware to easily access the files uploaded with busboy.
The problem is that im putting `next()` inside the `on('file')` callback. The problem with this is that
whenever I try to upload more than 1 file, since the event call will be async, 
I cannot guarantee that both files will be inside the `request.files` object.

Well, I think the best place to put the `next()` call would be inside the `on('finish')` event callback.
The thing is, this method is not being called because I'm not handling the file stream: I'm just putting
it inside the `request.files` object.

Possible solutions:
- Handle the Stream of all files and save them to disk. Then later pipe the disk content to whatever
    place we want inside.
- Use a timer and a counter. The timer keeps checking the counter to see if it is equal the
    number of files that are being uploaded, if they are, just call `next()`.
- Handle the Stream of all files and save them to Buffer variables. Save the variables inside the
    `request.files`, and then call `next()` on the `on(finish)` event. Transform the buffer into readable Streams
    and pipe them to a file or to mongodb.

I think the better solution would be the latter, but I was wondering what's your opinions.
so... What should I do?

Here is the link to the git repository:

[github.com/cesarvargas00/nodefu](http://github.com/cesarvargas00/nodefu)

Take a look where I'm calling `next()` on line 53, and my question will probably be clearer.

**Comment by mscdex** [comment]
Well, I don't have any particular opinion, it just depends on the application. Trying to decide on a single solution that works for every situation is impossible.

What if there is only 1 file? 10 files? What if the files are all small and could fit into memory? What if they are all large files? What if there are both large and small files?

FWIW the way I handled this in the [`reformed`](https://github.com/mscdex/reformed) module was to instead have the end user define up front the expected fields/files and how they should be handled (e.g. custom stream callback, saved to disk, buffered in memory, etc.). That way when a field/file matches, you know exactly how it should be handled.

**Comment by cesarvargas00** [comment]
@mscdex Thank you for the answer! I think I will use the reformed module for my application. Thanks!
