### ISSUE TITLE
Load oreder of "field, file..."?

### ISSUE THREAD

**Issue by thearabbit** [mscdex/busboy#99]
I don't understand of order loading
```js
    busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated) {
     ......................
      console.log('first');
    });
busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
      ..............
      console.log('second');
    });

// Show
second
first
```
Please help me.

**Comment by mscdex** [comment]
The order of the events corresponds 1:1 with the order in which the fields are defined in the request.

So for example in HTML forms, the literal order of the input fields in the DOM is what determines the order in which fields are sent to the server. Similarly if you use something like the FormData API, it's the order in which you `append()` fields.

**Comment by thearabbit** [comment]
Thanks for your reply.
I use this with `mongodb-restore npm` in `Meteor JS` 
```js
// Form
<input type="file"

// Client
var formData = new FormData($form[0]);
formData.append('dropCollections', dropCollections);

// Server
restore = Npm.require('mongodb-restore');
var options = {
     uri: process.env.MONGO_URL,
     parser: 'bson'
};
busboy.on('field', function(fieldname, val, fieldnameTruncated, valTruncated) {
   options.dropCollections: .............    
});
busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
   options.stream = file
});

busboy.on('finish', function() {
      restore(options);
      res.writeHead(303, { Connection: 'close', Location: '/' });
      res.end();
});

// But don't work.
```
And then I tried to replace `restore()` into `busboy.on('file'....)`, it work fine. but `options.dropCollections is undefined`

**Comment by mscdex** [comment]
Ok, so your text field is appended, so it's being sent *after* the file. In your server code you've shown so far, you're not ever reading from the file stream so the parser stops parsing once the file stream's internal buffer fills up.

The solution is to do *something* with your file stream. Pipe it somewhere, buffer it in memory, or something else, depending on what is acceptable for your application. Once the file stream starts to be read from, the parser can continue on and eventually you will get your text field.

**Comment by thearabbit** [comment]
Could I prepend the `dropCollections`  before the file?

**Comment by mscdex** [comment]
Yes, if you add the text field (hidden or otherwise) *before* the file, you will receive it first.

**Comment by thearabbit** [comment]
Could example to use with `on('finish')` for file?

**Comment by mscdex** [comment]
I'm not sure what you are asking. If you're wanting to explicitly listen for the end of the `file` stream, it's just a plain Readable stream so you could just do `file.on('end', ...);`

**Comment by thearabbit** [comment]
could example use in?
```js
busboy.on('finish', function() {
      restore(options);
      res.writeHead(303, { Connection: 'close', Location: '/' });
      res.end();
});
```

**Comment by mscdex** [comment]
I haven't used mongo before, so I'm not sure exactly what `restore()` does, but you will probably need to do that inside the `file` event handler (assuming you just have one file), so that the file stream will be read from (again, guessing at the behavior of `restore()` here).

**Comment by thearabbit** [comment]
Thanks again.
